### ISSUE TITLE
Dynamic Pvalues 

### ISSUE THREAD

**Issue by Owen-haha** [MRCIEU/TwoSampleMR#101]
Hi Developer,

I realize that the Pvalues given by `mr()` can have different values when I run it multiple times with the same input on the same R-terminal. 
Sometimes the reported Pvalue is **less than 0.05** but sometimes not. It happens in three default methods: _Weighted median, Simple mode and Weighted mode_. 

For example, here is one output from my running.
> First run:
           method         b        se       pval
 Weighted median 0.6996191 0.2217217 0.00160282
     Simple mode 0.7315045 0.2809381 0.05980901
   Weighted mode 0.7315045 0.2689338 **0.05298595**

> Second run:
            method         b        se        pval
 Weighted median 0.6996191 0.2151182 0.001144936
     Simple mode 0.7315045 0.2913609 0.066011713
   Weighted mode 0.7315045 0.2587905 **0.047507308**

To help you replicate my problem, attached below is my instruments and codes. 
[531.2803_1.510833_to_id1090_instruments.txt](https://github.com/MRCIEU/TwoSampleMR/files/3399445/531.2803_1.510833_to_id1090_instruments.txt)
[mr_code.txt](https://github.com/MRCIEU/TwoSampleMR/files/3399446/mr_code.txt)

**Can you give me a hint how can it happen and how do I interpret this results?** 
Looking forward to hearing from you!

Thanks,
Owen

**Comment by explodecomputer** [comment]
Hi @Owen-haha 

The standard errors for these methods are obtained using random bootrstraps. This means each time you run the analysis you will get a slightly different result unless you define the random seed e.g.

```
set.seed(1234)
```

before you start the analysis, this will ensure you always get the same result. You can increase the number of bootstraps by changing the `nboot` value in the `parameters` argument for the mr function which might make it a bit less variable between runs. Also, it's worth just mentioning that it's generally not good practice to have your conclusions hinge on whether the p-value is below some arbitrary threshold.

Cheers
Gib
