### ISSUE TITLE
 an error when loading  TwoSampleMR package

### ISSUE THREAD

**Issue by SunnyWit** [MRCIEU/TwoSampleMR#104]
Hi, recently i use the TwoSampleMR package,it reture an error, how can i solve this problem?

ao <- available_outcomes()
2019-08-07 17:33:35> No httr_oauth_cache file found at mrbase.oauth - creating new file.
Adding mrbase.oauth to .gitignore
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Connection timed out after 10000 milliseconds

**Comment by explodecomputer** [comment]
it looks like you might be running this on a server that doesn't have a web browser. See the instructions here https://mrcieu.github.io/TwoSampleMR/#authentication

**Comment by SunnyWit** [comment]
I run:
ao <- available_outcomes()


computer then opened a web browse,I signed in to the Google account and authenticate access to MR Base.  then I closed the browse. 
I returned to R, but it suggested an error as I put in the above problem. This function created a new file called mrbase.oauth，but it was an empty file. 



---Original---

**Comment by explodecomputer** [comment]
Sorry, I see it doesn't seem to be an authentication issue. 
I'm running this now and it doesn't give me an error, so the server is fine. Could you try

```
ao <- available_outcomes(access_token=NULL)
```

Also check that your internet connection is fast enough as it is downloading a fairly large list of studies

**Comment by SunnyWit** [comment]
thanks！
But it didn't work after try:
ao <- available_outcomes(access_token=NULL)
the Mr base laugh was still empty
I thought I can sign in Google account, so  the internet connection should be unblocked
I don't know why





---Original---

**Comment by luochihiro** [comment]
hi，I meet the sample question, so have you ever solved this problem?

**Comment by explodecomputer** [comment]
Hi

I would try this:

```
ao <- available_outcomes(access_token=NULL)
```

It prevents it from trying to authenticate via google. If it still doesn't work then please check your firewall settings, it might be blocking access to http://api.mrbase.org

**Comment by explodecomputer** [comment]
This is actually the same issue, please provide `access_token=NULL` for the extract_outcome_data function also. You may need to provide it for other functions that query the mr-base database through the API also

**Comment by luochihiro** [comment]
> This is actually the same issue, please provide `access_token=NULL` for the extract_outcome_data function also. You may need to provide it for other functions that query the mr-base database through the API also

YES!
It works!
Thank you very much! You really help me solve a big problem which disturbs me for a long time!
Best wishes to you!

**Comment by explodecomputer** [comment]
Great thanks for letting me know, good luck

**Comment by Arnold-wong** [comment]
> I run: ao <- available_outcomes() computer then opened a web browse,I signed in to the Google account and authenticate access to MR Base. then I closed the browse. I returned to R, but it suggested an error as I put in the above problem. This function created a new file called mrbase.oauth，but it was an empty file.
> […](#)
> ---Original--- From: "gibran hemani"<notifications@github.com> Date: Wed, Aug 7, 2019 19:02 PM To: "MRCIEU/TwoSampleMR"<TwoSampleMR@noreply.github.com>; Cc: "SunnyWit"<2970138204@qq.com>;"Author"<author@noreply.github.com>; Subject: Re: [MRCIEU/TwoSampleMR] an error when loading TwoSampleMR package (#104) it looks like you might be running this on a server that doesn't have a web browser. See the instructions here https://mrcieu.github.io/TwoSampleMR/#authentication — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

I had the same bug, the file named "mrbase.oauth" is empty, when I run the code like this , the bug shows:
ao <- available_outcomes()
2019-09-24 17:28:45> No httr_oauth_cache file found at mrbase.oauth - creating new file.
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Connection timed out after 10000 milliseconds
and when I add "access_token=NULL" , the bug is :
ao <- available_outcomes(access_token=NULL)
Error in function (type, msg, asError = TRUE)  : 
  Operation timed out after 299990 milliseconds with 3660498 out of 14061912 bytes received
How can I solve it,please

**Comment by lxtkkk123** [comment]
When I try to conduct MR analysis, I face the problem: 
> ao<-available_outcomes()
Error in api_query("gwasinfo", access_token = access_token) : 
  The query to MR-Base exceeded 300 seconds and timed out. Please simplify the query

How can I handle it?

**Comment by lxtkkk123** [comment]
And I have tried like this: 
> ao <- available_outcomes(access_token=NULL)
Error in api_query("gwasinfo", access_token = access_token) : 
  The query to MR-Base exceeded 300 seconds and timed out. Please simplify the query
It still does not work. Please help me !

**Comment by lxtkkk123** [comment]
And I have tried like this:

ao <- available_outcomes(access_token=NULL)
Error in api_query("gwasinfo", access_token = access_token) :
The query to MR-Base exceeded 300 seconds and timed out. Please simplify the query

It still does not work. Please help me !

**Comment by yemaozi285** [comment]
> And I have tried like this:
> 
> ao <- available_outcomes(access_token=NULL)
> Error in api_query("gwasinfo", access_token = access_token) :
> The query to MR-Base exceeded 300 seconds and timed out. Please simplify the query
> 
> It still does not work. Please help me !

Hi! l met the same question as yours , but before this try, it works. So l don't know how to solve it. bro……

**Comment by ElizabethSissi** [comment]
> ao <- available_outcomes()
Error in `dplyr::bind_rows()`:
! Argument 1 must be a data frame or a named atomic vector.
Run `rlang::last_trace()` to see where the error occurred.
> ao
Error: object 'ao' not found
> rlang::last_trace()
<error/rlang_error>
Error in `dplyr::bind_rows()`:
! Argument 1 must be a data frame or a named atomic vector.
---
Backtrace:
    ▆
 1. ├─TwoSampleMR::available_outcomes()
 2. │ └─ieugwasr::gwasinfo(opengwas_jwt = opengwas_jwt)
 3. │   ├─dplyr::bind_rows(out) %>% ...
 4. │   └─dplyr::bind_rows(out)
 5. └─dplyr::select(., "id", "trait", dplyr::everything())
Run rlang::last_trace(drop = FALSE) to see 1 hidden frame.
> rlang::last_trace()
<error/rlang_error>
Error in `dplyr::bind_rows()`:
! Argument 1 must be a data frame or a named atomic vector.
---
Backtrace:
    ▆
 1. ├─TwoSampleMR::available_outcomes()
 2. │ └─ieugwasr::gwasinfo(opengwas_jwt = opengwas_jwt)
 3. │   ├─dplyr::bind_rows(out) %>% ...
 4. │   └─dplyr::bind_rows(out)
 5. └─dplyr::select(., "id", "trait", dplyr::everything())
Run rlang::last_trace(drop = FALSE) to see 1 hidden frame.

In my situation, the ao doesn't work too, I need help. THX!!!!!!

**Comment by nuomiou** [comment]
> > ao <- available_outcomes()
> > Error in `dplyr::bind_rows()`:
> > ! Argument 1 must be a data frame or a named atomic vector.
> > Run `rlang::last_trace()` to see where the error occurred.
> > ao
> > Error: object 'ao' not found
> > rlang::last_trace()
> > <error/rlang_error>
> > Error in `dplyr::bind_rows()`:
> > ! Argument 1 must be a data frame or a named atomic vector.
> 
> Backtrace: ▆
> 
> 1. ├─TwoSampleMR::available_outcomes()
> 2. │ └─ieugwasr::gwasinfo(opengwas_jwt = opengwas_jwt)
> 3. │   ├─dplyr::bind_rows(out) %>% ...
> 4. │   └─dplyr::bind_rows(out)
> 5. └─dplyr::select(., "id", "trait", dplyr::everything())
>    Run rlang::last_trace(drop = FALSE) to see 1 hidden frame.
> 
> > rlang::last_trace()
> > <error/rlang_error>
> > Error in `dplyr::bind_rows()`:
> > ! Argument 1 must be a data frame or a named atomic vector.
> 
> Backtrace: ▆
> 
> 1. ├─TwoSampleMR::available_outcomes()
> 2. │ └─ieugwasr::gwasinfo(opengwas_jwt = opengwas_jwt)
> 3. │   ├─dplyr::bind_rows(out) %>% ...
> 4. │   └─dplyr::bind_rows(out)
> 5. └─dplyr::select(., "id", "trait", dplyr::everything())
>    Run rlang::last_trace(drop = FALSE) to see 1 hidden frame.
> 
> In my situation, the ao doesn't work too, I need help. THX!!!!!!

I have the same problem as you. Have you solved it?

**Comment by yemaozi285** [comment]
Sorry for that, I have solved this problem but without a doubt, in my opinion, it may be the format error or internet error.




Doc.Feng
***@***.***

Guangzhou&nbsp;Medical&nbsp;University
Dr.
+86&nbsp;18076291855
国家呼吸中心胸外科、呼研所



------------------ Original ------------------
From: nuomiou ***@***.***&gt;
Date: Fri,Aug 9,2024 0:05 AM
To: MRCIEU/TwoSampleMR ***@***.***&gt;
Cc: yi feng ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [MRCIEU/TwoSampleMR]  an error when loading  TwoSampleMR package(#104)





   
ao <- available_outcomes()
 Error in dplyr::bind_rows():
 ! Argument 1 must be a data frame or a named atomic vector.
 Run rlang::last_trace() to see where the error occurred.
 ao
 Error: object 'ao' not found
 rlang::last_trace()
 <error/rlang_error&gt;
 Error in dplyr::bind_rows():
 ! Argument 1 must be a data frame or a named atomic vector.
  
Backtrace: ▆
  
├─TwoSampleMR::available_outcomes()
 
│ └─ieugwasr::gwasinfo(opengwas_jwt = opengwas_jwt)
 
│   ├─dplyr::bind_rows(out) %&gt;% ...
 
│   └─dplyr::bind_rows(out)
 
└─dplyr::select(., "id", "trait", dplyr::everything())
 Run rlang::last_trace(drop = FALSE) to see 1 hidden frame.
   
rlang::last_trace()
 <error/rlang_error&gt;
 Error in dplyr::bind_rows():
 ! Argument 1 must be a data frame or a named atomic vector.
  
Backtrace: ▆
  
├─TwoSampleMR::available_outcomes()
 
│ └─ieugwasr::gwasinfo(opengwas_jwt = opengwas_jwt)
 
│   ├─dplyr::bind_rows(out) %&gt;% ...
 
│   └─dplyr::bind_rows(out)
 
└─dplyr::select(., "id", "trait", dplyr::everything())
 Run rlang::last_trace(drop = FALSE) to see 1 hidden frame.
  
In my situation, the ao doesn't work too, I need help. THX!!!!!!
  
I have the same problem as you. Have you solved it?
