### ISSUE TITLE
GWAS catalog up to date?

### ISSUE THREAD

**Issue by krz** [MRCIEU/TwoSampleMR#110]
Hi,
Is the packages `gwas_catalog` data up to date? I tried finding some newer studies, e.g. the Yengo et al. (2018) BMI study, but it seems it's not there.

**Comment by mightyphil2000** [comment]
Hi there
I have just updated it in the MRInstruments package. The previous version was out of date.

**Comment by krz** [comment]
thanks, appreciate it
