### ISSUE TITLE
Difficulty in "could not find function **" in many cases

### ISSUE THREAD

**Issue by Jiangqiner** [MRCIEU/TwoSampleMR#114]
Dear sir, I encountered a series of similar questions which presented "could not find function ***", for example :
1.  >bmi_exp_dat <- clump_data(bmi_exp_dat)
Error in clump_data(bmi_exp_dat) : could not find function "clump_data"
2. >chd_out_dat <- extract_outcome_data (snps = bmi_exp_dat$SNP, outcomes = 7)
Error in extract_outcome_data(snps = bmi_exp_dat$SNP, outcomes = 7) :  could not find function "extract_outcome_data"

Would you give me some advice? thank you very much!

**Comment by ValeriiaH** [comment]
Have you installed and attached the TwoSampleMR package ?
devtools::install_github("MRCIEU/TwoSampleMR")
library(TwoSampleMR)

**Comment by Jiangqiner** [comment]
Yes, I have installed the TwoSampleMR and other relevant packages , and I have solved my problem, thank you very much.




------------------ 原始邮件 ------------------
发件人: "Valeriia Haberland"<notifications@github.com>;
发送时间: 2019年9月2日(星期一) 晚上6:13
收件人: "MRCIEU/TwoSampleMR"<TwoSampleMR@noreply.github.com>;
抄送: "JQ"<1538028262@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [MRCIEU/TwoSampleMR] Difficulty in "could not find function **"in many cases (#114)




Have you installed and attached the TwoSampleMR package ?
 devtools::install_github("MRCIEU/TwoSampleMR")
 library(TwoSampleMR)
