### ISSUE TITLE
Problem using clump_data function and generating mrbase.oauth 

### ISSUE THREAD

**Issue by KlerB** [MRCIEU/TwoSampleMR#115]
Hello,

I want to use the function clump_data on SNPs I selected but after harmonizing my data set and applying the function, I get an error message:
```
clump_window = 10000
r2_cutoff <- 0.001
table_exp_clumped <- clump_data(table_exp,
                        clump_kb = clump_window, 
                        clump_r2 = r2_cutoff, 
                        clump_p1 = 1,
                        clump_p2 = 1)
Clumping n63u4S, 178 SNPs
Error: Forbidden
```

I guessed it was because the file mrbase.oauth was not generated. Could you confirm that assumption? If not, what would be the explanation of the message “Error: Forbidden”? 

Concerning the generation of mrbase.oauth, I tried to do it using ao <- available_outcomes(). However, after having logged into my Google account I got a message such as:
This site is inaccessible
localhost does not allow the connection.
•	Do a Google search on localhost 1410.
ERR_CONNECTION_REFUSED

Hence, I could not write the file mrbase.oauth. Could it be possible to generate it offline, and so to send me the file? Else, could you provide another solution?

Thank you very much!

Claire

**Comment by mightyphil2000** [comment]
Hi Claire

Are you working on a server? A workaround would be to generate the file locally and transfer over to your working directory.
________________________________

**Comment by KlerB** [comment]
Hi,

Thank you for your quick answer. Indeed, I forgot to mention I am working on a Rstudio server. How can the file be generated locally ?

Thanks,

Claire

**Comment by mightyphil2000** [comment]
Where are you running R studio?
________________________________

**Comment by KlerB** [comment]
I am running Rstudio on a platform hosted by my Institute on servers. Hence I am not running Rstudio from my computer (it is not installed on it).

**Comment by mightyphil2000** [comment]
Run available_outcomes on your local machine. You could do so by opening R on your local machine, then load the TwoSampleMR library. Then type available_outcomes(). then type getwd() to find out the working directory. The mrbase.oauth file should be there. Then you will need to copy over that file to the working directory on the R studio server.

Alternatively, if you want to generate the file directly on your rstudio server you will have to contact your IT support for help.
________________________________

**Comment by KlerB** [comment]
Thank you for your help but unfortunately I do not have the administrator rights on my computer and thus cannot install R on it. That's why I have to work on my institute rstudio server.

I had contacted my IT support for help and they wanted to know if it was possible to generate the mrbase.oauth file offline by sending it to us so we can generate it on the rstudio server ?

**Comment by mightyphil2000** [comment]
Yes it is possible. You can generate it locally on your own machine in R then send it over. Perhaps you can ask someone with admin rights to install R for you.
________________________________

**Comment by KlerB** [comment]
Ok then this means I must install R locally so I can generate it after on the Rstudio server ?

**Comment by mightyphil2000** [comment]
Well the idea is that you generate it locally in R and copy it over to the server. You're not generating it on the server. You're copying it to the server. But I suppose if you manage to install R on your local machine you may no longer need access to the server at all.


________________________________

**Comment by explodecomputer** [comment]
On the problem of the clump_data function - this doesn't actually use the mrbase.oauth token, I am not sure why you would be getting a 'forbidden' error. Can you try this:

```
ao <- available_outcomes(access_token=NULL)
```

**Comment by remlapmot** [comment]
I'm pretty sure that R can be installed without Admin rights on all operating systems. On some of the installers choose the install for this user options (instead of all users). And it helps to choose a library path without spaces, e.g.
https://cran.r-project.org/bin/windows/base/rw-FAQ.html#How-do-I-install-R-for-Windows_003f


Additionally RStudio can be installed without Admin rights. This may be possible from within their installer but certainly from their preview version download page for the Windows version you can download and unzip the first download under the *Zip/Tarballs* section:

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by KlerB** [comment]
@explodecomputer Thank you for your suggestion. I tried your code but I received this error message:
`Error: lexical error: invalid char in json text.
                                       <HTML><HEAD>  <TITLE>Access Den
                     (right here) ------^`

Do you know why I get this and if that could explain why clump_data does not work ? My hypothesis is that the Rstudio server from my Institute does not allow to get data from external server (which is the case for getting linkage desequilibrium values if I'm correct). This could explain why I get "Error: Forbidden" when I use the clump_data fonction. Do you think this is plausible or the explanation is elsewhere ?

@remlapmot Thank you for your suggestions, I will try to install R and Rstudio following the instructions in the links you sent. I might still have some struggles accessing the Internet using these local installations due to the network security infrastructure of my Institute. I'll see how it goes.

**Comment by explodecomputer** [comment]
Yeah it could well be a server firewall issue - it would explain why the API functions aren't working.

**Comment by KlerB** [comment]
@explodecomputer Thanks for your feedback. I'll see with my IT support if the Institute server firewall could be responsible for this clump_data issue, and see what we can do about it.

**Comment by KlerB** [comment]
I checked with my IT support, indeed the request goes through a proxy. Could you provide the API URL/URL that need to be allowed through Proxy for the functions clump_data and power_prune (I face the same issue as with clump_data) ? Or even for the whole TwoSampleMR package ? For now I did not meet other issues with other functions from the package but I have not used them all.
Thanks a lot!

**Comment by explodecomputer** [comment]
This is the url:

http://api.mrbase.org/

**Comment by KlerB** [comment]
Thank you very much for the link!
