### ISSUE TITLE
Error: Path 'mrbase.oauth' does not exist

### ISSUE THREAD

**Issue by WhiteDesk52** [MRCIEU/TwoSampleMR#116]
I've installed the TwoSampleMR package, and I am running RStudio on a desktop. When I attempt to carry out the first step of the basic analysis, authentication, I get an error and can't seem to get passed it. Code is below. Any advice would be appreciated.

> ao <- available_outcomes()
Error: Path 'mrbase.oauth' does not exist

**Comment by explodecomputer** [comment]
In the last few days the package used to manage authentication has updated and broken previous functionality. I'm looking for a way to fix this but for the time being just install the old version of the package using:

```
devtools::install_github("MarkEdmondson1234/googleAuthR@v0.8.1")
```

**Comment by minghuihuang** [comment]
The question not resolved  as just install the old version of the package using:
> install.packages("D:/Downloads/MarkEdmondson1234-googleAuthR-v0.8.1-0-gcb974f8.tar.gz", repos = NULL, type = "source")
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
* installing *source* package 'googleAuthR' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'googleAuthR'
    finding HTML links ... 好了
    Authentication                          html  
    checkGoogleAPIError                     html  
    checkTokenAPI                           html  
    doHttrRequest                           html  
    gar_api_generator                       html  
    gar_api_page                            html  
    gar_attach_auto_auth                    html  
    gar_auth                                html  
    finding level-2 HTML links ... done

    gar_auth_service                        html  
    gar_auto_auth                           html  
    gar_batch                               html  
    gar_batch_walk                          html  
    gar_cache_setup                         html  
    gar_check_existing_token                html  
    gar_create_api_objects                  html  
    gar_create_api_skeleton                 html  
    gar_create_package                      html  
Rd warning: C:/Users/Administrator/AppData/Local/Temp/RtmpIpehVu/R.INSTALL1b8cb4221a1/MarkEdmondson1234-googleAuthR-cb974f8/man/gar_create_package.Rd:34: file link 'usethis' in package 'usethis' does not exist and so has been treated as a topic
    gar_debug_parsing                       html  
    gar_discovery_api                       html  
    gar_discovery_apis_list                 html  
    gar_gce_auth                            html  
    gar_gce_auth_default                    html  
    gar_gce_auth_email                      html  
    gar_set_client                          html  
    gar_shiny_auth                          html  
    gar_shiny_auth_url                      html  
    gar_shiny_login_ui                      html  
    gar_shiny_ui                            html  
    gar_token_info                          html  
    get_google_token                        html  
    googleAuth                              html  
    googleAuthR                             html  
    googleAuthUI                            html  
    googleAuth_js                           html  
    googleAuth_jsUI                         html  
    googleSignIn                            html  
    googleSignInUI                          html  
    retryRequest                            html  
    silent_auth                             html  
    skip_if_no_env_auth                     html  
    token_exists                            html  
    with_shiny                              html  
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
* DONE (googleAuthR)
> outcome_data <- extract_outcome_data(snps = exposure_data$SNP, outcomes = 23)
Extracting data for 34 SNP(s) from 1 GWAS(s)
Error: Path 'mrbase.oauth' does not exist
