### ISSUE TITLE
insufficient colours in mr_scatter_plot() when using >12 methods

### ISSUE THREAD

**Issue by AntonioJBT** [MRCIEU/TwoSampleMR#120]
Hi,
Great package, thanks for providing it. An issue:
Looks like `mr_scatter_plot` needs more colours when passing results with more than 12 methods listed, e.g.:
```
mr_method_list()
methods_list <- c("mr_wald_ratio", # single SNP only
                  "mr_two_sample_ml",
                  "mr_egger_regression",
                  "mr_egger_regression_bootstrap",
                  "mr_simple_median",
                  "mr_weighted_median",
                  "mr_penalised_weighted_median",
                  "mr_ivw",
                  # "mr_ivw_radial", # # needs the RadialMR package
                  "mr_ivw_mre",
                  "mr_ivw_fe",
                  "mr_simple_mode",
                  "mr_weighted_mode",
                  "mr_weighted_mode_nome",
                  "mr_simple_mode_nome",
                  # "mr_raps", # needs the mr.raps package
                  "mr_sign",
                  "mr_uwr"
                  )
res_all <- mr(dat, method_list = methods_list)
res_all
p1 <- mr_scatter_plot(res_all, dat)
p1
```
p1 results in
```
$uq7rfs.7
Error: Insufficient values in manual scale. 15 needed but only 12 provided.
```

This might be due to [line 46 in plots.R](
https://github.com/MRCIEU/TwoSampleMR/blob/a0cf89f68d5583b7e42d3c2998894e3eb3c0c415/R/plots.R#L46) which has 12 colours specified. Using 12 or fewer methods plots without errors. Some quick tests that plot without error:
- Removing line 46 (which will choose colours automatically)
- If wanting to keep manual, providing as many colours or more as the number of methods available.
Best,
Antonio

**Comment by explodecomputer** [comment]
Thanks for the message @AntonioJBT 

I think I may need to put a warning about the colours, but in general I'm not sure it's going to be very easy to distinguish between that many and I'd rather not encourage that.

For the time being you can do this:

```
mr_scatter_plot(...)[[1]] +
scale_colour_manual(...)
```

where you specify your own colour palette. You can also try `scale_colour_brewer()` or other methods for generating the colour profile.

**Comment by AntonioJBT** [comment]
Hi,
Thanks, that works and is an easier fix. Also probably bad practice to run all methods without some thought in any case. Closing this now.
Best,
Antonio
