### ISSUE TITLE
The problem of Authentication

### ISSUE THREAD

**Issue by Arnold-wong** [MRCIEU/TwoSampleMR#121]
I had a problem of authentication, I had sign in Google account . but the new file "mrbase.oauth" is empty.How can I solve this problem? Please.

> library("TwoSampleMR", lib.loc="F:/R-3.5.0/library")
Welcome to TwoSampleMR.
[>] Full documentation: https://mrcieu.github.io/TwoSampleMR
[>] Check news(package='TwoSampleMR') for bug fixes and updates
[>] By generating access tokens to retrieve data from the MR-Base
    database you consent to having your email address logged on
    our servers. For info on how this is used see logging_info()
[>] NOTE: We will be rolling out extensive changes to the database
    in the next few weeks. To ensure backwards compatibility please
    keep the R package updated.
> ao <- available_outcomes()
2019-09-24 17:58:03> No httr_oauth_cache file found at mrbase.oauth - creating new file.
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Connection timed out after 10000 milliseconds  

And I had try another method to solve ,but it also had a bug:
> ao <- available_outcomes(access_token=NULL)
Error in function (type, msg, asError = TRUE)  : 
  Operation timed out after 299990 milliseconds with 6271731 out of 14061912 bytes received

so ,how can I solve this problem?

**Comment by explodecomputer** [comment]
Are you behind a firewall that prevents access to http://api.mrbase.org ?

**Comment by Arnold-wong** [comment]
> Are you behind a firewall that prevents access to http://api.mrbase.org ?

I had close the firewall and I can open MRbase on Google, but I cant open the web your offered,when I click this hyperlink ,it only shows some words:
Welcome to the MR-Base API. This was automatically deployed.
How can I do next? Thanks!

**Comment by explodecomputer** [comment]
Hmm, it's quite strange because it seems like it is connecting but it's transferring very slowly. Can you run this:

```
a <- extract_outcome_data("rs234", 2, access_token=NULL, proxies=FALSE)
```

It should return one row very quickly. Also just try reinstalling the package to make sure it is latest version and restarting R

**Comment by Arnold-wong** [comment]
> Hmm, it's quite strange because it seems like it is connecting but it's transferring very slowly. Can you run this:
> 
> ```
> a <- extract_outcome_data("rs234", 2, access_token=NULL, proxies=FALSE)
> ```
> 
> It should return one row very quickly. Also just try reinstalling the package to make sure it is latest version and restarting R

Yes you're right , I seems that the R has connected , because the code you gave me runs like this:

> a <- extract_outcome_data("rs234", 2, access_token=NULL, proxies=FALSE)
Extracting data for 1 SNP(s) from 1 GWAS(s)
> a
    SNP beta.outcome se.outcome samplesize.outcome ncase.outcome ncontrol.outcome pval.outcome
1 rs234       0.0048     0.0036             236157            NA               NA       0.1824
  eaf.outcome effect_allele.outcome other_allele.outcome units.outcome                 outcome
1      0.4417                     G                    A   SD (kg/m^2) Body mass index || id:2
  consortium.outcome year.outcome pmid.outcome id.outcome category.outcome subcategory.outcome
1              GIANT         2015     25673413          2      Risk factor      Anthropometric
  originalname.outcome               outcome.deprecated mr_keep.outcome data_source.outcome
1      Body mass index Body mass index || GIANT || 2015            TRUE              mrbase

But the transmission speed is slowly , how big is this file ? Can I download it from MRbase to local ?

**Comment by explodecomputer** [comment]
It should be an almost instant function. available_outcomes normally takes about 2 seconds. We’re in the process of making all the data available, but it will be a few weeks before it’s ready. Perhaps just try running this in different wifi networks (e.g. at home) and if it runs faster elsewhere then it could be something to do with firewall etc at your current location
