### ISSUE TITLE
lexical error when using the clump_data function 

### ISSUE THREAD

**Issue by Yazhouhe** [MRCIEU/TwoSampleMR#122]
Hi, 
I got the following error message when using the clump_data function:  
"Error: lexical error: invalid char in json text.
                                       <html>  <head><title>504 Gatewa
                     (right here) ------^"    
My guess is the the server could be down during the weekend. Could you kindly help have a look and fix it? 
Thanks

**Comment by explodecomputer** [comment]
Hi it might have been down temporarily but it should be working at the moment. 

 

```

> a <- extract_instruments(2)

Requesting default values. Extracting from pre-clumped data

Loading required package: MRInstruments

b 1 out of 1 requested outcomes have pre-calculated instruments.

> b <- clump_data(a)

Warning: since v0.4.2 the default r2 value for clumping has changed from 0.01 to 0.001

Clumping 2, 79 SNPs

> 

```
