### ISSUE TITLE
Error in res$info : $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by zqcrystal325** [MRCIEU/TwoSampleMR#123]
Hi, 

I was trying to example in R
# Extact instruments for BMI
expsure_dat <- extract_instruments(2)

# Get corresponding effects for CHD
outcome_dat <- extract_outcome_data(exposure_dat$SNP, 7)

# Harmonise
dat <- harmonise_data(exposure_dat, outcome_dat)

# Load the downloaded RData object. This loads the rf object
load("rf.rdata")

# Perform MR-MoE
res <- mr_moe(dat, rf)

However, after I load the"rf.rdata" , I got this error
Error in res$info : $ operator is invalid for atomic vectors

I couln't find the proper way to solve this.

What should I do? Thanks.

**Comment by vackground** [comment]
I´m in the same situation, any ideas to solve this?

**Comment by explodecomputer** [comment]
Hey sorry for the slow reply. The documentation failed to mention a step:

```
library(TwoSampleMR)
load("rf.rdata")
exp <- extract_instruments(2)
out <- extract_outcome_data(exp$SNP, 7)
dat <- harmonise_data(exp, out)
res <- mr_wrapper(dat) # Perform all MR methods and generate metrics
res_moe <- mr_moe(res, rf) # Predict best-performing method
```

Thanks for pointing it out, I'll update the docs
