### ISSUE TITLE
how many kinds of exposure_data and outcome_data 

### ISSUE THREAD

**Issue by Arnold-wong** [MRCIEU/TwoSampleMR#124]
I want to konw how many kinds of exposure_data and outcome_data  in the packages .
I use the code : 
 >available_outcomes()
2019-10-06 18:13:46> No httr_oauth_cache file found at mrbase.oauth - creating new file.
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Connection timed out after 10000 milliseconds

But it seems that my Rstudio runs very solwly and I try another method:
 > ao <- available_outcomes(access_token=NULL)
Error in function (type, msg, asError = TRUE)  : 
  Operation timed out after 299990 milliseconds with 9826811 out of 14061912 bytes received

 The result is same to the last.

but I can extract some data from it like CHD:
> chd_out_dat <- extract_outcome_data(
+   snps = bmi_exp_dat$SNP,
+   outcomes = 7,
+   access_token=NULL,
+   proxies=FALSE
+ )
Extracting data for 38 SNP(s) from 1 GWAS(s)
> 

so , I think it can run but slowly .
I want to konw how many kinds of exposure_data and outcome_data  in the packages .
in another words , "outcomes = ???  "   how can I get these messages?

**Comment by explodecomputer** [comment]
We seem to be noticing this happen when the user is accessing MR-Base from behind a firewall. Please check if that's the case, and maybe try using different internet connections.

This is how many publicly accessible GWAS studies there are:

```
> a <- available_outcomes(access_token=NULL)
> dim(a)
[1] 21282    22
```

**Comment by Arnold-wong** [comment]
Thank you very much ! The code runs after I close the firewall.

> ao <- available_outcomes(access_token=NULL)
> dim(ao)
[1] 21282    22
> head(ao)
  access      author    category consortium
1 public   Dastani Z Risk factor   ADIPOGen
2 public   Jostins L     Disease     IIBDGC
3 public  Randall JC Risk factor      GIANT
4 public       Okbay Risk factor      SSGAC
5 public       Okbay Risk factor      SSGAC
6 public Kilpelainen Risk factor       <NA>
                                                                               filename   id mr
1                                  adipogen.discovery.eur_.meta_.public.release.txt.tab    1  1
2                                                 CD.gwas_ichip_meta_release.txt.gz.tab   10  1
3 GIANT_Randall2013PlosGenet_stage1_publicrelease_HapMapCeuFreq_HIPadjBMI_MEN_N.txt.tab  100  1
4                                                                    DS_Full.txt.gz.tab 1000  1
5                                                              EduYears_Main.txt.gz.tab 1001  1
6                                                       Leptin_Adjusted_for_BMI.txt.tab 1002  1
  ncase ncontrol                                                    note    nsnp
1    NA       NA                                                    <NA> 2675209
2 14763    15977                                                    <NA>   13898
3    NA       NA                                        Adjusted for BMI 2725796
4    NA       NA                                                    <NA> 6524475
5    NA       NA                                                    <NA> 8146841
6    NA       NA Adjusted for BMI; effect allele frequencies are missing 2474010
                                                                                                       path
1                                                   /projects/MRC-IEU/publicdata/GWAS_summary_data/ADIPOGEN
2                                                        /projects/MRC-IEU/publicdata/GWAS_summary_data/IBD
3                                       /projects/MRC-IEU/publicdata/GWAS_summary_data/GIANT_2010_2012_2013
4                               /projects/MRC-IEU/research/data/evidencehub/summary/gwas/raw/SSGAC_27089181
5 /projects/MRC-IEU/research/data/evidencehub/summary/gwas/raw/SSGAC_education_educational_attainment_2016/
6                           /projects/MRC-IEU/research/data/evidencehub/summary/gwas/raw/Kilpelainen_Leptin
      pmid population priority sample_size     sd               sex                subcategory
1 22479202      Mixed        1       39883 0.5700 Males and females                    Protein
2 23128233   European        1       30740     NA Males and females  Autoimmune / inflammatory
3 23754948   European       15       60586 8.4548             Males             Anthropometric
4 27089181   European        1      161460     NA Males and females Psychiatric / neurological
5 27225129   European        1      293723 3.7100 Males and females                  Education
6 26833098   European        1       32161     NA Males and females                    Hormone
                trait       unit year
1         Adiponectin  ln(mg/dL) 2012
2     Crohn's disease   log odds 2012
3   Hip circumference    SD (cm) 2013
4 Depressive symptoms         SD 2016
5  Years of schooling SD (years) 2016
6              Leptin  log ng/ml 2016

**Comment by Hibs941** [comment]
Hi Im trying to conduct an MR analysis and im having trouble reading the outcome file.
I keep getting this error message 
Error in data.table::fread(filename, header = TRUE, sep = sep) : 
  argument "filename" is missing, with no default

I ran this function
>outcome_dat <- read_outcome_data(
  snps = "snps",
   type = "outcome",
   filename = "thyca_physical_activity_outcome_data.txt",
   snp_col = "SNP",
   beta_col = "beta",
   se_col = "se",
   effect_allele_col = "effect_allele",
   other_allele_col = "other_allele",
   eaf_col = "eaf",
   pval_col = "P.val",
   phenotype_col = "Phet"
 )
Error in read_outcome_data(snps = "snps", type = "outcome", filename = "thyca_physical_activity_outcome_data.txt",  : 
  unused argument (type = "outcome")
