### ISSUE TITLE
errors in getting available outcomes

### ISSUE THREAD

**Issue by tlu0918** [MRCIEU/TwoSampleMR#13]
Hi,

I tried the command

##
>library(TwoSampleMR)
> ao <- available_outcomes()
Token cache file: .httr-oauth
Error: lexical error: invalid char in json text.
                                       <html>  <head><title>504 Gatewa
                     (right here) ------^

##
But I keep got the lexical error. How to fix the error? I restarted my desktop and R but still got the same error. The command "ao <- available_outcomes()" worked yesterday.

Thanks!

Ake

**Comment by explodecomputer** [comment]
Hi Thanks for the message. We were updating the database, but everything is back up now

**Comment by tlu0918** [comment]
Thanks! It is working now.

Ake

**Comment by shiccae** [comment]
Hello, I got the same error although yesterday everything was working fine. Is it also because the database is currently updated or is there update I need to install? Thanks in advance.

**Comment by explodecomputer** [comment]
hey sorry about this we appear to be having server issues again. working to fix it. We'll be migrating to a completely new architecture soon that should be much more stable but this particular problem will hopefully resolve within a couple hours

**Comment by shiccae** [comment]
Great - thanks for letting me know.

**Comment by explodecomputer** [comment]
Should be back up now, apologies for the downtime

**Comment by shiccae** [comment]
Working again now, thanks!
