### ISSUE TITLE
ao <- available_outcomes(access_token=NULL)

### ISSUE THREAD

**Issue by Xiongqiaohua** [MRCIEU/TwoSampleMR#132]
When I was running the following code:
          ` ao <- available_outcomes(access_token=NULL)`
I find that the number of the observations  are different every time I run it,I'm curious about the reason? Thank  for your generous answers!

**Comment by explodecomputer** [comment]
Hi @Xiongqiaohua we're adding more datasets and sometimes moving from public to private or vice versa, which means that the number will change quite regularly.
