### ISSUE TITLE
MR Steiger 

### ISSUE THREAD

**Issue by DannyRose101** [MRCIEU/TwoSampleMR#134]
Just trying MR steiger and got the following error:
Error in mr_steiger(p_exp = dat$pval.exposure,  : 
  argument "r_out" is missing, with no default

I cannot find mention to r_out in the documentation
Would there be any other reference or explanation for these tests.

Thanks in advance!

**Comment by kaanokay** [comment]
Hi @DannyRose101 ,

Did you solve this problem? If so, can you explain it here?

Thanks.
Best wishes.

**Comment by explodecomputer** [comment]
Hey both if trying to run the directionality test that uses mr_steiger then create harmonised data frame and run `directionality_test` e.g.

```
a <- make_dat(2,300)
directionality_test(a)
```

otherwise see documentation for arguments expected for `mr_steiger`
