### ISSUE TITLE
Steiger p-values above 1

### ISSUE THREAD

**Issue by stephen8624** [MRCIEU/TwoSampleMR#139]
Hi

I am analysing a continuous exposure on diagnosis of coronary heart disease. Why am I getting Steiger p values above 1?

**Comment by stephen8624** [comment]
this was using the steiger_filtering(dat) option..

**Comment by explodecomputer** [comment]
Sorry about this I made an edit recently that introduced a bug, it is fixed now, thanks for pointing it out to me 5adbf1d
