### ISSUE TITLE
questions about the analysis results by TwoSampleMR

### ISSUE THREAD

**Issue by SunnyWit** [MRCIEU/TwoSampleMR#141]
Hi, recently I do some MR analysis through TwoSampleMR package. in the results, colume" mr_keep" present true or false, if the snp is false, it will be removed in the analysis process, why?
for example:
SNP|effect_allele.exposure | other_allele.exposure | effect_allele.outcome | other_allele.outcome | beta.exposure | beta.outcome | eaf.exposure | eaf.outcome | remove | palindromic | ambiguous|mr_keep
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
rs10740118|G | C | G | C | 0.25 | 0.0149 | 0.56 | 0.5692 | FALSE | TRUE | TRUE|FALSE
then rs10740118 will  not be included in the analysis process, why?

**Comment by explodecomputer** [comment]
By default it assumes that it is unknown whether a variant is on the forward strand. Palindromic SNPs are hard to prove to be on the same strand in the two studies unless the allele frequency is not intermediate. Here it is palindromic with allele frequency 0.56, so it is dropped. You can run `harmonise_data(dat, action=3)` if you want to be less strict, assuming that the exposure and outcome have alleles coded on the forward strand

**Comment by SunnyWit** [comment]
thank you. but i didn't understand why allele frequency 0.56 ,so it is  palindromic. can you explain it ? thanks a lot!

**Comment by explodecomputer** [comment]
Sure -
If the SNP is not palindromic e.g. the forward strand alleles are G and A, then you can easily work out if two studies are on the same strand. If the exposure is on the forward strand and the outcome is on the reverse strand, then the outcome will have alleles C and T, so we can flip them without ambiguity.

For palindromic SNPs (i.e. the alleles are G and C, or A and T), then the forward and reverse strand alleles look the same, flipping G and C gives you C and G. So, now the question is, are they the same strand and the opposite effect alleles, or the opposite strand and the same effect alleles.

We can use the allele frequency to try to work this out. If the G allele in the exposure is 0.9, and the G allele in the outcome is 0.1, then we know that they are on opposing strands.

If the allele frequency is close to 0.5 then we can't be sure about which which is the minor allele as there is sampling variance around the allele frequency.

**Comment by jennysjaarda** [comment]
Hello, 
Just to follow-up with the above. Is the threshold of 0.42/0.58 only used for the exposure AF? In other words, when harmonising and using action=2, does the function take into account outcome AF? What if exposure AF happens to be 0.43 for a palindromic SNP but outcome AF is 0.41. Is this SNP dropped? 

Thanks

**Comment by explodecomputer** [comment]
I think it is either the exposure or outcome frequency being within the threshold

https://github.com/MRCIEU/TwoSampleMR/blob/master/R/harmonise.R#L365
