### ISSUE TITLE
Cannot find fromJSON_safe() function while running extract_outcome_data()

### ISSUE THREAD

**Issue by dpanyard** [MRCIEU/TwoSampleMR#148]
Hi, I downloaded TwoSampleMR yesterday and have run into the following issue: sometimes when I run extract_outcome_data(), I get the error message "Error in fromJSON_safe(url) : could not find function "fromJSON_safe" ", and the code fails.

I am using TwoSampleMR version 0.5.0. I am trying to look up GWAS ID ieu-a-1183 using a collection of 4937 SNPs. The full message output is the following:

`output <- extract_outcome_data( snps = my_snps, outcomes = mrcieu_gwas_id )`

> Extracting data for 4937 SNP(s) from 1 GWAS(s)
> Finding proxies for 775 SNPs in outcome ieu-a-1183
> Extracting data for 775 SNP(s) from 1 GWAS(s)
> 1 of 1 outcomes
>  [>] 1 of 2 chunks
> Error in fromJSON_safe(url) : could not find function "fromJSON_safe"

For now I'll try using the previous version of TwoSampleMR to see if that works OK. Thanks for your help!

**Comment by explodecomputer** [comment]
Ah thanks so much for letting me know about this, something hanging over from the previous version. I committed a fix just now so if you try reinstalling it should work

**Comment by dpanyard** [comment]
It seems to be working now. That was the fastest turnaround I've seen on an issue! Thanks!
