### ISSUE TITLE
TwoSampleMR 0.5.0 About Clumping 

### ISSUE THREAD

**Issue by whve** [MRCIEU/TwoSampleMR#150]
Hi, The `clump_data` on multiple `exposure` looks like it can only handle one of them. Its replacement `ieugwasr :: ld_clump ()` cannot be processed either.

**Comment by explodecomputer** [comment]
Thank you very much for pointing this out. The ieugwasr package had an issue which has now been updated. If you update that package to 0.1.1 then things should work properly

```
devtools::install_github("MRCIEU/ieugwasr")
```
