### ISSUE TITLE
 could not find function "clump_data" 

### ISSUE THREAD

**Issue by gs115** [MRCIEU/TwoSampleMR#153]
I am getting error message consistently

Error in clump_data(vta, clump_r2 = 0.05) :    could not find function "clump_data"

I tried several things that used to work before, but nothing worked 
--

**Comment by explodecomputer** [comment]
i'm not seeing this problem, have you updated recently?

```
devtools::install_github("mrcieu/twosamplemr")
```

**Comment by gs115** [comment]
Thank you very much. I reinstalled twosamplemr and it worked!

Thanks again,
Ghada
