### ISSUE TITLE
Error in density.default when running mr()

### ISSUE THREAD

**Issue by Annapanca** [MRCIEU/TwoSampleMR#154]
Hi, 

I have been using the package for a while now, but this is the first time I encounter an error when trying to run mr() on my harmonized data. 

The exact error I got is:

Analysing 'sj24vX' on 'OY8jkN'
Error in density.default(BetaIV.in, weights = weights, bw = h) : 
  non-finite 'bw'

I was trying to find what `h` is for the bandwidth in your code on here,
[myharmoniseddata.txt](https://github.com/MRCIEU/TwoSampleMR/files/4149391/myharmoniseddata.txt)

 but I couldn`t find it unfortunately.
I attached the harmonized data. 

Many thanks,
Anna

**Comment by explodecomputer** [comment]
I think sometimes the mr mode method fails to converge. You can omit it by using 

```
mr(dat, method_list=c(mr_ivw, ... etc))
```

the method list can be seen from `mr_method_list()`

**Comment by udube** [comment]
I'm having this same issue. The specific modes where this fails are mr_simple_mode, mr_weighted_mode.
