### ISSUE TITLE
How to calculate the F statistic？

### ISSUE THREAD

**Issue by cynthia1227** [MRCIEU/TwoSampleMR#157]
Hi, I want to calculate the "F statistic", but I did not find the command in the package "TwoSample MR". I noticed that many papers using this package reported the parameter,  and how can I get it? Thank you!

**Comment by explodecomputer** [comment]
For each of the instruments, if you have the SNP-exposure data then

```
qf(pval, df1=1, df2=samplesize-1, lower.tail=FALSE)
```
