### ISSUE TITLE
question on LD calculation

### ISSUE THREAD

**Issue by statgen33** [MRCIEU/TwoSampleMR#17]
Thank you for presenting this very nice program for MR analysis. I found that in the recent few days the program fail to compute LD matrix for variants (even after trying for a few times), for example when doing analysis on correlated genetic variants. This appears to occur after a recent update of the API. 

dat_to_MRInput(dat, get_correlations = TRUE)
Error in ld_matrix(unique(dat$SNP)) : 
  None of the requested SNPs were found

May I know if this problem will be corrected? Thank you very much indeed.

**Comment by explodecomputer** [comment]
Hi thanks for letting me know about this. Some files were not available on the server, these are restored now and it should work again.

**Comment by statgen33** [comment]
Thank you very much for the prompt response. I have updated my version of TwoSampleMR and retried the above command, however I am still getting the same error: 

dat_to_MRInput(dat, get_correlations = TRUE)
Error in ld_matrix(unique(dat$SNP)) :
None of the requested SNPs were found

Sorry for bothering  but would you mind looking into the issue again? Thank you very much in advance for your help.

**Comment by explodecomputer** [comment]
My apologies, I thought this change had been propagated to the server but it had not, it should be working now. Thanks for your patience.
