### ISSUE TITLE
clump_data remove all SNP

### ISSUE THREAD

**Issue by WeiCSong** [MRCIEU/TwoSampleMR#173]
Hi TSMR developer,
     Thank you for the great tools. I was analyzing GWAS of  [Alzheimer](https://ctg.cncr.nl/software/summary_statistics)  and found that all chosen snps were removed by clump_data. By manual insepection i think this does not make sense, because these snps can be found in 1000G database. For example, rs4575098 has MAF~0.2 in 1000G, according to the description of clump_data, at least one of its LD partners should be retained. Could you help me about that? Thank you very much!

My data:
`>head(exposure)
SNP beta.exposure se.exposure pos.exposure other_allele.exposure
1  rs4575098    0.01641163 0.002576595    161155392                     G
2 rs11585858    0.01604387 0.002580382    161156033                     C
3  rs6690215    0.01183991 0.002171020    207656050                     T
4  rs4844600    0.02140083 0.002772637    207679307                     G
5 rs12037841    0.01928490 0.003036707    207684192                     G
6  rs4266886    0.02230881 0.002770698    207685786                     C
  pval.exposure effect_allele.exposure samplesize.exposure chr.exposure
1  1.896396e-10                      A           161155392            1
2  5.047090e-10                      A           161156033            1
3  4.935515e-08                      C           207656050            1
4  1.176308e-14                      A           207679307            1
5  2.144842e-10                      T           207684192            1
6  8.165758e-16                      T           207685786            1
  exposure mr_keep.exposure pval_origin.exposure id.exposure eaf.exposure
1 exposure             TRUE             reported      WMJXyM           NA
2 exposure             TRUE             reported      WMJXyM           NA
3 exposure             TRUE             reported      WMJXyM           NA
4 exposure             TRUE             reported      WMJXyM           NA
5 exposure             TRUE             reported      WMJXyM           NA
6 exposure             TRUE             reported      WMJXyM           NA
`

my code:
`exposure=clump_data(exposure)`

**Comment by WeiCSong** [comment]
PS, i tried using local binary files like
`exposure=ieugwasr::ld_clump(exposure,plink_bin=data_maf0.01_rs_ref)`
and the issue still remained.

**Comment by explodecomputer** [comment]
Thanks for letting me know. I'm not sure why you experienced this issue, but this morning I believe the server was down for some reason. It seems to be up again now. I just tried this, taking the first 6 SNPs from your example:

```
> library(dplyr)
> library(TwoSampleMR)
> d <- tibble(SNP=c("rs4575098", "rs11585858", "rs6690215", "rs4844600", "rs12037841", "rs4266886"), pval.exposure = c(1.896396e-10,5.047090e-10,4.935515e-08,1.176308e-14,2.144842e-10,8.165758e-16))
> a <- clump_data(d)
Warning: since v0.4.2 the default r2 value for clumping has changed from 0.01 to 0.001
API: public: http://gwas-api.mrcieu.ac.uk/
Clumping pOWpQ3, 6 variants
Removing 4 of 6 variants due to LD with other variants or absence from LD reference panel
> a
# A tibble: 2 x 3
  SNP       pval.exposure id.exposure
  <chr>             <dbl> <chr>
1 rs4575098      1.90e-10 pOWpQ3
2 rs4266886      8.17e-16 pOWpQ3
```

**Comment by WeiCSong** [comment]
> Thanks for letting me know. I'm not sure why you experienced this issue, but this morning I believe the server was down for some reason. It seems to be up again now. I just tried this, taking the first 6 SNPs from your example:
> 
> ```
> > library(dplyr)
> > library(TwoSampleMR)
> > d <- tibble(SNP=c("rs4575098", "rs11585858", "rs6690215", "rs4844600", "rs12037841", "rs4266886"), pval.exposure = c(1.896396e-10,5.047090e-10,4.935515e-08,1.176308e-14,2.144842e-10,8.165758e-16))
> > a <- clump_data(d)
> Warning: since v0.4.2 the default r2 value for clumping has changed from 0.01 to 0.001
> API: public: http://gwas-api.mrcieu.ac.uk/
> Clumping pOWpQ3, 6 variants
> Removing 4 of 6 variants due to LD with other variants or absence from LD reference panel
> > a
> # A tibble: 2 x 3
>   SNP       pval.exposure id.exposure
>   <chr>             <dbl> <chr>
> 1 rs4575098      1.90e-10 pOWpQ3
> 2 rs4266886      8.17e-16 pOWpQ3
> ```

Thank you for your help, i'll try that again.

**Comment by eriftips** [comment]
Hi, I'm having the same issue today with TSMR clump commands that were working yesterday:
`Warning: since v0.4.2 the default r2 value for clumping has changed from 0.01 to 0.001
Clumping fozkSs, 1868 variants, using EUR population reference
Removing 1868 of 1868 variants due to LD with other variants or absence from LD reference panel`

I'm using v0.5.4. Is there any maintenance in the server today? 
Thank you very much and sorry for the inconveniences.

Sergi

**Comment by explodecomputer** [comment]
Apologies this has been temporarily disabled because someone was hammering the server with LD operations. We'll reinstate it as soon as possible

**Comment by eriftips** [comment]
> 
> 
> Apologies this has been temporarily disabled because someone was hammering the server with LD operations. We'll reinstate it as soon as possible

Thank you so much.
Sergi

**Comment by Aioa19** [comment]
> Apologies this has been temporarily disabled because someone was hammering the server with LD operations. We'll reinstate it as soon as possible

Is it still disabled? cause I'm experiencing the same issue today.

Thanks

**Comment by ZoheirAlayash** [comment]
Same problem! any updates concerning the server ?

**Comment by explodecomputer** [comment]
Sorry for the issues, working on it - just need to protect other services on the same server so it's a slightly non-trivial task. But hopefully back soon. 

btw it's possible to run LD clumping and LD matrix operations locally, have a look here for info, we tried to make it as straightforward as possible: https://mrcieu.github.io/ieugwasr/articles/local_ld.html

**Comment by ZoheirAlayash** [comment]
I ran this:
ld_clump(
  dplyr::tibble(variant=exposure_gwas1_8_1$rsid , pval=exposure_gwas1_8_1$pval, id=exposure_gwas1_8_1$trait_id),
  plink_bin = genetics.binaRies::get_plink_binary(),
  bfile = "~/Desktop/1kg.v3/EUR.bed")

And I got this error: 
Error in ld_clump(dplyr::tibble(variant = exposure_gwas1_8_1$rsid, pval = exposure_gwas1_8_1$pval,  : 
  "rsid" %in% names(dat) is not TRUE

Thank you in advance.

**Comment by explodecomputer** [comment]
oops sorry can you change `variant=exposure_gwas...` to `rsid=exposure_gwas...`

**Comment by ZoheirAlayash** [comment]
It worked, thank you :)

**Comment by explodecomputer** [comment]
ld operations back up now

**Comment by Xuemin-Wang** [comment]
Hi there, 

I've been encountering the same issue with TwoSampleMR version 0.5.5 since yesterday. I've also tested the the above example with 6 variants, but all were removed. 
> d <- tibble(SNP=c("rs4575098", "rs11585858", "rs6690215", "rs4844600", "rs12037841", "rs4266886"), pval.exposure = c(1.896396e-10,5.047090e-10,4.935515e-08,1.176308e-14,2.144842e-10,8.16> dim(d)))
> a <- clump_data(d)
Please look at vignettes for options on running this locally if you need to run many instances of this command.
Clumping OOqJPW, 6 variants, using EUR population reference
Removing 6 of 6 variants due to LD with other variants or absence from LD reference panel.

Was this due to the interruption of the server again?

Regards,
patrick

**Comment by Haojie818** [comment]
any updated? I also faced this problem now. 
"Removing 12 of 12 variants due to LD with other variants or absence from LD reference panel."

**Comment by Haojie818** [comment]
and another thing strange is that when I use subset of the expdata, for example 8 out of 12 snp, then the clump_data will return some result.
![image](https://user-images.githubusercontent.com/81631681/170841708-ba23d787-1b56-4153-8910-1e6001aaf789.png)

**Comment by Haojie818** [comment]
Hi, all.
I think the reason is caused by 1 of my snp has p value of 0. TwoSampleMR will give the SNP NA as P, then the problem happened.
when I remove this specific SNP, cuump_data returned correct result.

**Comment by llalluan** [comment]
> 
Hi,
I am experiencing the same issue when running the clump_data function without any SNP with P value of 0.

**Comment by fabianacz** [comment]
I am trying to perform clumping using the 1000 genomes as reference dataset.
I been experiencing the following error 


To get the same LD reference dataset that is used by the API, you can download it directly from here: http://fileserve.mrcieu.ac.uk/ld/1kg.v3.tgz

To get a path to plink you can do the following:

devtools::install_github("explodecomputer/genetics.binaRies")
plink <- genetics.binaRies::get_plink_binary()

* Using plink **

orru_clump <- ld_clump(
  dplyr::tibble(rsid = summaryset_orru$rsid, pval = summaryset_orru$p, id = summaryset_orru$id),
  plink_bin = "plink",
  bfile = "1kg.v3" # This is the same directory as my R project

)

Clumping ebi-a-GCST90001942, 15141982 variants, using EUR population reference PLINK v1.90b7 64-bit (16 Jan 2023) [www.cog-genomics.org/plink/1.9/](http://www.cog-genomics.org/plink/1.9/) (C) 2005-2023 Shaun Purcell, Christopher Chang GNU General Public License v3 Logging to C:\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file3930d7a4440.log. Options in effect: --bfile 1kg.v3 --clump C:\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file3930d7a4440 --clump-kb 10000 --clump-p1 0.99 --clump-r2 0.001 --out C:\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file3930d7a4440 65210 MB RAM detected; reserving 32605 MB for main workspace. Error: Failed to open 1kg.v3.bed. Error in file(file, "rt") : cannot open the connection In addition: Warning message: In file(file, "rt") : cannot open file 'C:\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file3930d7a4440.clumped': No such file or directory


** Using plink2 **

plink2 <- "C:/Users/corsfmdg/Desktop/R/R_ME" # I have put plink.exe in the same directory as my R project

orru_clump <- ld_clump(
  dplyr::tibble(rsid=summaryset_orru$rsid, pval=summaryset_orru$p, id=summaryset_orru$id),
  plink_bin = "plink2",
  bfile = "1kg.v3"
)
 
Clumping ebi-a-GCST90001942, 15141982 variants, using EUR population reference Error in file(file, "rt") : cannot open the connection In addition: Warning message: In file(file, "rt") : cannot open file 'C:\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file39303fa538bf.clumped': No such file or directory

any suggestions how to sort that?

**Comment by huahuaa-lab** [comment]
> 我正在尝试使用 1000 个基因组作为参考数据集进行聚集。我遇到了以下错误
> 
> 要获取 API 使用的相同 LD 参考数据集，您可以直接从此处下载：http://fileserve.mrcieu.ac.uk/ld/1kg.v3.tgz
> 
> 若要获取 plink 的路径，可以执行以下操作：
> 
> devtools：：install_github（“explodecomputer/genetics.binaRies”） plink <- genetics.binaRies：：get_plink_binary（）
> 
> * 使用 plink **
> 
> orru_clump <- ld_clump（ dplyr：：tibble（rsid = summaryset_orru$rsid， pval = summaryset_orru$p， id = summaryset_orru$id）， plink_bin = “plink”， bfile = “1kg.v3” # 这是与我的 R 项目相同的目录
> 
> )
> 
> 15141982 GCST90001942使用 EUR 人口参考 PLINK v1.90b7 64 位 （2023年1月16日） [www.cog-genomics.org/plink/1.9/](http://www.cog-genomics.org/plink/1.9/) （C） 2005-2023 Shaun Purcell， Christopher Chang GNU 通用公共许可证 v3 日志记录到 C：\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file3930d7a4440.log。有效的选项： --bfile 1kg.v3 --clump C：\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file3930d7a4440 --clump-kb 10000 --clump-p1 0.99 --clump-r2 0.001 --out C：\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file3930d7a4440 检测到 65210 MB RAM;为主工作区保留 32605 MB。错误：无法打开 1kg.v3.bed。file（file， “rt”） 中的错误：无法打开连接 此外： 警告消息：在 file（file， “rt”） 中：无法打开文件“C：\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file3930d7a4440.clumped”：没有这样的文件或目录
> 
> ** 使用 plink2 **
> 
> plink2 <- “C：/Users/corsfmdg/Desktop/R/R_ME” # 我把 plink.exe 放在和我的 R 项目相同的目录中
> 
> orru_clump <- ld_clump（ dplyr：：tibble（rsid=summaryset_orru$rsid， pval=summaryset_orru$p， id=summaryset_orru$id）， plink_bin = “plink2”， bfile = “1kg.v3” )
> 
> 使用 EUR 总体参考的 ebi-a-GCST90001942,15141982变体 file（file， “rt”） 中的错误：无法打开连接 此外： 警告消息：在 file（file， “rt”） 中：无法打开文件“C：\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file39303fa538bf.clumped”：没有这样的文件或目录
> 
> 有什么建议如何排序吗？


Has your problem been solved? I had the same problem

**Comment by An-Orange** [comment]
> Hi, I'm having the same issue today with TSMR clump commands that were working yesterday: `Warning: since v0.4.2 the default r2 value for clumping has changed from 0.01 to 0.001 Clumping fozkSs, 1868 variants, using EUR population reference Removing 1868 of 1868 variants due to LD with other variants or absence from LD reference panel`
> 
> I'm using v0.5.4. Is there any maintenance in the server today? Thank you very much and sorry for the inconveniences.
> 
> Sergi

Have you solved this problem? I have also encountered the same problem, do you know how to solve this problem, please reply me, thank you very much

**Comment by rendaths** [comment]
Hi, I'm having the same issue. In the last three days, I tried to perform a clumping for some SNPs, and all SNPs were removed. I tried with different SNPs datasets and I got the same error. I checked and every SNP are included in 1000G database.
I'm using TwoSampleMR version 0.6.8. the command I'm running is

**Comment by Nice32** [comment]
Hi, I'm also having the same issue about all the snps are removed. I wonder if **clump_data** function  down again, and when will this issue be fixed? Or is there another way to analyze it?
