### ISSUE TITLE
clump_data stops once it gets to an exposure with 1 SNP

### ISSUE THREAD

**Issue by bethleegy** [MRCIEU/TwoSampleMR#175]
Hello,

With the new version of the clump_data (hasn't run into this particular issue with the older version of TwoSampleMR), it seems that clumping stops the iteration once it reaches an exposure with only 1 SNP instead of keep going through the loop. 

The code stops at: 
Only one SNP for 026mCx

and the output then is a dataframe with only one row. 

Please let me know if there's anything I can do to get around this! I tried running clump_data on the older version, and it gives me 

Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML PUBLIC "-//W3C//
                     (right here) ------^

which may be an issue with the server, perhaps? 

Thank you in advance.

**Comment by explodecomputer** [comment]
Thanks for this @bethleegy i have fixed the issue now. Please update using:

```
devtools::install_github("mrcieu/twosamplemr")
```

it should update the ieugwasr package to version 0.1.4, if it doesn't then reinstall that manually using


```
devtools::install_github("mrcieu/ieugwasr")
```

**Comment by bethleegy** [comment]
Hi there,

I seem to be running into the same issue again. I'm clumping a file with multiple exposures but it stops once it reaches an exposure with only one SNP. The message that appears before stopping the iteration is "Only one SNP for (ID)." 

Please let me know if this can be fixed soon! Tried running on different versions again this time to no avail. Thanks in advance.
