### ISSUE TITLE
Problem with installing in RStudio on Mac

### ISSUE THREAD

**Issue by WeiD95** [MRCIEU/TwoSampleMR#178]
Hi,
 
I've been having some trouble installing the latest version of TwoSampleMR on Rstudio for my Macbook. The legacy version runs fine and devtools is also installed. 

This is what appears on the console:

`> devtools::install_github("MRCIEU/TwoSampleMR")
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo MRCIEU/TwoSampleMR@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                                             
2: CRAN packages only                              
3: None                                            
4: ieugwasr (483381f4e... -> 1b8ea29f1...) [GitHub]

Enter one or more numbers, or an empty line to skip updates:
1
ieugwasr   (483381f4e... -> 1b8ea29f1...) [GitHub]
robustbase (NA           -> 0.93-6      ) [CRAN]
Installing 1 packages: robustbase
Error: Failed to install 'TwoSampleMR' from GitHub:
  (converted from warning) unable to access index for repository https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6:
  cannot open URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/PACKAGES'
> `

Don't think I've seen this error being mentioned yet. Would really appreciate it if someone can help.

Many thanks

**Comment by explodecomputer** [comment]
hey i've not seen this error before. can you have a look here - perhaps it helps?

https://community.rstudio.com/t/install-packages-unable-to-access-index-for-repository-try-disabling-secure-download-method-for-http/16578

https://community.rstudio.com/t/unable-to-access-index-for-repository-https-cran-rstudio-com-src-contrib/31729

**Comment by WeiD95** [comment]
Thank you for the response! 

I've tried both links. The first one did not help and gave me the same error. 
I then changed the CRANmirror as instructed and this has given me a new error:

`> devtools::install_github("MRCIEU/TwoSampleMR")
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo MRCIEU/TwoSampleMR@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                                             
2: CRAN packages only                              
3: None                                            
4: ieugwasr (483381f4e... -> 1b8ea29f1...) [GitHub]

Enter one or more numbers, or an empty line to skip updates:
1
ieugwasr   (483381f4e... -> 1b8ea29f1...) [GitHub]
robustbase (NA           -> 0.93-6      ) [CRAN]
Installing 1 packages: robustbase

  There is a binary version available but the source version is later:
           binary source needs_compilation
robustbase 0.93-5 0.93-6              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) yes
installing the source package ‘robustbase’

trying URL 'https://www.stats.bris.ac.uk/R/src/contrib/robustbase_0.93-6.tar.gz'
Content type 'application/x-gzip' length 2956184 bytes (2.8 MB)
==================================================
downloaded 2.8 MB

* installing *source* package ‘robustbase’ ...
** package ‘robustbase’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -c R-rng4ftn.c -o R-rng4ftn.o
gfortran  -fPIC  -Wall -g -O2  -c eigen.f -o eigen.o
make: gfortran: No such file or directory
make: *** [eigen.o] Error 1
ERROR: compilation failed for package ‘robustbase’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/robustbase’
Error: Failed to install 'TwoSampleMR' from GitHub:
  (converted from warning) installation of package ‘robustbase’ had non-zero exit status
`

**Comment by WeiD95** [comment]
I may have found a solution. It appears the issue seems to be solved. When the console asks for:

"Do you want to install from sources the package which needs compilation? (Yes/no/cancel) "

Choosing no, will allow the install to go through

**Comment by explodecomputer** [comment]
great, glad it worked thanks for letting me know

**Comment by remlapmot** [comment]
If source packages are not compiling for you on Mac I think you need to install Command Line tools. See [here](https://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/) for more info; but the TL;DR is open the Terminal app and issue:
```
xcode-select --install
```
