### ISSUE TITLE
Timed out

### ISSUE THREAD

**Issue by lgl15** [MRCIEU/TwoSampleMR#179]
Dear developers,
I wonder if there is a way to extent the query times of function api_query(). For example, when I do:

extract_instruments(          outcomes = gwas.id, 
                                           force_server = TRUE,
                                           p1 = p.value.threshold, 
                                           r2 = clumpling.ld.threshold,
                                           clump = TRUE) 

if the  p.value.threshold is higher than 5x10-3 the query times out with the following error:

**Error in api_query("tophits", query = list(id = id, pval = pval, preclumped = preclumped,  : 
  The query to MR-Base exceeded 300 seconds and timed out. Please simplify the query**

Can I extend the time limit of 300 seconds? I understand the query grows in size when I relax the p.value.threshold. 

Many thanks for developing this package!,
--
Luis

**Comment by explodecomputer** [comment]
Thanks for the message Luis.
We struggle with this a bit because if we allow very expensive computation on our servers it can make the whole server difficult to use. I think for this particular case can you try:

1. Extracting without clumping
2. Performing clumping on each chromosome separately

Alternatively, you could try downloading the VCF from https://gwas.mrcieu.ac.uk/ and using the [gwasvcf](https://mrcieu.github.io/gwasvcf/index.html) to extract based on p-value, and use the [ieugwasr](https://mrcieu.github.io/ieugwasr/articles/guide.html#ld-clumping) package to do clumping locally. We're trying to get to a point where it's easy to do heavier computation on these data locally. 

LD reference files listed in the gwasvcf page

**Comment by fabianacz** [comment]
I am trying to perform clumping using the 1000 genomes as reference dataset.
I been experiencing the following error

To get the same LD reference dataset that is used by the API, you can download it directly from here: http://fileserve.mrcieu.ac.uk/ld/1kg.v3.tgz

To get a path to plink you can do the following:

devtools::install_github("explodecomputer/genetics.binaRies")
plink <- genetics.binaRies::get_plink_binary()

Using plink **
orru_clump <- ld_clump(
dplyr::tibble(rsid = summaryset_orru$rsid, pval = summaryset_orru$p, id = summaryset_orru$id),
plink_bin = "plink",
bfile = "1kg.v3" # This is the same directory as my R project

)

Clumping ebi-a-GCST90001942, 15141982 variants, using EUR population reference PLINK v1.90b7 64-bit (16 Jan 2023) [www.cog-genomics.org/plink/1.9/](http://www.cog-genomics.org/plink/1.9/) (C) 2005-2023 Shaun Purcell, Christopher Chang GNU General Public License v3 Logging to C:\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file3930d7a4440.log. Options in effect: --bfile 1kg.v3 --clump C:\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file3930d7a4440 --clump-kb 10000 --clump-p1 0.99 --clump-r2 0.001 --out C:\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file3930d7a4440 65210 MB RAM detected; reserving 32605 MB for main workspace. Error: Failed to open 1kg.v3.bed. Error in file(file, "rt") : cannot open the connection In addition: Warning message: In file(file, "rt") : cannot open file 'C:\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file3930d7a4440.clumped': No such file or directory

** Using plink2 **

plink2 <- "C:/Users/corsfmdg/Desktop/R/R_ME" # I have put plink.exe in the same directory as my R project

orru_clump <- ld_clump(
dplyr::tibble(rsid=summaryset_orru$rsid, pval=summaryset_orru$p, id=summaryset_orru$id),
plink_bin = "plink2",
bfile = "1kg.v3"
)

Clumping ebi-a-GCST90001942, 15141982 variants, using EUR population reference Error in file(file, "rt") : cannot open the connection In addition: Warning message: In file(file, "rt") : cannot open file 'C:\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file39303fa538bf.clumped': No such file or directory

any suggestions how to sort that?

**Comment by KLKreft** [comment]
> I am trying to perform clumping using the 1000 genomes as reference dataset. I been experiencing the following error
> 
> To get the same LD reference dataset that is used by the API, you can download it directly from here: http://fileserve.mrcieu.ac.uk/ld/1kg.v3.tgz
> 
> To get a path to plink you can do the following:
> 
> devtools::install_github("explodecomputer/genetics.binaRies") plink <- genetics.binaRies::get_plink_binary()
> 
> Using plink ** orru_clump <- ld_clump( dplyr::tibble(rsid = summaryset_orru$rsid, pval = summaryset_orru$p, id = summaryset_orru$id), plink_bin = "plink", bfile = "1kg.v3" # This is the same directory as my R project
> 
> )
> 
> Clumping ebi-a-GCST90001942, 15141982 variants, using EUR population reference PLINK v1.90b7 64-bit (16 Jan 2023) [www.cog-genomics.org/plink/1.9/](http://www.cog-genomics.org/plink/1.9/) (C) 2005-2023 Shaun Purcell, Christopher Chang GNU General Public License v3 Logging to C:\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file3930d7a4440.log. Options in effect: --bfile 1kg.v3 --clump C:\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file3930d7a4440 --clump-kb 10000 --clump-p1 0.99 --clump-r2 0.001 --out C:\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file3930d7a4440 65210 MB RAM detected; reserving 32605 MB for main workspace. Error: Failed to open 1kg.v3.bed. Error in file(file, "rt") : cannot open the connection In addition: Warning message: In file(file, "rt") : cannot open file 'C:\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file3930d7a4440.clumped': No such file or directory
> 
> ** Using plink2 **
> 
> plink2 <- "C:/Users/corsfmdg/Desktop/R/R_ME" # I have put plink.exe in the same directory as my R project
> 
> orru_clump <- ld_clump( dplyr::tibble(rsid=summaryset_orru$rsid, pval=summaryset_orru$p, id=summaryset_orru$id), plink_bin = "plink2", bfile = "1kg.v3" )
> 
> Clumping ebi-a-GCST90001942, 15141982 variants, using EUR population reference Error in file(file, "rt") : cannot open the connection In addition: Warning message: In file(file, "rt") : cannot open file 'C:\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file39303fa538bf.clumped': No such file or directory
> 
> any suggestions how to sort that?

Hi, 
You should extract the 1kg.v3 file first, and then use the path to the EUR bed file 
Bw, Karim
