### ISSUE TITLE
Isuue with "extract_outcome data"

### ISSUE THREAD

**Issue by MichelNivard** [MRCIEU/TwoSampleMR#18]
I encounter the following error when extracting outcome data:
```
outcome_dat <- extract_outcome_data(snps=dep3$SNP,outcomes = 838:960)

Extracting data for 37 SNP(s) from 123 GWAS(s)
1 of 37 snps
 [>] 1 of 1 chunks
Token cache file: mrbase.oauth
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML PUBLIC "-//W3C//
                     (right here) ------^
```

Any ideas?

**Comment by explodecomputer** [comment]
Hi Michel, Thanks for letting me know about this. We've been having a lot of server issues and are working on moving over to a new database architecture, I'll let you know when this happens, hopefully very soon.

**Comment by explodecomputer** [comment]
We have just moved over to the new database and hopefully it gives much more reliable performance going forward. Do let us know if you experience any other issues

**Comment by ayuellen** [comment]
I have also encountered the same problem when using extract_outcome_data:

```
out_dat <- extract_outcome_data(snps = exp_dat$SNP, outcomes = 1:nrow(ao))

Extracting data for 4 SNP(s) from 1691 GWAS(s)
Token cache file: mrbase.oauth
......
Finding proxies for 4 SNPs in outcome 33
Extracting data for 4 SNP(s) from 1 GWAS(s)
Error: lexical error: invalid char in json text.
                               <!DOCTYPE HTML PUBLIC "-//W3C//
             (right here) ------^
```

How to tackle it? Thanks.

**Comment by mightyphil2000** [comment]
Howzit

Instead of outcomes = 1:nrow(ao) try
outcomes = ao$id

Row number is not always the same as ID.

If still not working, and in a hurry, a work around would be to divide the extraction into a few steps, ie don't extract all outcomes in one go but try 100 at a time.

Philip Haycock, PhD
MR-Base: www.mrbase.org
CRUK Population Research Fellow
MRC Integrative Epidemiology Unit
University of Bristol
Oakfield House, Oakfield Grove
Bristol, BS8 2BN, UK
T +44 (0)117 3310088
________________________________

**Comment by ayuellen** [comment]
Thank you very much for your prompt reply. 
I would like to extract outcome data for around 100 exposures. The suggested code did work for the first few exposures, but the same error appeared later on. When I tried to perform the extraction again (even using 1 SNP with several outcomes), I got the following error:

```
Extracting data for 1 SNP(s) from 7 GWAS(s)
Error: Service Unavailable
```
Your prompt reply will be highly appreciated. Thanks a lot.

**Comment by mightyphil2000** [comment]
We've been having some server problems recently. Do you still get the same error?

________________________________

**Comment by ayuellen** [comment]
I got another error:
```
 Error in function (type, msg, asError = TRUE)  : 
  Failed to connect to api.mrbase.org port 80: Timed out 
```

**Comment by zqcrystal325** [comment]
Hi, I successfully installed the package, however I encounter this problem while running the code ao <- available_outcomes(), and I got the following error:
Token cache file: mrbase.oauth
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML PUBLIC "-//IETF/
                     (right here) ------^

Is there any solution? I appreciate any response.

**Comment by explodecomputer** [comment]
Sorry we are currently having server issues, I'll let you know when it's back online
