### ISSUE TITLE
Installation of Two Sample MR package

### ISSUE THREAD

**Issue by Mercy-Kimani** [MRCIEU/TwoSampleMR#180]
Why am I getting this error? And what can I do to fix it?
Error: Failed to install 'TwoSampleMR' from GitHub:
  Failed to install 'ieugwasr' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘rlang’

**Comment by remlapmot** [comment]
The first thing to try for this is close R/RStudio and then reopen it and retry the install.
