### ISSUE TITLE
MR Steiger / get_r_from_lor

### ISSUE THREAD

**Issue by daghli** [MRCIEU/TwoSampleMR#181]
Hello,

Thanks again for this terrific package. Was wondering, for the get_r_from_lor function, do the beta coefficients all have to be positive? And does allele frequency refer to effect allele frequency or minor allele frequency? Thank you!

Best,

I

**Comment by explodecomputer** [comment]
Hey I think it makes little difference whether positive/negative or effect allele freq or minor allele freq

```
> TwoSampleMR::get_r_from_lor(1, 0.2, 1000, 10000, 0.1)
[1] 0.2160363
> TwoSampleMR::get_r_from_lor(1, 0.8, 1000, 10000, 0.1)
[1] 0.2149304
> TwoSampleMR::get_r_from_lor(-1, 0.8, 1000, 10000, 0.1)
[1] 0.2160363
> TwoSampleMR::get_r_from_lor(1, 0.2, 1000, 10000, 0.1)
[1] 0.2160363
> TwoSampleMR::get_r_from_lor(-1, 0.2, 1000, 10000, 0.1)
[1] 0.2149304
> TwoSampleMR::get_r_from_lor(-0.1, 0.2, 1000, 10000, 0.1)
[1] 0.02204193
> TwoSampleMR::get_r_from_lor(-0.1, 0.8, 1000, 10000, 0.1)
[1] 0.02205395
```

**Comment by daghli** [comment]
How silly of me - I could have checked that so easily. Thank you.
