### ISSUE TITLE
TwoSampleMR available only for R-3.6.2?

### ISSUE THREAD

**Issue by ssier** [MRCIEU/TwoSampleMR#182]
I tried to install TwoSampleMR package without success. I use R-3.6.3 on my personal computer and I have access to two computing clusters that have either R-3.6.0 or R-3.6.1, and I always get the same error message:
install.packages("TwoSampleMR")
Warning in install.packages :
package ‘TwoSampleMR’ is not available (for R version 3.6.3)
Warning message:
package ‘TwoSampleMR’ is not available (for R version 3.6.1)
Warning message:
package 'TwoSampleMR' is not available (for R version 3.6.0) 

Is it true that TwoSampleMR package is available only for R-3.6.2? Or am I missing something/doing something wrong?
The problem is that apparently R-3.6.2 is not available for macOS anymore (at least I did not manage to find it from https://cran.r-project.org/bin/macosx/), so I am struggling to get the correct R version.
Thanks for help!

**Comment by mightyphil2000** [comment]
Hi

That message indicates that the package is not available on CRAN. You could try installing it from github instead.

If you have devtools already installed then type
install_github("MRCIEU/TwoSampleMR")

If not:


install.packages("devtools")
devtools::install_github("MRCIEU/TwoSampleMR")


bw

Philip

________________________________

**Comment by innache** [comment]
I have no success in installing the package with 3.6.2 R version and a few others. Which version of R does TwoSampleMR package work with?
<img width="458" alt="Screen Shot 2020-05-14 at 5 59 01 PM" src="https://user-images.githubusercontent.com/43591541/82000260-9c0b9480-960c-11ea-991f-099fd0545e88.png">

**Comment by remlapmot** [comment]
As Phil explained you get this error when you incorrectly try and install **TwoSampleMR** from CRAN. 

**TwoSampleMR** is not on CRAN, you install it from our GitHub repo. 

Please use the commands as Phil wrote for you :
```r
install.packages("devtools")
devtools::install_github("MRCIEU/TwoSampleMR")
```

* In the first line you install **devtools** from CRAN
* in the second you use **devtools** to install **TwoSampleMR** from GitHub)

**Comment by remlapmot** [comment]
Just to close this.

You can often see what version of R a package depends on by looking the `DESCRIPTION` file at the top level of the package repo.

You can see **TwoSampleMR** works on R 3.6.0 and above [here](https://github.com/MRCIEU/TwoSampleMR/blob/9960e8703466c330f96b17bcba7cb1117cc9adfb/DESCRIPTION#L25).
