### ISSUE TITLE
How to find proxy and solve forward strand ambiguous SNPs with local outcome data

### ISSUE THREAD

**Issue by ChongWu-Biostat** [MRCIEU/TwoSampleMR#185]
I found the TwoSampleMR is super helpful and makes two-sample MR super easy to implement. However, when I want to use the local outcome data, I found there is something I am unable to do. I have two questions:
1. How can we find proxy SNPs?
2. How can we solve forward strand ambiguous SNPs? Which function do I need to use?

Thank you for your help.

Thanks,
Chong

**Comment by explodecomputer** [comment]
Hey @ChongWu-Biostat 
I'm afraid proxy lookups aren't possible with local data. But if it was really necessary you could convert to VCF format and try to do it through this method: https://mrcieu.github.io/gwasvcf/

If you read in your local outcome data using `read_outcome_data` then you can use the `harmonse_data` function then it will align the exposure and outcome datasets, just the same as when using results from the database
Cheers
Gib
