### ISSUE TITLE
dat_to_MRInput unable to convert

### ISSUE THREAD

**Issue by kdack** [MRCIEU/TwoSampleMR#188]
Hello ,  
When I try to convert harmonise_data output to the format for MendelianRandomization using dat_to_MRInput, I get the following error:  
```
> SeMerged=dat_to_MRInput(SeMerged, get_correlation=TRUE)
Converting:
 - exposure: Se
 - outcome: outcome
 - obtaining LD matrix
Warning message:
'ld_matrix' is deprecated.
Use 'ieugwasr::ld_matrix()' instead.
See help("Deprecated") 
```  
Is there any way around this or other way to convert the data?

Thanks

**Comment by explodecomputer** [comment]
hey that's just a warning (not an error) so it should be doing fine. i was planning to change the ld_matrix function at some point so that's why the warning is there, but i guess it's confusing so i'll remove it
