### ISSUE TITLE
Clumping Removes SNPs which aren't in the LD reference panel

### ISSUE THREAD

**Issue by ParsaAkbari** [MRCIEU/TwoSampleMR#19]
If I have the following two snps rs71328596 and rs375573892
Calculating the LD matrix I get the following:
```
ld_matrix(c("rs71328596", "rs375573892"))
The following SNPs are not present in the LD reference panel
 rs71328596
 rs375573892

```
When these variants are clumped as part of a data frame of GWAS hits they are both removed with the following message:
```
Removing the following SNPs due to LD with other SNPs:
rs71328596
rs375573892
```

In my list of SNPs given for clumping rs71328596 is the only SNP on chromosome 21.

**Comment by explodecomputer** [comment]
Thanks for the message. The LD reference panel that we are using at the moment is quite a heavily filtered set SNPs - MAF > 0.01 in Europeans and no indels. rs71328596 is an INDEL and rs375573892 appears to be quite rare, hence they are not present in the reference dataset. 

By default anything that isn't present in the reference panel, which is then used in an operation that requires the reference panel, is being removed. We can change this behaviour if there is a good reason to - but it might just be easier to add those SNPs back in after you have performed clumping, should you know that they don't pose a problem with LD etc.

**Comment by ParsaAkbari** [comment]
Hi, I do not propose changing the behaviour of the function only changing the output text which is currently misleading:

> Removing the following SNPs due to LD with other SNPs:
> rs71328596
> rs375573892

Not all SNPs in this list are removed due to LD with other SNPs (as indicated by the text), SNPs may be removed due to the filtering as you described - such SNPs may not actually be in high LD with other SNPs.

**Comment by explodecomputer** [comment]
Thanks for the suggestion, changed the message now.
