### ISSUE TITLE
Steiger filtering function using z-scores

### ISSUE THREAD

**Issue by jorientr** [MRCIEU/TwoSampleMR#190]
Hi!

I have a question about the Steiger filtering function steiger_filtering(). For one of my analyses I have summary-level GWAS data that has as its unit unstandardized betas with SEs (to be more exact: volume measures in mm). If I read the R documentation on the Steiger function, it says that _'To estimate rsq for quantitative traits there must be either p-values and sample sizes for each SNP, or effect sizes and standard errors AND the units are in SD units (the column must contain "SD")'_.
Since the unit that I am working with is not SD, am I correct to think that I should provide the Steiger function with a dataset that only includes p-values and sample sizes, with the effect sizes taken out, and the unit column saying something like "mm"? Would that provide enough information to compute explained variance, and is that just as accurate as using a SD unit measure?

Thank you in advance!

**Comment by explodecomputer** [comment]
Hey @jorientr thanks for the question and sorry for the slow reply. The function should automatically detect that sample size and p-val are available and that the units are not in SD, and therefore use the appropriate method.
An alternative is to scale the effect and standard error to SD units if you know the standard deviation of the trait

```
dat$beta.exposure <- dat$beta.exposure / trait_sd
dat$se.exposure <- dat$se.exposure / trait_sd
```
