### ISSUE TITLE
cannot find "mr_rucker_cooksdistance" function

### ISSUE THREAD

**Issue by JYE-Lee** [MRCIEU/TwoSampleMR#191]
I am using the latest version of TwoSampleMR (0.5.4), but cannot find the function "mr_rucker_cooksdistance()".

> mr_rucker_cooksdistance(dat)
Error: could not find function "mr_rucker_cooksdistance"

Thanks for your help.

**Comment by remlapmot** [comment]
Hi thanks for the report.

We have forgotten to export that function.

For the time being please use the triple colon syntax to access this function as follows

``` r
TwoSampleMR:::mr_rucker_cooksdistance(dat)
```

**Comment by JYE-Lee** [comment]
Thanks, it worked.
I have one more question though. Where can I find the interpretation of the result?

From this function, I got the result as below.
"Factor(0)" means that there's no SNP to remove? 
And what does CD mean?
-----
$removed_snps
factor(0)
86 Levels: rs111448570 rs112063406 rs112759668 rs113771676 ... rs80245804

$selected
$selected$Method
[1] "Rucker (CD)"

$rucker
$rucker$Method
[1] " (CD)"
