### ISSUE TITLE
cannot use extract outcome data because of connection reset.. is there a server mainenance?

### ISSUE THREAD

**Issue by asadalian** [MRCIEU/TwoSampleMR#193]
Error in function (type, msg, asError = TRUE)  : 
  Recv failure: Connection was reset

I get this when I used the extract_outcome_data, which worked perfectly 5 minutes ago..
Could you please let me know why?

Many thanks!

**Comment by explodecomputer** [comment]
Hey sorry for the slow reply, it's possible that there was a server outage at that moment. Things have been generally fine over the past month but let me know if you have further issues
