### ISSUE TITLE
Nbclust

### ISSUE THREAD

**Issue by panosemma** [MRCIEU/TwoSampleMR#196]
Hi,
I run segmentation analysis in a sample with 75 rows successfully and now I try to run segmentation analysis in another larger sample(300 rows). however when I run the function
**NbClust(data=std_seg_data[,1:5], min.nc=3, max.nc=15, index="all", method="ward.D2")**
it appears the mesage
**_Error in std_seg_data[, 1:5] : subscript out of bounds_**
Any ideas what's wrong?
Thanks
Panos

**Comment by explodecomputer** [comment]
is it possible that this was posted to the wrong repository?
