### ISSUE TITLE
clump_data performs differently on .exposure and .outcome df

### ISSUE THREAD

**Issue by mvab** [MRCIEU/TwoSampleMR#197]
The `clump_data()` function gives very different sets of clumped instruments depending on whether you give it data in `.exposure` or `.outcome` format. In theory, the results should be identical as only column names differ. 

I'm aware that it only makes sense to be clumping exposure data, but the reason I encountered this issue is that when using external GWAS text file data I normally load and format it directly into the .outcome format to later use it in MVMR or 2-step MR, and also clump it along the way to get instruments at the same time. But the these clumped instruments are 80% different depending on whether you clump them as exposure or outcome. 

However, I think I know why this happens - in `clump_data()` it is assumed that the input will always be an `.exposure` df and it looks for a `pval.exposure` column, and if it is absent, a dummy `pval.exposure` column with 0.99 for all variants is created. Understandably, that produces quite different results. 
Therefore, my suggestion would be to check in `clump_data()` whether the supplied df is in `.exposure` or `.outcome` format and select the appropriate `pval.exposure` or `pval.outcome` column, and if neither are there, only then use the 0.99 replacement. 

This seems like a very easy mistake to make (i.e. assume that it's ok to clump `.outcome` df)  if you're just starting out at this - so this I believe the suggested check would be beneficial to help prevent incorrectly clumped SNPs in analyses. 📈 🤔 

p.s. happy to provide data/code to reproduce the problem

**Comment by explodecomputer** [comment]
many thanks for this, have updated and added credit to you in the NEWS.md file, hope that's ok
