### ISSUE TITLE
Error in ivw.res$coef["b_exp", "Estimate"] : subscript out of bounds 

### ISSUE THREAD

**Issue by Amanda2018genetics** [MRCIEU/TwoSampleMR#198]
Hi all,
When performing analysis using lapply, I got this error. Does anybody know this error:
Error in ivw.res$coef["b_exp", "Estimate"] : subscript out of bounds 
Best

**Comment by explodecomputer** [comment]
Are able to send some example code to repreoduce the problem? That would help trying to solve it

**Comment by Amanda2018genetics** [comment]
> Are able to send some example code to repreoduce the problem? That would help trying to solve it

Fixed, thanks

**Comment by mariyam-khan** [comment]
Hi all,
I have the same error:
Error in ivw.res$coef["b_exp", "Estimate"] : subscript out of bounds
Best

**Comment by 15987124360** [comment]
I have the same error as u
Error in ivw.res$coef["b_exp", "Estimate"] : subscript out of bounds
I'd appreciate it if you could tell me the solution! Thank you!!!
