### ISSUE TITLE
tutorial for in-house (local) data?

### ISSUE THREAD

**Issue by sariya** [MRCIEU/TwoSampleMR#199]
hello there,

Is there manual or tutorial to begin with GWAS, eQTL in-house or local data? 
I've data from population not from EUR or mentioned ones. Thus, I'd like customize scripts, calculate LD.

**Comment by explodecomputer** [comment]
Hey @sariya thanks for the message, I think there is a lot that could be related to this. There is a week-long short course here at Bristol that covers these sorts of topics https://www.bristol.ac.uk/medical-school/study/short-courses/2020-21-courses/genetic-epidemiology/ and many others - they might be able to make them available online if you contact them.
Good luck!

**Comment by sariya** [comment]
thanks.
