### ISSUE TITLE
Single SNP analysis is not performing

### ISSUE THREAD

**Issue by jahad** [MRCIEU/TwoSampleMR#2]
I'm getting this error every time I'm trying to do the single SNP analysis, I'm providing my exposure and outcome file using 49 SNPs

> res_single <- mr_singlesnp(dat)
Error in data.frame(SNP = c(as.character(x$SNP), nom), b = sapply(l, function(y) y$b),  : 
  arguments imply differing number of rows: 50, 0

Thanks

**Comment by explodecomputer** [comment]
Can you provide some data to reproduce the issue? Feel free to email it to me if it is sensitive (g.hemani@bristol.ac.uk)
