### ISSUE TITLE
Problem with install TwoSampleMR

### ISSUE THREAD

**Issue by zqzqcrystal325** [MRCIEU/TwoSampleMR#203]
Hello, I run the following codes, however error occured

library(devtools)
devtools::install_github("MRCIEU/TwoSampleMR")
Downloading GitHub repo MRCIEU/TwoSampleMR@master
MRCIEU-TwoSampleMR-59dc01a/docs/articles/perform_mr_files/figure-html/unnamed-chunk-20-1.png: truncated gzip input
tar.exe: Error exit delayed from previous errors.
错误: Failed to install 'unknown package' from GitHub:
Does not appear to be an R package (no DESCRIPTION)
此外: Warning messages:
1: In utils::untar(tarfile, ...) :
‘tar.exe -zxf "C:\Users\86133\AppData\Local\Temp\RtmpsV2HWN\file2d241841766d.tar.gz" -C "C:/Users/86133/AppData/Local/Temp/RtmpsV2HWN/remotes2d242f7544b6"’ returned error code 1
2: In system(cmd, intern = TRUE) :
运行命令'tar.exe -ztf "C:\Users\86133\AppData\Local\Temp\RtmpsV2HWN\file2d241841766d.tar.gz"'的状态是1

Then I tried isntalled with local zip file of TwoSampleMR package, it still won't work
devtools::install_local("TwoSampleMR-master.zip")

Error: Failed to install 'TwoSampleMR-master.zip' from local:
  Failed to install 'MRInstruments' from GitHub:
  Does not appear to be an R package (no DESCRIPTION)
In addition: Warning messages:
1: In utils::untar(tarfile, ...) :
  ‘tar.exe -xf "C:\Users\zqzqc\AppData\Local\Temp\RtmpAnwdfP\file43b0148d6df4.tar.gz" -C "C:/Users/zqzqc/AppData/Local/Temp/RtmpAnwdfP/remotes43b0f8b1777"’ returned error code 1
2: In system(cmd, intern = TRUE) :
  running command 'tar.exe -tf "C:\Users\zqzqc\AppData\Local\Temp\RtmpAnwdfP\file43b0148d6df4.tar.gz"' had status 1

it bothers me a lot, I tried to work this out the whole day, any help would be appreciated!

**Comment by zqzqcrystal325** [comment]
Problem solved!

**Comment by Kingsman-Key** [comment]
excuse me, how did you solve that?

**Comment by Koalalive** [comment]
excuse me, how did you solve that? I met similar problem. Thanks!

**Comment by remlapmot** [comment]
Firstly please try the standard installation

```r
install.packages("remotes")
remotes::install_github("MRCIEU/TwoSampleMR")
```

If that fails for some reason on your computer then download the latest `.tar.gz` file from the Releases, which is currently this file [here](https://github.com/MRCIEU/TwoSampleMR/archive/refs/tags/v0.5.6.tar.gz). Then run in R (assuming the `.tar.gz` file is in your current working directory)

```r
install.packages("TwoSampleMR-0.5.6.tar.gz", repos = NULL, type = "source")
```
If these don't work please let us know what error message you get.

**Comment by Humairarasheed** [comment]
I tried all install options from this page and from MR base page, but unable to install the TwoSampleMR package. `

`remotes::install_github("MRCIEU/TwoSampleMR")`
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘tmvnsim’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package ‘psych’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/psych’

The downloaded source packages are in
	‘/private/var/folders/mq/lb3ylym94k7bnjlppxw9sr940000gn/T/Rtmp26MGtG/downloaded_packages’
✔  checking for file ‘/private/var/folders/mq/lb3ylym94k7bnjlppxw9sr940000gn/T/Rtmp26MGtG/remotesa7c540e7ba38/MRCIEU-TwoSampleMR-82a4ca4/DESCRIPTION’ (398ms)
─  preparing ‘TwoSampleMR’: (345ms)
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘TwoSampleMR_0.5.6.tar.gz’
   
ERROR: dependency ‘psych’ is not available for package ‘TwoSampleMR’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/TwoSampleMR’
Warning messages:
1: In i.p(...) : installation of package ‘psych’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘/var/folders/mq/lb3ylym94k7bnjlppxw9sr940000gn/T//Rtmp26MGtG/filea7c54db0974d/TwoSampleMR_0.5.6.tar.gz’ had non-zero exit status

I tried `install.packages("TwoSampleMR-0.5.6.tar.gz", repos = NULL, type = "source")` too

Warning: invalid package ‘TwoSampleMR-0.5.6.tar.gz’
Error: ERROR: no packages specified
Warning in install.packages :
  installation of package ‘TwoSampleMR-0.5.6.tar.gz’ had non-zero exit status

**Comment by remlapmot** [comment]
> > Firstly please try the standard installation
> > ```r
> > install.packages("remotes")
> > remotes::install_github("MRCIEU/TwoSampleMR")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If that fails for some reason on your computer then download the latest `.tar.gz` file from the Releases, which is currently this file [here](https://github.com/MRCIEU/TwoSampleMR/archive/refs/tags/v0.5.6.tar.gz). Then run in R (assuming the `.tar.gz` file is in your current working directory)
> > ```r
> > install.packages("TwoSampleMR-0.5.6.tar.gz", repos = NULL, type = "source")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If these don't work please let us know what error message you get.
> > Thank you! I got this error:
> 
> Warning in install.packages : installation of package ‘TwoSampleMR-0.5.6.tar.gz’ had non-zero exit status

The installation using **remotes** is working.

``` r
remotes::install_github("MRCIEU/TwoSampleMR")
#> Using github PAT from envvar GITHUB_PAT
#> Downloading GitHub repo MRCIEU/TwoSampleMR@HEAD
#> 
#> ── R CMD build ─────────────────────────────────────────────────────────────────
#> * checking for file ‘/private/var/folders/wr/9_chh41d327cm97kngnr4qqh0000gp/T/RtmpeVHami/remotesc5f42c461b15/MRCIEU-TwoSampleMR-f5935b5/DESCRIPTION’ ... OK
#> * preparing ‘TwoSampleMR’:
#> * checking DESCRIPTION meta-information ... OK
#> * checking for LF line-endings in source and make files and shell scripts
#> * checking for empty or unneeded directories
#> * building ‘TwoSampleMR_0.5.6.tar.gz’
library(TwoSampleMR)
#> TwoSampleMR version 0.5.6 
#> [>] New: Option to use non-European LD reference panels for clumping etc
#> [>] Some studies temporarily quarantined to verify effect allele
#> [>] See news(package='TwoSampleMR') and https://gwas.mrcieu.ac.uk for further details
```

<sup>Created on 2023-02-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by Julie1130** [comment]
Thank you. I tried the standard way. The error is like this
ERROR: dependencies 'ieugwasr', 'MRMix', 'MRPRESSO', 'RadialMR' are not available for package 'TwoSampleMR'
* removing 'D:/R-4.1.2/library/TwoSampleMR'
There were 11 warnings (use warnings() to see them)
> warnings()
警告信息：
1: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:/Users/Lenovo/OneDrive/??": 文件名、目录名或卷标语法不正确。
2: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:/Users/Lenovo/OneDrive/??": 文件名、目录名或卷标语法不正确。
3: In i.p(...) :
  installation of package ‘C:/Users/Lenovo/AppData/Local/Temp/RtmpuSjpJf/file34786f3f6e62/MRMix_0.1.0.tar.gz’ had non-zero exit status
4: In i.p(...) : installation of package ‘fs’ had non-zero exit status
5: In i.p(...) :
  installation of package ‘C:/Users/Lenovo/AppData/Local/Temp/RtmpuSjpJf/file34786eee1b55/ieugwasr_0.1.5.tar.gz’ had non-zero exit status
6: In i.p(...) :
  installation of package ‘C:/Users/Lenovo/AppData/Local/Temp/RtmpuSjpJf/file347831861ffb/MRPRESSO_1.0.tar.gz’ had non-zero exit status
7: In i.p(...) : installation of package ‘fs’ had non-zero exit status
8: In i.p(...) :
  installation of package ‘C:/Users/Lenovo/AppData/Local/Temp/RtmpuSjpJf/file3478392642/RadialMR_1.0.tar.gz’ had non-zero exit status
9: In i.p(...) : installation of package ‘fs’ had non-zero exit status
10: In i.p(...) : installation of package ‘metadat’ had non-zero exit status
11: In i.p(...) :
  installation of package ‘C:/Users/Lenovo/AppData/Local/Temp/RtmpuSjpJf/file347875e63ed/TwoSampleMR_0.5.6.tar.gz’ had non-zero exit status

**Comment by Julie1130** [comment]
Thank you! I somehow solved this problem. Thank you so much!

**Comment by zillurbmb51** [comment]
> Firstly please try the standard installation
> 
> ```r
> install.packages("remotes")
> remotes::install_github("MRCIEU/TwoSampleMR")
> ```
> 
> If that fails for some reason on your computer then download the latest `.tar.gz` file from the Releases, which is currently this file [here](https://github.com/MRCIEU/TwoSampleMR/archive/refs/tags/v0.5.6.tar.gz). Then run in R (assuming the `.tar.gz` file is in your current working directory)
> 
> ```r
> install.packages("TwoSampleMR-0.5.6.tar.gz", repos = NULL, type = "source")
> ```
> 
> If these don't work please let us know what error message you get.

Hi,

I am getting the following error in R/4.3 in ubuntu:
```
install.packages('scripts/TwoSampleMR-0.5.7.tar.gz',repos = NULL,type = 'source')
Installing package into '/fp/homes01/u01/ec-mohammazr/R/x86_64-pc-linux-gnu-library/4.3'
(as 'lib' is unspecified)
During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C" 
2: Setting LC_TIME failed, using "C" 
3: Setting LC_MESSAGES failed, using "C" 
4: Setting LC_MONETARY failed, using "C" 
5: Setting LC_PAPER failed, using "C" 
6: Setting LC_MEASUREMENT failed, using "C" 
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
ERROR: dependencies 'MendelianRandomization', 'meta' are not available for package 'TwoSampleMR'
* removing '/fp/homes01/u01/ec-mohammazr/R/x86_64-pc-linux-gnu-library/4.3/TwoSampleMR'
Warning in install.packages :
  installation of package 'scripts/TwoSampleMR-0.5.7.tar.gz' had non-zero exit status
```

**Comment by remlapmot** [comment]
For Ubuntu 22.04 Jammy Jossa we provide a binary package courtesy of our [mrcieu.r-universe](https://mrcieu.r-universe.dev/), you should be able to install that by running in R
```r
install.packages('TwoSampleMR', repos = 'https://mrcieu.r-universe.dev/bin/linux/jammy/4.3/')
```

**Comment by Phyllis-Wei-2** [comment]
> Firstly please try the standard installation
> 
> ```r
> install.packages("remotes")
> remotes::install_github("MRCIEU/TwoSampleMR")
> ```
> 
> If that fails for some reason on your computer then download the latest `.tar.gz` file from the Releases, which is currently this file [here](https://github.com/MRCIEU/TwoSampleMR/archive/refs/tags/v0.5.6.tar.gz). Then run in R (assuming the `.tar.gz` file is in your current working directory)
> 
> ```r
> install.packages("TwoSampleMR-0.5.6.tar.gz", repos = NULL, type = "source")
> ```
> 
> If these don't work please let us know what error message you get.

Hi! I tried both of these methods and still couldn't install the package. When I tried the second option (with the gz file), I got:
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
ERROR: dependencies ‘ieugwasr’, ‘MendelianRandomization’, ‘mr.raps’, ‘psych’, ‘randomForest’, ‘meta’, ‘MRPRESSO’, ‘MRInstruments’, ‘RadialMR’, ‘MRMix’, ‘glmnet’ are not available for package ‘TwoSampleMR’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/TwoSampleMR’
Warning in install.packages :
  installation of package ‘TwoSampleMR-0.5.6.tar.gz’ had non-zero exit status

I am using a MacBook with M1 chip. Maybe that's part of the problem? Thank you!
