### ISSUE TITLE
Server code: 503; Server is possibly experiencing traffic, trying again...

### ISSUE THREAD

**Issue by zqzqcrystal325** [MRCIEU/TwoSampleMR#207]
Hi, dear all,
while I was running the following codes, the errors occured,
alzheimer_out_dat <- extract_outcome_data(
+   snps = exp_dat$SNP,
+   outcomes = "ieu-a-297"
+ )
Server code: 503; Server is possibly experiencing traffic, trying again...
Failed to retrieve results from server. See error status message in the returned object and contact the developers if the problem persists.

I tried several times, if we change the outcome to a different id, it would work, but this one did not work.
Any suggestions? Thanks!

**Comment by jamesrpriest** [comment]
Similar problem occurring here from different computers.

**Comment by explodecomputer** [comment]
Sorry about this, if there were server outages that could have explained it. At the moment I am not experiencing any problems. If you send me the code that is giving errors I will investigaet

**Comment by jamesrpriest** [comment]
library("TwoSampleMR");

packageVersion("TwoSampleMR");

> [1] ‘0.5.4’

Ao.white.file = "/Users/jpriest/Downloads/test.e08.CLEANED.results_glm_AoD.all.white.txt";

Ao.white_exp_dat <- read_exposure_data(Ao.white.file, sep = "\t",
                                       snp_col = "SNP",
                                       beta_col = "BETA",
                                       se_col = "SE",
                                       eaf_col = "EAF",
                                       effect_allele_col = "EFFECT_ALLELE",
                                       other_allele_col = "OTHER_ALLELE",
                                       pval_col = "PVAL");
>No phenotype name specified, defaulting to 'exposure'.

Ao.white_exp_dat$exposure = "ascending_aorta_diameter.white";

Ao.white_exp_dat <- clump_data(Ao.white_exp_dat, clump_r2 = 0.001, clump_kb=100);
>Please look at vignettes for options on running this locally if you need to run many instances of this command.
>Using access token. For info on how this is used see logging_info()
>Clumping CgQixd, 9 variants, using EUR population reference
>Server code: 503; Server is possibly experiencing traffic, trying again...
>Server code: 503; Server is possibly experiencing traffic, trying again...
>Server code: 503; Server is possibly experiencing traffic, trying again...
>Server code: 503; Server is possibly experiencing traffic, trying again...
>Server code: 503; Server is possibly experiencing traffic, trying again...
>Server code: 503; Server is possibly experiencing traffic, trying again...
>Server error: 503
>Failed to retrieve results from server. See error status message in the returned object and contact the developers if the >problem persists.
>
[test.e08.CLEANED.results_glm_AoD.all.white.txt](https://github.com/MRCIEU/TwoSampleMR/files/5001817/test.e08.CLEANED.results_glm_AoD.all.white.txt)
Removing 9 of 9 variants due to LD with other variants or absence from LD reference panel

**Comment by jamesrpriest** [comment]
> Sorry about this, if there were server outages that could have explained it. At the moment I am not experiencing any problems. If you send me the code that is giving errors I will investigaet

Thanks-- have uploaded test code and error messages. Had thought it might be some error related to access token, but error is reproducible on a university server & my laptop, and results of ieugwasr::check_access_token() look ok.

**Comment by jamesrpriest** [comment]
> Similar problem occurring here from different computers.

Apologies for wasting your time, this was due to a simple error on SNP ids
