### ISSUE TITLE
Questions about GWAS pipeline and single SNP

### ISSUE THREAD

**Issue by kaanokay** [MRCIEU/TwoSampleMR#208]
Hi,

First, I want to thank you for this nice MR package.

I have several questions about your package.

Question 1:

I tried two different pipelines on my GWAS data.

in the first pipeline:

-- I used clump_data() function to remove LD SNPs from GWAS data having ~2.000.000 SNPs, but I got time-out error and the clump step was unsuccessful, so I designed the second pipeline. Does time out error is expected for my GWAS data? Is it a problem? If I didn't get time-out error, then I would make genome-wide significance filtering (p-value < 5x10-8) for remaining SNPs and I would use these SNPs for MR analysis.

in the second pipeline (consecutive steps):

-- First, I manually extracted genome-wide significance SNPs (i.e., p-value < 5x10-8) from exposure GWAS data.
-- Second, those extracted SNPs were underwent LD pruning with clump_data() function.
-- Third, statistically significant and LD pruned SNPs were obtained from outcome data.
-- Fourth, exposure and outcome data having common SNPs were harmonized with using harmonise_data() function
-- Fifth, harmonized data was used in Mendelian Randomization analysis with mr() function

Which pipeline do you suggest for me?

------------------------------------------------------------------------

Question 2: 

When I performed the second pipeline that I mentioned above, I got only one SNP instead of multiple SNPs and used respective SNP as the instrumental variable for MR analysis. In the end, I didn't get MR results such as IVW and Egger, but I got only a wald ratio with a significant p-value. 

Can single SNP be used in MR analysis? Can a single SNP's wald ratio with a statistically significant p-value be used for MR interpretation instead of other MR methods such as IVW?

I can't perform heterogeneity and pleiotropy analyses with single SNP. Is this a problem?

------------------------------------------------------------------------

Question 3: Can you suggest any confidence pipeline that I can perform?

Very thanks for your response.
Best regards.

**Comment by zqzqcrystal325** [comment]
Hi,

I have several suggestions for you, hope it would help you.

In the first pipeline, I think you should make genome-wide significance filtering (p-value < 5x10-8) first, then to remove the LD SNPs, too many SNPs would easily gets you the time-out error since the calculation was too complicated.

In the second pipeline, this happens for some exposures since the LD pruning and data harmonization removed many SNPs, try a different GWAS dataset for that exposure if possible.

Thanks

**Comment by kaanokay** [comment]
Thanks for your quick response.

I have no other exposure GWAS data, so using this GWAS data with single SNP is enough for MR interpretation? Can I put our results based on the wald ratio of single SNP in an article?

Thanks again.

**Comment by explodecomputer** [comment]
hey @kaanokay it's considered best practice to use a colocalisation method when you have only one instrument, e.g. see https://mrcieu.github.io/gwasglue/articles/colocalisation.html and this paper that describes good practice https://pubmed.ncbi.nlm.nih.gov/28985495/

**Comment by kaanokay** [comment]
Hi @explodecomputer,

Thanks for your guidance.
