### ISSUE TITLE
Clump data error : unused argument (pop = pop)

### ISSUE THREAD

**Issue by jonnyrose** [MRCIEU/TwoSampleMR#209]
Hi,  I am trying to clump_data:

Model1_exp_datClumped <- clump_data(Model1_exp_dat)
Model1_exp_datClumped <- clump_data(Model1_exp_dat, pop="EUR")

I even added a pop variable to the dataset.  Both ways I got the following error message:
Error in ieugwasr::ld_clump(d, clump_kb = clump_kb, clump_r2 = clump_r2,  : 
  unused argument (pop = pop)

I did clump using:
ieugwasr::id_clump(Model1_exp_dat) 

It looks like you may be adding different reference panels but I am not sure how to use them.  

Thanks!

**Comment by explodecomputer** [comment]
Hey I think you need to upgrade the ieugwasr package

```
devtools::install_github("mrcieu/ieugwasr")
```

cheers

**Comment by jonnyrose** [comment]
Thanks!
