### ISSUE TITLE
I have trouble with connecting github when I use vmware, can I try local installation? my systerm is window7, how to download the source package? thanks

### ISSUE THREAD

**Issue by yfShi0901** [MRCIEU/TwoSampleMR#214]

**Comment by remlapmot** [comment]
Hi there. You have a couple of options.

1. The source version of the package, i.e. `.tar.gz` file, is available from the tags page [here](https://github.com/MRCIEU/TwoSampleMR/tags).

    So take the latest `.tar.gz` file, i.e. this one [here](https://github.com/MRCIEU/TwoSampleMR/archive/0.5.4.tar.gz).

2. Another way to get the source version is to download the repo. 
    * Then open the `TwoSampleMR.Rproj` file in RStudio. 
    * Then go to the Build pane and click the Build Source Package option from the dropdown menu. 
    * You will find the `.tar.gz` file in the folder level above your .Rproj file. 

3. Or email me and I can send you the `.tar.gz` file at the latest commit.

**Comment by yfShi0901** [comment]
Thanks a lot, I will try this. Best.
