### ISSUE TITLE
clump_data issue again

### ISSUE THREAD

**Issue by bethleegy** [MRCIEU/TwoSampleMR#215]
Hi there,

I seem to be running into the same issue again. I'm clumping a file with multiple exposures but it stops once it reaches an exposure with only one SNP. The message that appears before stopping the iteration is "Only one SNP for (ID)." 

Please let me know if this can be fixed soon! Tried running on different versions again this time to no avail. Thanks in advance.

_Originally posted by @bethleegy in https://github.com/MRCIEU/TwoSampleMR/issues/175#issuecomment-676837937_

**Comment by explodecomputer** [comment]
Hey @bethleegy thanks for the comment. I tried to recreate an example and don't experience the error

```
a <- rbind(extract_instruments(2), extract_instruments(7)[1,], extract_instruments(1001), extract_instruments(22))
b <- clump_data(a)
```

here the second ID is restricted to have only one variant, when it runs it says only one available but then continues to the next ones

```
Clumping ieu-a-2, 79 variants, using EUR population reference
Removing 1 of 79 variants due to LD with other variants or absence from LD reference panel
Only one SNP for ieu-a-7
Clumping ieu-a-1001, 73 variants, using EUR population reference
Removing 2 of 73 variants due to LD with other variants or absence from LD reference panel
Clumping ieu-a-22, 83 variants, using EUR population reference
Removing 2 of 83 variants due to LD with other variants or absence from LD reference panel
```

can you send me example code that leads to the error?

**Comment by bethleegy** [comment]
Ah. I just ran it again and it went through without an issue. Weird -- but thank you for the responsiveness and apologies for the false alarm!

**Comment by fabianacz** [comment]
I am trying to perform clumping using the 1000 genomes as reference dataset.
I been experiencing the following error

To get the same LD reference dataset that is used by the API, you can download it directly from here: http://fileserve.mrcieu.ac.uk/ld/1kg.v3.tgz

To get a path to plink you can do the following:

devtools::install_github("explodecomputer/genetics.binaRies")
plink <- genetics.binaRies::get_plink_binary()

Using plink **
orru_clump <- ld_clump(
dplyr::tibble(rsid = summaryset_orru$rsid, pval = summaryset_orru$p, id = summaryset_orru$id),
plink_bin = "plink",
bfile = "1kg.v3" # This is the same directory as my R project

)

Clumping ebi-a-GCST90001942, 15141982 variants, using EUR population reference PLINK v1.90b7 64-bit (16 Jan 2023) [www.cog-genomics.org/plink/1.9/](http://www.cog-genomics.org/plink/1.9/) (C) 2005-2023 Shaun Purcell, Christopher Chang GNU General Public License v3 Logging to C:\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file3930d7a4440.log. Options in effect: --bfile 1kg.v3 --clump C:\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file3930d7a4440 --clump-kb 10000 --clump-p1 0.99 --clump-r2 0.001 --out C:\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file3930d7a4440 65210 MB RAM detected; reserving 32605 MB for main workspace. Error: Failed to open 1kg.v3.bed. Error in file(file, "rt") : cannot open the connection In addition: Warning message: In file(file, "rt") : cannot open file 'C:\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file3930d7a4440.clumped': No such file or directory

** Using plink2 **

plink2 <- "C:/Users/corsfmdg/Desktop/R/R_ME" # I have put plink.exe in the same directory as my R project

orru_clump <- ld_clump(
dplyr::tibble(rsid=summaryset_orru$rsid, pval=summaryset_orru$p, id=summaryset_orru$id),
plink_bin = "plink2",
bfile = "1kg.v3"
)

Clumping ebi-a-GCST90001942, 15141982 variants, using EUR population reference Error in file(file, "rt") : cannot open the connection In addition: Warning message: In file(file, "rt") : cannot open file 'C:\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file39303fa538bf.clumped': No such file or directory

any suggestions how to sort that?
