### ISSUE TITLE
proxies were not returned (problem in extract_outcome_data)

### ISSUE THREAD

**Issue by maki8080** [MRCIEU/TwoSampleMR#216]
Hi !
I used "extract_outcome_data" to extracted SNPs for outcome. 2 SNPs were not present in the outcome GWAS. Then 2 proxies with the target SNPs were searched and extracted for instead, as explained below:

> BMD_outcome <- extract_outcome_data(
     snps = exposure_data$SNP,
     outcomes =  "ieu-a-982") 
Extracting data for 5 SNP(s) from 1 GWAS(s)
Finding proxies for 2 SNPs in outcome ieu-a-982
Extracting data for 2 SNP(s) from 1 GWAS(s)

However, the proxies were not returned and reflected in the results.
Why did this happen? What should I do to get the outcome of the proxies? 
Thanks in advances.

**Comment by explodecomputer** [comment]
hey the message just says that it was looking for proxies, if it didn't return anything then it means no proxies were found in the requested dataset

**Comment by maki8080** [comment]
Thank you for your reply. I understood.

**Comment by Shicheng-Guo** [comment]
As the manual shows: "By default if a particular requested SNP is not present in the outcome GWAS then a SNP (proxy) that is in LD with the requested SNP (target) will be searched for instead". Usually, there will be multiple SNPs showed higher LD, for example in WGS data, then which one will be selected as proxy SNPs or it will be randomly selection any one? 

Thanks
Shicheng
