### ISSUE TITLE
HbA1c datasets of MRbase

### ISSUE THREAD

**Issue by jamesliu0501** [MRCIEU/TwoSampleMR#223]
Dear Mr.(s),
 
I realize that the MRbase package has been updated.
 
I used the “extract_outcome_data” function to extract the genetic data of glycated haemoglobin (HbA1c) (outcome id: ieu-a-758,  from MAGIC Soranzo N et al 2010) previously.
 
However, this outcome dataset is missing in this updated version.
 
I am wondering whether it will be updated later?
 
Thank you so much indeed for your assist.
 
Regards,
James

**Comment by mightyphil2000** [comment]
Hi James

Sorry about that. We had to take that dataset down temporarily because we discovered problems with the effect allele frequency column.
________________________________

**Comment by mvab** [comment]
Hi there, 
Any idea when all quarantined datasets will be available again? 

Thanks!

**Comment by mvab** [comment]
Hi @mightyphil2000 @explodecomputer, 

Just wondering if you have an estimate for when the quarantined datasets will be available again? 

Many thanks,
Marina

**Comment by mightyphil2000** [comment]
Hi Marina

Will try to restore the MAGIC datasets this week. Is that all you need?
________________________________

**Comment by mvab** [comment]
Hi Phil, 

Thanks, I just need these: 

ieu-a-758
ieu-a-770
ieu-a-771
ieu-a-773
ieu-a-775
ieu-a-777
ieu-a-778

**Comment by mightyphil2000** [comment]
Thanks do you also have the pmids for them?
________________________________

**Comment by mvab** [comment]
Yes: 
ieu-a-758	20858683
ieu-a-770	20081858
ieu-a-771	20081858
ieu-a-773	22581228
ieu-a-775	22581228
ieu-a-777	22885924
ieu-a-778	22885924

**Comment by mvab** [comment]
Hi @mightyphil2000, 

Just wanted to check if there is any progress on this? 

Thanks,
Marina

**Comment by mightyphil2000** [comment]
Hi Marina

Sorry for the delay. Hoping to sort these out by end of next week.
________________________________

**Comment by mvab** [comment]
Hi @mightyphil2000, 

Is there any progress on this? Can I do anything to help?

Many thanks,
Marina

**Comment by mightyphil2000** [comment]
Hi Marina

Do you have any of the meta data for these files? e.g. the trait name, units etc?

bw
Philip
________________________________

**Comment by mvab** [comment]
Hi Philip,

Yeah I've got some metadata for those traits, see the attached file
[glyceamic_traits.txt](https://github.com/MRCIEU/TwoSampleMR/files/5943000/glyceamic_traits.txt)

Many thanks,
Marina

**Comment by mightyphil2000** [comment]
The following MAGIC datasets have been re-instated and have been assigned new IDs. Allele frequency has been removed. 

old ID -> new ID
ieu-a-773 -> ieu-b-113
ieu-a-777 -> ieu-b-114
ieu-a-775 -> ieu-b-115
ieu-a-778 -> ieu-b-116
ieu-a-758 -> ieu-b-112
ieu-a-770 -> ieu-b-117
ieu-a-771 -> ieu-b-118
