### ISSUE TITLE
Steiger test for binary traits

### ISSUE THREAD

**Issue by niekverw** [MRCIEU/TwoSampleMR#225]
I noticed that the total sample size is being used to test the r2 difference. I was wondering if this should actually be the case-count if it is a binary trait?  
 
https://github.com/MRCIEU/TwoSampleMR/blob/1c26512ed9fd95e4cc2d698ec0ff5b99ec17d337/R/steiger.R#L138
https://github.com/MRCIEU/TwoSampleMR/blob/a5fbbd0e520d140f14fbe9a34525a5e275d92fad/R/steiger_filtering.R#L48

**Comment by explodecomputer** [comment]
Thanks for this @niekverw - I have edited now to use effective sample size instead of actual sample size for case-control studies
