### ISSUE TITLE
Failed to extract instrument from MRbase

### ISSUE THREAD

**Issue by jc-dusingize** [MRCIEU/TwoSampleMR#227]
Hi,
I am trying to extract instruments from MRbase but I am being disconnected from the server (see screenshot below) for all traits with ID starting with  ID:  “UKB-a-“ or “UKB-b (for e.g.: UKB-a-248 ).  Any tips how to fix this ?  

![pastedImage](https://user-images.githubusercontent.com/72802829/95861403-ba84e000-0da4-11eb-8787-b9b390423592.png)

Many thanks
Jean Claude

**Comment by mightyphil2000** [comment]
Hi Jean

It seems to work for other UKB-a IDs I tried. That trait is no longer accessible in the database. The most likely reason is we identified a problem with that particular file and so had to take down. Do you know  which trait it corresponded to?

bw
Philip
________________________________

**Comment by jc-dusingize** [comment]
Hi Philip,

Could you please try for e.g. these phenotypes below? None of them worked for me:

Freckles        UKB-b-15
tanning UKB-b-533
Melanocytic naevi       UKB-b-6772
Hypothyroidism  UKB-a-523
hayfever        UKB-a-254
 Vitiligo       UKB-a-115
Alopecia areata UKB-b-604
balding pattern 4       UKB-a-303



________________________________

**Comment by mightyphil2000** [comment]
Hi Jean

It looks there's a technical issue that we're hoping to fix soon.

In the meantime, could try accessing those traits via Open GWAS?
https://gwas.mrcieu.ac.uk/

bw
Philip


________________________________

**Comment by jc-dusingize** [comment]
Hi Philip,
Yes, I was able to access the data via Open GWAS. Although, downloading every individual GWAS is cumbersome if one need to perform a PheWAS.

By the way, would you please share with me the R script used to perform the analyses of the following paper (of course if possible)?  A Phenome-Wide Mendelian Randomization
Study of Pancreatic Cancer Using Summary Genetic Data? I am trying to find an automated way to run similar analyses without going through individual GWAS.

Thanks
Jean Claude

**Comment by mightyphil2000** [comment]
Hi Jean

You should be able to extract the summary data for a single SNP or small set of SNPs for all the traits in Open GWAS , although the results are filtered on P value <0.001
https://gwas.mrcieu.ac.uk/phewas/rs7412/

You could also use the extract_instruments function of the TwoSampleMR package to conduct a phewas. Have you tried that? This function will extract your SNP or SNPs from everything in the database.

For the script could you contact Ryan Langdon
"Ryan Langdon" <ryan.langdon@bristol.ac.uk>


bw
Philip
________________________________

**Comment by jc-dusingize** [comment]
Hi Philip,

Yes, I tried  to use extract_instruments function of the TwoSampleMR package but as I told you previously, it doesn't work for some traits. See below.


> BMI <- extract_instruments(outcomes='UKB-a-248')
> head(BMI)
NULL


Thanks

JC

________________________________

**Comment by mightyphil2000** [comment]
Sorry I meant to say the extract_outcome_data function. You could use that to extract your SNPs of interest from the database (although yes I agree it may not work for some of the traits).

As I mentioned, you could also use the phewas app. Although it filters on P value, it is quite lenient for a hypothesis-free scan. Therefore you shouldn't miss anything that would pass a conventional bonferroni-corrected multiple testing selection threshold.
e.g
 https://gwas.mrcieu.ac.uk/phewas/rs7412/


________________________________

**Comment by jc-dusingize** [comment]
Yes, I've been playing with the  phewas app, but it only allows to test one SNP at a time. My instrument consists of 60 SNPs and I want to perform the TwoSampleMR analyses.

JC
________________________________

**Comment by mightyphil2000** [comment]
For the phewas (multi SNP lookup across all traits) can you try:

R package
https://github.com/mrcieu/ieugwasr
https://mrcieu.github.io/ieugwasr/articles/guide.html

RESTful API
https://gwas-api.mrcieu.ac.uk/

________________________________

**Comment by jc-dusingize** [comment]
Ok, let me give it a try and see how it goes.


JC

________________________________

**Comment by mightyphil2000** [comment]
Hi JC

Did you try ieugwasr?

I believe you could use this function for your needs:

library(ieugwasr)
associations()
________________________________

**Comment by jc-dusingize** [comment]
Hi Philip,
Yes, that function worked. Although this method is not user friendly if you have a large number of SNP instrument. Also the documentation is not very rich and it takes time to figure out what to do.

Thanks
JC
