### ISSUE TITLE
Did not open the command "ao <- available_outcomes()"

### ISSUE THREAD

**Issue by xiangboyulan** [MRCIEU/TwoSampleMR#23]
Dear all,

I did not run the command "ao <- available_outcomes()", because the web “http://localhost:1410/?state=8bPKmHj10q&code=4/AACXU4AFIxEow6qg Qp0rHS0CPpAgvs1yoUKRD6CE81xc4NI_4ocE_P4L8rQMid0mK6n4WgbXQt-NAkN7eZVJzA#" couldn't be opened. Could you give some advice to me? 
Thank you so much!

Bo

**Comment by explodecomputer** [comment]
I'm not sure why this might be the case, it could be an issue with google not being available in your location? Or something to do with the version of the googleAuthR package. To sidestep the issue you could run `available_outcomes(access_token=NULL)` which will mean you only get access to public data

**Comment by xiangboyulan** [comment]
Yes, the google can't be available here
