### ISSUE TITLE
p-value was above 0.05 even though the 95% CI did not contain nulls

### ISSUE THREAD

**Issue by maki8080** [MRCIEU/TwoSampleMR#230]
Hi,
I would like to ask about MR-Egger analysis. 
For some estimates, the p-value was above 0.05 even though the 95% CI did not contain nulls. 
Could you tell me why I got this result?
Thank you very much for your reply.

Best regards, 
Maki

**Comment by mightyphil2000** [comment]
Hi Maki

Could you provide further details on the results?
________________________________

**Comment by maki8080** [comment]
Dear mightyphil2000 

Thank you very much for your reply.

We evaluated the causal effect of A on B in the MR analysis.

ab_mr <- mr(ab_harmonise)
ab_odds <- generate_odds_ratios(ab_mr)
ab_odds

The result of the MR-Egger analysis was as follows:

Beta: 1.056, se: 0.493, pval: 0.165
Odds ratio: 2.877, 95% CI: 1.094-7.567

When p < 0.05 was considered statistically significant, there was no effect  A on B. On the other hand, the 95 %CI did not contain nulls.
I don’t understand the interpretation of the result.
Could you tell me why I got this result?

Sincerely,
Maki

**Comment by mightyphil2000** [comment]
Hi Maki

What traits A and B?

Is B a binary outcome? Was it estimated in UK Biobank?

bw
Philip

________________________________

**Comment by maki8080** [comment]
Dear Philip

I used four A-related SNPs as exposure selected from GWAS among about 15000 individuals.
B is a continuous outcome obtained from UK Biobank. 

Best regards,
Maki

**Comment by mightyphil2000** [comment]
Hi Maki

If the outcome is a continuous variable I would not use the generate_odds_ratio function. That is intended to be use when your MR results are log odds ratios for disease. However, even taking that into account, the 95% confidence interval on the correct scale also doesn't include the null (null is 0). What's happening is that MR Egger uses a t distribution, taking into account the number of SNPs (for degrees of freedom), to estimate the p value, while the confidence intervals use a Z distribution. The 95% confidence intervals will look discrepant to the P value when the number of SNPs in the model is small. How many SNPs were in your mr egger model?

bw
Philip


________________________________

**Comment by maki8080** [comment]
Dear Philip

Your explanation really helped!
As you pointed out, I used only 4 SNPs in my mr-Egger model. 
Thanks a lot.

Sincerely, 
Maki

**Comment by mightyphil2000** [comment]
Great.

We generally recommend against using MR-Egger regression when the number of SNPs is that small.

bw
philip
________________________________

**Comment by maki8080** [comment]
Dear Philip

Thanks for the good tips.

Best regards
Maki
