### ISSUE TITLE
available_outcomes()

### ISSUE THREAD

**Issue by qserenali** [MRCIEU/TwoSampleMR#231]
I last used this package in July using version  0.5.4 and was able to retrieve the outcomes. I came back today and the same command threw the following error message. I upgraded the code to 0.5.5 and got the same. I read somewhether that the google oauth is no longer needed and renamed my mrbase.oauth file but still did not work. 
> available_outcomes()
Error: $ operator is invalid for atomic vectors

I also generated a token somehow and got no luck
available_outcomes(access_token="this_is_a_fake_token_9bq1icDYASqe8ryNQk6k_u6IrI")

Has the command line access to the database changed?

Thanks!

**Comment by explodecomputer** [comment]
apologies must have been a server issue, should be working now
