### ISSUE TITLE
Server code: 503; Server is possibly experiencing traffic, trying again

### ISSUE THREAD

**Issue by Chenxi0730** [MRCIEU/TwoSampleMR#232]
Hi, developing team,

When I was trying to access to ieu-a-832 summary data based on a few exposure-instrument datasets, sometimes R reported this error: "Server code: 503; Server is possibly experiencing traffic, trying again". I have tried to reinstall the package but it didn't work. Could you or anyone who has solved this problem please give me some advice about this? Many thanks!

**Comment by yemaozi285** [comment]
yep! l met this one right now

**Comment by meghanasp21** [comment]
Hi. I'm having the same issue and reinstalled also. Was the solution posted?

**Comment by Chenxi0730** [comment]
Hi

I don't think so. But I found two possible reasons. One is the internet
issue, so try it another time. The other may be that the server could not
find some specific SNP or their proxies. I deleted two SNPs with this
problem and then it ran smoothly.

**Comment by youruilian123** [comment]
have you resolve this problem? I experienced it today.but I can run it yesterday. how can I resolve it？

**Comment by meghanasp21** [comment]
Hi. The thing that was causing my issue is the variants were not in rsid. So, the server timed out. Once I converted everything to rsid, it worked. Hope that helps!

**Comment by youruilian123** [comment]
OK, thank you very much for your reply,I will try this method.^_^



At 2021-02-01 05:02:45, "meghanasp21" <notifications@github.com> wrote:

Hi. The thing that was causing my issue is the variants were not in rsid. So, the server timed out. Once I converted everything to rsid, it worked. Hope that helps!
