### ISSUE TITLE
Extract outcome data issue

### ISSUE THREAD

**Issue by ChristinaLg** [MRCIEU/TwoSampleMR#233]
I last used  this package and want to extract the outcome data. But when I used the "extract_outcome_data", extracting data from "ieu-a-966", the outcome data is NULL.

>out_dat <- extract_outcome_data(snps=SNP, outcomes = 'ieu-a-966',proxies=FALSE,access_token = NULL)
Extracting data for 842 SNP(s) from 1 GWAS(s)

> out_dat
NULL

the variable SNP contains 842 SNPs from reading my data.

Thank you very much.

**Comment by t0mrg** [comment]
Tested with:

```r
> SNP = c("rs805297","rs1802127","rs8034191","rs12440014")
> out_dat <- extract_outcome_data(snps=SNP, outcomes = 'ieu-a-966',proxies=FALSE,access_token = NULL)
Extracting data for 4 SNP(s) from 1 GWAS(s)
```

Code functioning as expected. Please ensure your variable ```SNP``` is consistent with the example given above.

**Comment by BroQuan** [comment]
@t0mrg Hello sir, are you sure the "out_dat" is not NULL? However, when I run your code, my result is NULL. And what's worse, even I run code as follows, my result is NULL too.
`> exp_dat <- extract_instruments(outcomes='ieu-a-966', p1 = 1, clump = FALSE)
> exp_dat
NULL
`

**Comment by BroQuan** [comment]
`
print(12312321)
`

**Comment by BroQuan** [comment]
@t0mrg Hello sir, are you sure the "out_dat" is not NULL? However, when I run your code, my result is NULL. And what's worse, even I run code as follows, my result is NULL too.
`
> exp_dat <- extract_instruments(outcomes='ieu-a-966', p1 = 1, clump = FALSE)
> exp_dat
NULL
`

**Comment by BroQuan** [comment]
`R
exp_dat <- extract_instruments(outcomes='ieu-a-966', p1 = 1, clump = FALSE)
exp_dat
NULL
`

**Comment by BroQuan** [comment]
`exp_dat <- extract_instruments(outcomes='ieu-a-966', p1 = 1, clump = FALSE)
exp_dat
NULL`

**Comment by BroQuan** [comment]
@t0mrg Hello sir, are you sure the "out_dat" is not NULL? I don't know why, when I run your code, my result is NULL.
And what's worse, even I run code as follows, my result is NULL too.
`exp_dat <- extract_instruments(outcomes='ieu-a-966', p1 = 1, clump = FALSE)
exp_dat
NULL`

**Comment by BroQuan** [comment]
Hello sir, are you sure the "out_dat" is not NULL? I don't know why, when I run your code, my result is NULL.
And what's worse, even I run code as follows, my result is NULL too.
```R
> exp_dat <- extract_instruments(outcomes='ieu-a-966', p1 = 1, clump = FALSE)
> exp_dat
NULL
```

**Comment by BroQuan** [comment]
@t0mrg Hello sir, are you sure the "out_dat" is not NULL? I don't know why, when I run your code, my result is NULL.
And what's worse, even I run code as follows, my result is NULL too.
```R
> exp_dat <- extract_instruments(outcomes='ieu-a-966', p1 = 1, clump = FALSE)
> exp_dat
NULL
```

**Comment by BroQuan** [comment]
```
> exp_dat <- extract_instruments(outcomes='ieu-a-966', p1 = 1, clump = FALSE)
> exp_dat
NULL
```

**Comment by BroQuan** [comment]
While I use other ids, such as "ieu-a-2", it works. Why would this happen?

**Comment by Zhuyj29** [comment]
I've got the same question, and after I tried the following code:

> SNP = c("rs805297","rs1802127","rs8034191","rs12440014")
> out_dat <- extract_outcome_data(snps=SNP, outcomes = 'ieu-a-966',proxies=FALSE,access_token = NULL)

the outcome data is NULL, and neither do "ieu-a-2"

**Comment by Zhuyj29** [comment]
I've got the same question, but the outcome are NULL when I run the code given above: and with id "ieu-a-2" 

> exp_dat <- extract_instruments(outcomes='ieu-a-966', p1 = 1, clump = FALSE)
> exp_dat

and the outcome remains to be NULL with id "ieu-a-2" .

**Comment by t0mrg** [comment]
@damar-insitro there are some issues caused by very heavy load on the database cluster at the moment, but I have tested this again and it should work (see below) once the load reduces.

```
> SNP = c("rs805297","rs1802127","rs8034191","rs12440014")
> out_dat <- extract_outcome_data(snps=SNP, outcomes = 'ieu-a-966',proxies=FALSE,access_token = NULL)
Extracting data for 4 SNP(s) from 1 GWAS(s)
> out_dat
         SNP chr      pos beta.outcome se.outcome samplesize.outcome pval.outcome eaf.outcome effect_allele.outcome
1  rs1802127   6 31729925    0.0141189   0.062319              27209  8.29250e-01   0.0209435                     T
2  rs8034191  15 78806023    0.2866870   0.024383              27209  2.53980e-53   0.3688550                     C
3 rs12440014  15 78926726   -0.2599190   0.017224              27209  5.68984e-30   0.2180010                     G
  other_allele.outcome                     outcome id.outcome originalname.outcome  outcome.deprecated
1                    C Lung cancer || id:ieu-a-966  ieu-a-966          Lung cancer Lung cancer ||  ||
2                    T Lung cancer || id:ieu-a-966  ieu-a-966          Lung cancer Lung cancer ||  ||
3                    C Lung cancer || id:ieu-a-966  ieu-a-966          Lung cancer Lung cancer ||  ||
  mr_keep.outcome data_source.outcome
1            TRUE                 igd
2            TRUE                 igd
3            TRUE                 igd
```

**Comment by damar-insitro** [comment]
Okay, I will try rerunning a few times in the next few days. Thank you for the quick reply!

**Comment by xysifang** [comment]
@t0mrg The outcome are NULL when I run the code given above: and with the test snps.

**Comment by t0mrg** [comment]
@xysifang - we have had ongoing server load issue due to very high demand. We have now implemented some throttling of very high intensity usage, and are seeing much more stable usage. I have tested your code just now, and it is returning data as expected. We will continue to monitor server load, and are planning to implement other steps to address the high levels of usage.

```
r$> SNP = c("rs805297","rs1802127","rs8034191","rs12440014")

r$> out_dat <- extract_outcome_data(snps=SNP, outcomes = 'ieu-a-966',proxies=FALSE,access_token = NULL)
Extracting data for 4 SNP(s) from 1 GWAS(s)

r$> out_dat
         SNP chr      pos beta.outcome se.outcome samplesize.outcome pval.outcome eaf.outcome effect_allele.outcome other_allele.outcome                     outcome id.outcome originalname.outcome  outcome.deprecated mr_keep.outcome data_source.outcome
1  rs1802127   6 31729925    0.0141189   0.062319              27209  8.29250e-01   0.0209435                     T                    C Lung cancer || id:ieu-a-966  ieu-a-966          Lung cancer Lung cancer ||  ||             TRUE                 igd
2  rs8034191  15 78806023    0.2866870   0.024383              27209  2.53980e-53   0.3688550                     C                    T Lung cancer || id:ieu-a-966  ieu-a-966          Lung cancer Lung cancer ||  ||             TRUE                 igd
3 rs12440014  15 78926726   -0.2599190   0.017224              27209  5.68984e-30   0.2180010                     G                    C Lung cancer || id:ieu-a-966  ieu-a-966          Lung cancer Lung cancer ||  ||             TRUE                 igd
```

**Comment by xxz19900** [comment]
It still doesn't work. The result is Null.

**Comment by MirandaKhoury** [comment]
I'm having the same issue as many of the above commenters. Regardless of what outcome ID I put in, I always get NULL. Running the sample code provided by @t0mrg also returns a value of null. I tried running the code at different times of the day over several days, even weeks -- I first encountered the problem 3 weeks ago and have tried running the code periodically from then until now -- but it has never worked. Either the server is under _extreme_ load or something else is wrong. Additonal advice would be much appreciated!

**Comment by yaoli00** [comment]
It still doesn't work. The result is Null.

**Comment by whoolatoyuposmy** [comment]
结果仍然是null

**Comment by gabumon0** [comment]
Yes, The result is Null, how to solve it?

**Comment by YinsZhong** [comment]
try options(ieugwasr_api = 'gwas-api.mrcieu.ac.uk/')

**Comment by JivonKiang** [comment]
Ran into the same problem, anything that ran MRInstruments showed up as NULL when extracting the ending variable

**Comment by hanjaydaxia** [comment]
but The output result is still null

outcome_dat <- extract_outcome_data(exposure_dat$SNP, c('ieu-b-43'), proxies = 1, rsq = 0.8, align_alleles = 1, palindromes = 1, maf_threshold = 0.3)#额叶痴呆 
Extracting data for 5 SNP(s) from 1 GWAS(s) 
Finding proxies for 5 SNPs in outcome ieu-b-43
 Extracting data for 5 SNP(s) from 1 GWAS(s) 
> outcome_dat 
NULL

**Comment by hanjaydaxia** [comment]
Results can be obtained by extracting from other databases at the same time.
> outcome_dat <- extract_outcome_data(exposure_dat$SNP, c('finn-b-KRA_PSY_DEMENTIA_EXMORE'), proxies = 1, rsq = 0.8, align_alleles = 1, palindromes = 1, maf_threshold = 0.3)#额叶痴呆
Extracting data for 5 SNP(s) from 1 GWAS(s)
> outcome_dat <- extract_outcome_data(exposure_dat$SNP, c('finn-b-F5_ALZHDEMENT'), proxies = 1, rsq = 0.8, align_alleles = 1, palindromes = 1, maf_threshold = 0.3)
Extracting data for 5 SNP(s) from 1 GWAS(s)
> outcome_dat
        SNP chr       pos beta.outcome se.outcome samplesize.outcome pval.outcome
