### ISSUE TITLE
error in harmonise_data function

### ISSUE THREAD

**Issue by Despoina-Manousaki** [MRCIEU/TwoSampleMR#236]
Hi,

I am a new user of the 2 sample MR package. I am getting the following error when running the harmonise_data function
harmonise_data(exposure_dat, outcome_dat, action = 2)
Error in fix.by(by.x, x) : 'by' must specify a uniquely valid column

Then I specify the by=..., but a new error appears

> dat<-harmonise_data(exposure_dat,outcome_dat, action =2, by=c("SNP")
Error in `$<-.data.frame`(`*tmp*`, "beta.exposure", value = numeric(0)) : 
  replacement has 0 rows, data has 17

Does that have to do with the fact that the exposure and outcome files do not have the same number of rows?

Thank you!

**Comment by lanxianmei** [comment]
you can check the exposure and outcome files yourself, by printing or dim().

**Comment by mightyphil2000** [comment]
This error can mean that there is something wrong in the formatting of your exposure or outcome dataset, or both. Make sure you read / load the data in the format expected by the package. It might also mean you have duplicate SNP-exposures.

bw
Philip
________________________________

**Comment by t0mrg** [comment]
Closing, as this seems to relate to input data format issues
