### ISSUE TITLE
Got different sign of b value when using app.mrbase.org and TwoSampleMR package in R

### ISSUE THREAD

**Issue by amaa11** [MRCIEU/TwoSampleMR#249]
Dear all,

I performed MR using the r package (TwoSampleMR) and app.mrbase.org using same exposure SNPs and GWAS results.
I got same **results** in both way, however the sign values of **b** is different. The negative value using (TwoSampleMR) is positive in app.mrbase, vice versa.
For exapmle:

Using (TwoSampleMR)  in r
1. method	nsnp	b	se	pval
2. MR Egger	12	**0.1848442**	0.1428228	0.2246781
3. Weighted median	12	**0.0336717**	0.0586764	0.5660670
4. Inverse variance weighted	12	**-0.0037240**	0.0459267	0.9353729
5. Simple mode	12	**0.0455526**	0.0733988	0.5474944
6. Weighted mode	12	**0.0369029**	0.0724853	0.6207332

Using app.mrbase.org
1. MR Egger | 12 | **-0.1848** | 0.1428 | 0.2247
2. Weighted median | 12 | **-0.03367** | 0.05634 | 0.55
3. Inverse variance weighted | 12 | **0.003724** | 0.04593 | 0.9354
4. Weighted mode | 12 | **-0.0369** | 0.06904 | 0.6036

You can see the sign of the values are not same.
Any idea what that would be?

Regards

**Comment by mightyphil2000** [comment]
Hi Ahmed

Could you provide the code you used so that we may replicate your issue?

**Comment by amaa11** [comment]
Hi,
Below the code which I run it in jupyter notebook.<br>
import pandas as pd
import numpy as np
%load_ext rpy2.ipython
%%R -i df
 library(Cairo)
library(TwoSampleMR)
%%R -i df
exposure_dat <- read_exposure_data(
 filename = 'tl.txt',
 sep = '\t',
 snp_col = 'SNP',
 beta_col = 'beta',
 se_col = 'se',
 effect_allele_col = 'effect_allele',
 phenotype_col = 'Phenotype',
 units_col = 'units',
 other_allele_col = 'other_allele',
 eaf_col = 'eaf',
 saene_col = 'gene',
 pval_col = 'pval'
)
%%R -i df
outcome_dat <- read_outcome_data(
         filename = "IDP_T1_SIENAX_peripheral_grey_normalised_volume.txt",
         sep = " ",
         snp_col = "SNP",
         beta_col = "beta",
         se_col = "se",
         effect_allele_col = "effect_allele",
         other_allele_col = "other_allele",
         eaf_col = "eaf",
         pval_col = "pval",
         samplesize_col = 'samplesize')
dat <- harmonise_data(exposure_dat, outcome_dat, action=1)
mr_report(dat, study = "A Mendelian randomization")ene_col = 'gene',
 pval_col = 'pval'
)
%%R -i df
outcome_dat <- read_outcome_data(
         filename = "IDP_T1_SIENAX_peripheral_grey_normalised_volume.txt",
         sep = " ",
         snp_col = "SNP",
         beta_col = "beta",
         se_col = "se",
         effect_allele_col = "effect_allele",
         other_allele_col = "other_allele",
         eaf_col = "eaf",
         pval_col = "pval",
         samplesize_col = 'samplesize')
dat <- harmonise_data(exposure_dat, outcome_dat, action=1)
mr_report(dat, study = "A Mendelian randomization")

**Comment by mightyphil2000** [comment]
Thanks Ahmed. Can you also provide instructions on how to replicate the result using  app.mrbase.org

**Comment by amaa11** [comment]
When I use app.mrbase.org, I use **tl.txt** file (I sent it by email) as exposure, PMID: **30305740** as GWAS results (outcome), **peripheral grey normalised volume** as phenotype.

**Comment by mightyphil2000** [comment]
The problem is that the specification of the effect allele columns is different between this file 
IDP_T1_SIENAX_peripheral_grey_normalised_volume.txt
and 
peripheral grey normalised volume in the app. 

So for example, the effect allele for rs11125529 in IDP_T1_SIENAX_peripheral_grey_normalised_volume.txt is allele "C" but in the mrbase app the effect allele is A. 

How did you create the file IDP_T1_SIENAX_peripheral_grey_normalised_volume.txt ? 

I think the most likely explanation is that you have the effect and other alleles the wrong way around in IDP_T1_SIENAX_peripheral_grey_normalised_volume.txt?

**Comment by amaa11** [comment]
Thanks for the explanation. I generated the IDP_T1_SIENAX_peripheral_grey_normalised_volume.txt using the publicly available GWAS result of that study. In the file they published, they mentioned that **REF (C) and ALT (A)** for SNP **rs11125529** .
Does that mean if I change the column name from **effect _allele** to **other_allele**, and **other_allele** to **effect _allele** I will get the same results?

**Comment by mightyphil2000** [comment]
I found this sentence on the study's about page (http://big.stats.ox.ac.uk/about):
"In all studies, the effect allele is the ALT allele."

So yes it looks like you labelled the REF column as effect allele and ALT column as other allele? In this case, yes, if you switch the column names in the outcome text file you should get same results as the web app.

**Comment by amaa11** [comment]
I did a test by changing the column of of effect allele to ALT, and yeah I got same results as the web app.
Thanks so much for you kind help and response.
It helped me a lot and even got more reasonable results

**Comment by mightyphil2000** [comment]
Great glad I could help.
