### ISSUE TITLE
Disconnected from Server repeatedly

### ISSUE THREAD

**Issue by Siva701** [MRCIEU/TwoSampleMR#252]
I appear to be disconnecting from the server everytime I try to run a 2-sameple MR.
At first I thought there was an issue with my connection but I'm reaching out to see if there's an error with the way I'm inputting data? 

Any advice would be appreciated

**Comment by explodecomputer** [comment]
I've been getting this too sometimes. We think sometimes people are making thousands of requests from a cluster. Working on how to throttle this, apologies that it causes inconvenience sometimes
