### ISSUE TITLE
how to calculate the p values and CIs based on t-distribution using twosampleMR in R

### ISSUE THREAD

**Issue by xunxue-zero** [MRCIEU/TwoSampleMR#259]
Hi,
We used the twosampleMR package in R to conduct MR analysis. Because only 4 SNPs were selected as instruments (IVs) in the MR analysis, we believe that the P values and confidence intervals(CIs) should be calculated based on t-distribution for used methods such as MR Egger, Inverse variance weighted regression, etc. However, the default distribution seems to be normal distribution (Z distribution). My question is: how to calculate the p values and CIs based on t-distribution using twosampleMR in R? 
We try to run the following code, but it did not work.

res <- mr(dat, method_list = c("mr_egger_regression", mr_ivw_mre," mr_ivw_fe"), parameters = list(test_dist = "T", nboot = 1000, Cov = 0, penk = 20, phi = 1, alpha = 0.05, Qthresh = 0.05, over.dispersion = TRUE, loss.function = "huber"))

Many thanks!

Leng

**Comment by mightyphil2000** [comment]
Hi there. The P value from MR Egger is calculated using the T distribution by default. The other methods use the Z distribution. My understanding is that this isn't currently a modifiable argument. 

You can calculate the P value using the t distribution using this formula:
2*pt(t,df,lower.tail=FALSE)

where t is beta/se an df is number of SNPs minus number of parameters, which I think is typically 1 (but is 2 in MR-Egger).

**Comment by mightyphil2000** [comment]
By the way some of the mr methods were missing  invert commas and there is a space where there shouldn't be. fixed here:

mr(dat, method_list = c("mr_egger_regression", "mr_ivw_mre", "mr_ivw_fe"))
