### ISSUE TITLE
adding Egger SIMEX to forest plot & scatter plot

### ISSUE THREAD

**Issue by jorient** [MRCIEU/TwoSampleMR#26]
Hi,
I have done some MR analyses in MR base and because the I2 statistic was a bit too low (~0.8) I decided to do MR Egger SIMEX with a separate script, instead of normal MR Egger.  I would now like to include these SIMEX results in both the forest plot & scatter plot. Is there any way I could incorporate that in the below commands? 
Thank you in advance!
Best, Jorien

res_single <- mr_singlesnp(data, all_method = c("mr_ivw", "mr_weighted_median", "mr_egger_regression", "mr_simple_mode", "mr_weighted_mode"))
p1 <- mr_forest_plot(res_single)
p1[[1]]

p1 <- mr_scatter_plot(res_data, data)
p1[[1]]

**Comment by explodecomputer** [comment]
I think this should be possible. For the forest plot you need to add a row to the end of `res_single` that looks like the other global method rows but has the details from the SIMEX analysis.

Similarly for the scatter plot you need to add a row to the `res_data` data frame with the relevant details. The plotting functions should include the new rows automatically

**Comment by jorient** [comment]
Thank you for your reply, I managed to get the SIMEX results in there!

2018-03-27 0:57 GMT+01:00 gibran hemani <notifications@github.com>:
