### ISSUE TITLE
Pardon me, is the MR-Base website repair or has it crashed?

### ISSUE THREAD

**Issue by yemaozi285** [MRCIEU/TwoSampleMR#260]
Hello, gays. nowadays l have met some problems about using MR-Base website. 
  The site didn't respond to my request, some partners try it on different computers and different areas. but the answer is terrible "NO RESPONSE"
  So under the circumstance, l need some person have solved it or can provide a useful message. 
  sincerely

**Comment by t0mrg** [comment]
Thanks for letting us know @yemaozi285. Are you able to access [http://app.mrbase.org/](http://app.mrbase.org/)? This is currently functioning for us.

**Comment by MOMotlagh** [comment]
I had the same problem using the app last week, but at the moment, it seems to function properly.

**Comment by t0mrg** [comment]
Occasionally the server has issues, but is automatically restarted periodically (which might have fixed the issue). If you continue to experience this problem please can you submit a new bug report using the [Bug report template](https://github.com/MRCIEU/TwoSampleMR/issues/new/choose)?
