### ISSUE TITLE
Install the R package in linux

### ISSUE THREAD

**Issue by Cobbybaby** [MRCIEU/TwoSampleMR#261]
Hi
Thank you for yur tool. It is helpful for MR analysis.
I want to install the package in linux （R 4.0.3）, but it does not work after downloading twosamplemr.zip from github.
in window ,R 4.0.3 install it well, but because of website , i can not use install_github(). So is there any way to solve it?
I think this package will be used broader in Linux. 
Look forward to hearing from you!

**Comment by remlapmot** [comment]
TwoSampleMR does install on Linux.

Please follow the installation instructions, i.e.

```r
install.packages("remotes")
remotes::install_github("MRCIEU/TwoSampleMR")
```

Alternatively, if you want a `tar.gz` archive file to install from source (unfortunately the `tar.gz` archive on our Releases page is a little out of date) you could make that yourself by downloading the repo open the RStudio project and then in RStudio go to the Build Pane | Building Source Package. Or I can email you that. Alternatively @explodecomputer could make a GitHub release to put a new `tar.gz` in Releases.

**Comment by explodecomputer** [comment]
thanks @remlapmot, created a new release

**Comment by remlapmot** [comment]
And so if you prefer to install the package from the `.tar.gz` file (instead of the instructions above) download the new one (`TwoSampleMR-0.5.6.tar.gz`) from the Release page [here](https://github.com/MRCIEU/TwoSampleMR/releases/tag/v0.5.6) and with that in your current directory in R run
```r
install.packages("TwoSampleMR-0.5.6.tar.gz", repos = NULL, type="source")
```

**Comment by Cobbybaby** [comment]
Thank you very much!&nbsp;
Have a nice day!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tom ***@***.***&gt;; 
发送时间: 2021年3月25日(星期四) 晚上7:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MRCIEU/TwoSampleMR] Install the R package in linux (#261)





 
And so if you prefer to install the package from the .tar.gz file (instead of the instructions above) download the new one (TwoSampleMR-0.5.6.tar.gz) from the Release page here and with that in your current directory in R run
 install.packages("TwoSampleMR-0.5.6.tar.gz", repos = NULL, type="source")

**Comment by Cobbybaby** [comment]
Hi
Thank you for yor reply.
with your help, I have installed this R package. But I find clumping need to connect the internet (MR-Base).&nbsp; This is a slow process. so can I clump the GWAS data to filter SNPs using PLINK below code:
plink --bfileEUR_keep \
--clump-p1 5e-8 \
--clump-r2 0.05 \
--clump-kb 10000 \
--clump cis_eqtl_harmoni.txt \
--clump-snp-field SNP \
--clump-field p \
--out cis_eQTLGen_clump.txt



What difference between these mehods？








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MRCIEU/TwoSampleMR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月25日(星期四) 晚上7:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MRCIEU/TwoSampleMR] Install the R package in linux (#261)





 
And so if you prefer to install the package from the .tar.gz file (instead of the instructions above) download the new one (TwoSampleMR-0.5.6.tar.gz) from the Release page here and with that in your current directory in R run
 install.packages("TwoSampleMR-0.5.6.tar.gz", repos = NULL, type="source")
