### ISSUE TITLE
clump error

### ISSUE THREAD

**Issue by ad2n15** [MRCIEU/TwoSampleMR#267]
Server code: 503; Server is possibly experiencing traffic, trying again
Server error: 503
Failed to retrieve results from server. See error status message in the returned object and contact the developers if the problem persists.

**Comment by t0mrg** [comment]
Thanks for flagging this issue. The clumping function has recently been receiving a lot of requests (>10,000 per hour), overloading the API (clumping is computationally fairly expensive). Hopefully this has now resolved (load is now lower), but if this issue occurs again please try at a different time of day and/or reduce number of parallel requests.
