### ISSUE TITLE
Disconnected the server

### ISSUE THREAD

**Issue by noeserio** [MRCIEU/TwoSampleMR#268]
When using the mrbase.org website, it leaves the server continuously disconnected when performing an MR run. Recharge.
What is the problem?

**Comment by t0mrg** [comment]
Unfortunately we can't reproduce this error. Occasionally the server has issues, but is automatically restarted periodically (which might have fixed the issue). If you continue to experience this problem please can you submit a new bug report using the [Bug report template](https://github.com/MRCIEU/TwoSampleMR/issues/new/choose)?

**Comment by noeserio** [comment]
I am trying to extract instruments from MRbase but I am being disconnected from the server (see screenshot below) for traits ID ebi-a-GCST005647. Any tips how to fix this?

Thanks,
________________________________
De: Tom Gaunt ***@***.***>
Enviado: miércoles, 5 de mayo de 2021 18:18
Para: MRCIEU/TwoSampleMR ***@***.***>
Cc: noeserio ***@***.***>; Author ***@***.***>
Asunto: Re: [MRCIEU/TwoSampleMR] Disconnected the server (#268)


Unfortunately we can't reproduce this error. Occasionally the server has issues, but is automatically restarted periodically (which might have fixed the issue). If you continue to experience this problem please can you submit a new bug report using the Bug report template<https://github.com/MRCIEU/TwoSampleMR/issues/new/choose>?

**Comment by noeserio** [comment]
I have run some MR analyses a traits:  ebi-a-GCST005647. I now need to re-run some analyses and I am having issues to acces.

I wonder whether they have been removed for any particular reason or whether there may be an issue with the conexion.

Many thanks in advance for your help.

Best wishes
________________________________
De: Tom Gaunt ***@***.***>
Enviado: miércoles, 5 de mayo de 2021 18:18
Para: MRCIEU/TwoSampleMR ***@***.***>
Cc: noeserio ***@***.***>; Author ***@***.***>
Asunto: Re: [MRCIEU/TwoSampleMR] Disconnected the server (#268)


Unfortunately we can't reproduce this error. Occasionally the server has issues, but is automatically restarted periodically (which might have fixed the issue). If you continue to experience this problem please can you submit a new bug report using the Bug report template<https://github.com/MRCIEU/TwoSampleMR/issues/new/choose>?
