### ISSUE TITLE
Inconsistency in extracted number of SNPs from MRbase now and back in August 2020 

### ISSUE THREAD

**Issue by nabilakazmi** [MRCIEU/TwoSampleMR#277]
I ran some MR analyses using TwoSampleMR and MRInstruments packages on 28-08-2020. My outcome datasets were overall and advanced prostate cancer of PRACTICAL consortium which I extracted from MR-Base using above mentioned R packages. 

Today, I repeated the analyses (14-06-2021) and saw that I got more SNPs in my outcome datasets compared to my previous analyses. Does anyone know what could have been updated that made this impact? Thank you.

**Comment by mightyphil2000** [comment]
Hi Nabila 

The way that LD clumping is done has recently been updated and I suspect that may be the reason you are getting different numbers of SNPs. Although I am a bit surprised you are getting more SNPs. Could you share an example script and IDs for the exposure and outcome traits involved ?

**Comment by nabilakazmi** [comment]
Hi Philip, 

Thank you for your reply.

Below is the Rcode that I used and "CU.txt" file is attached.
[CU.txt](https://github.com/MRCIEU/TwoSampleMR/files/6654925/CU.txt). Could it be possible that the PC dataset has been modified somehow, I noticed that the alleles are flipped to what I have before? 

To let you know, the outcome id I used before was 1174 and now it is ieu-b-85.

   pathname <- paste("Exposures/CU.txt",sep="")
  exposure_dat <- read_exposure_data(pathname,sep=" ")
   exposure <- clump_data(exposure_dat,clump_r2 = 0.01, clump_kb=10000)
   outcome_dat <- extract_outcome_data(exposure$SNP,"ieu-b-85" ) # In previous analyses, the outcome id was"1174" 

Thank you for your help.

**Comment by mightyphil2000** [comment]
Thanks Nabila

Just to clarify, has the number of SNPs in the clumped exposure / instrument changed (the "exposure" object in your code)? Or is it only the number of SNPs in the outcome dataset that has changed (outcome_dat above)? 

I think the explanation may be that we reformatted the prostate cancer dataset and re-uploaded it to Open GWAS. I noticed the reformatted dataset had more SNPs than the previous version.

**Comment by nabilakazmi** [comment]
Thank you very much Philip.

The number of SNPs in the outcome dataset are changed not in the exposure. Yes, reformatting could be a possible explanation. 
I also noticed that some snps have been reported twice in advanced PC outcome. Their summary stats are exactly the same but  alleles are different. I am not sure which one to keep.

**Comment by mightyphil2000** [comment]
Hi Nabila
Could you send an example? Are they exactly the same even with regards to the effect size, standard error and eaf? They could be tri-allelic SNPs. You could confirm in dbSNP.

**Comment by nabilakazmi** [comment]
Yes, you are right. They are tri-allelic snps. I just confirmed at dbSNP. 
Thank you indeed for your help. All is sorted now.

**Comment by mightyphil2000** [comment]
Great!
