### ISSUE TITLE
Apparent error in documentation: implying `> TwoSampleMR::chd_out_dat()`?

### ISSUE THREAD

**Issue by hdraisma** [MRCIEU/TwoSampleMR#287]
Hi -- [Extracting particular SNPs from particular studies](https://mrcieu.github.io/TwoSampleMR/articles/outcome.html#extracting-particular-snps-from-particular-studies) reads:

> ... `chd_out_dat(c("rs234", "rs17097147"), c('ieu-a-2', 'ieu-a-7'))` ...

..., however `> `[`TwoSampleMR::`]`chd_out_dat()` doesn't exist.

Thanks

**Comment by remlapmot** [comment]
Thanks for the great spot. That line of code should be

``` r
chd_out_dat <- extract_outcome_data(c("rs234", "rs17097147"), c('ieu-a-2', 'ieu-a-7'))
```

I will try to update the vignette and website in due course.
