### ISSUE TITLE
{Cairo} not listed as TwoSampleMR::mr_report() dependency

### ISSUE THREAD

**Issue by hdraisma** [MRCIEU/TwoSampleMR#290]
Hello,

When using the `> TwoSampleMR::mr_report()` function, in my case the output HTML files contain the following code/(R error message):

`<body>`
`<pre><code>## Error in library(Cairo): there is no package called &#39;Cairo&#39;`
`</code></pre>`

This dependency is listed neither in [perform_mr.html#reports-1](https://mrcieu.github.io/TwoSampleMR/articles/perform_mr.html#reports-1) nor in the package's DESCRIPTION file.

Cheers

`> sessionInfo()`
`R version 4.0.5 (2021-03-31)`
`Platform: x86_64-w64-mingw32/x64 (64-bit)`
`Running under: Windows 10 x64 (build 19043)`

`Matrix products: default`

`locale:`
`[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           `
`[5] LC_TIME=English_United Kingdom.1252    `

`attached base packages:`
`[1] stats     graphics  grDevices datasets  utils     methods   base     `

`other attached packages:`
`[1] knitr_1.33          TwoSampleMR_0.5.6   MRInstruments_0.3.2`

`loaded via a namespace (and not attached):`
` [1] Rcpp_1.0.7        lattice_0.20-41   prettyunits_1.1.1 ps_1.6.0          digest_0.6.27     glmnet_4.1-2      rprojroot_2.0.2   psych_2.1.6      `
` [9] foreach_1.5.1     utf8_1.2.1        mime_0.11         R6_2.5.0          plyr_1.8.6        mr.raps_0.2       evaluate_0.14     highr_0.9        `
`[17] httr_1.4.2        ggplot2_3.3.5     pillar_1.6.1      rlang_0.4.11      curl_4.3.2        rstudioapi_0.13   callr_3.7.0       Matrix_1.3-2     `
`[25] labeling_0.4.2    desc_1.3.0        devtools_2.4.2    splines_4.0.5     stringr_1.4.0     munsell_0.5.0     tinytex_0.32      compiler_4.0.5   `
`[33] xfun_0.24         pkgconfig_2.0.3   mnormt_2.0.2      pkgbuild_1.2.0    tmvnsim_1.0-2     shape_1.4.6       ieugwasr_0.1.5    tidyselect_1.1.1 `
`[41] tibble_3.1.2      codetools_0.2-18  fansi_0.5.0       crayon_1.4.1      dplyr_1.0.7       withr_2.4.2       grid_4.0.5        nlme_3.1-152     `
`[49] jsonlite_1.7.2    gtable_0.3.0      lifecycle_1.0.0   magrittr_2.0.1    scales_1.1.1      stringi_1.6.2     cli_3.0.1         cachem_1.0.5     `
`[57] farver_2.1.0      renv_0.14.0       fs_1.5.0          remotes_2.4.0     testthat_3.0.4    ellipsis_0.3.2    generics_0.1.0    vctrs_0.3.8      `
`[65] nortest_1.0-4     iterators_1.0.13  tools_4.0.5       glue_1.4.2        markdown_1.1      purrr_0.3.4       parallel_4.0.5    processx_3.5.2   `
`[73] pkgload_1.2.1     fastmap_1.1.0     survival_3.2-10   colorspace_2.0-2  sessioninfo_1.1.1 memoise_2.0.0     usethis_2.0.1`

**Comment by remlapmot** [comment]
Thanks for this. I have added Cairo to the Imports list, so this should be fixed.
