### ISSUE TITLE
harmonise_data Error

### ISSUE THREAD

**Issue by ileenamitra** [MRCIEU/TwoSampleMR#3]
Hi, 

When using the harmonise_data(exposure_dat, outcome_dat, action = 2) function, I'm getting the following error: 
Error in !remove : invalid argument type

It seems this error arises when the outcome_dat has an effect_allele.outcome character variable longer than length 1 (e.g. "ATC" instead of "A".) For example, when using the outcome data from "Parents' age at death". I was able to work around by filtering out SNPs with the outcome_dat$effect_allele.outcome length greater than 1.

**Comment by mightyphil2000** [comment]
Hi Ileena

Thanks for letting us know. Could you send the rsid of the SNP? Is it an indel?

At the moment the package only caters to SNPs.

Gib, do you want to add anything?

bw
Philip

On 17 January 2017 at 01:43, Ileena Mitra <notifications@github.com> wrote:
> Hi,
>
> When using the harmonise_data(exposure_dat, outcome_dat, action = 2)
> function, I'm getting the following error:
> Error in !remove : invalid argument type
>
> It seems this error arises when the outcome_dat has an effect_allele.outcome
> character variable longer than length 1 (e.g. "ATC" instead of "A".) For
> example, when using the outcome data from "Parents' age at death". I was
> able to work around by filtering out SNPs with the
> outcome_dat$effect_allele.outcome length greater than 1.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Philip Haycock, PhD
CRUK Population Research Fellow
MRC Integrative Epidemiology Unit
University of Bristol
Oakfield House, Oakfield Grove
Bristol, BS8 2BN, UK
T +44 (0)117 3310088

**Comment by explodecomputer** [comment]
Thanks very much for letting us know about this, will get round to fixing
it asap.




On 24 January 2017 at 10:56:03, mightyphil2000 (notifications@github.com)
wrote:

Hi Ileena

Thanks for letting us know. Could you send the rsid of the SNP? Is it an
indel?

At the moment the package only caters to SNPs.

Gib, do you want to add anything?

bw
Philip

On 17 January 2017 at 01:43, Ileena Mitra <notifications@github.com> wrote:
> Hi,
>
> When using the harmonise_data(exposure_dat, outcome_dat, action = 2)
> function, I'm getting the following error:
> Error in !remove : invalid argument type
>
> It seems this error arises when the outcome_dat has an
effect_allele.outcome
> character variable longer than length 1 (e.g. "ATC" instead of "A".) For
> example, when using the outcome data from "Parents' age at death". I was
> able to work around by filtering out SNPs with the
> outcome_dat$effect_allele.outcome length greater than 1.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



--
Philip Haycock, PhD
CRUK Population Research Fellow
MRC Integrative Epidemiology Unit
University of Bristol
Oakfield House, Oakfield Grove
Bristol, BS8 2BN, UK
T +44 (0)117 3310088

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/MRCIEU/TwoSampleMR/issues/3#issuecomment-274771479>,
or mute
the thread

**Comment by olegkagan** [comment]
Hi,

I am having the same issue, although my outcome_dat$effect_allele_outcome is fine...I don't have indel.

I am trying to harmonise mQTLs with multiple exposure (CpGs) and encountered the same error


```
> data<-harmonise_data(exposure_dat = T1D_mQTL_expo_clump,outcome_dat = outcome_data)
Harmonising cg05844871 (00BKjF) and outcome (agKGBh)
Harmonising cg19455396 (07fn40) and outcome (agKGBh)
Harmonising cg10104420 (0C93X6) and outcome (agKGBh)
Harmonising cg04906816 (0dEAJK) and outcome (agKGBh)
Harmonising cg09945482 (0DmaEl) and outcome (agKGBh)
Harmonising cg10180404 (0LpcaT) and outcome (agKGBh)
Harmonising cg13076785 (0t7F6i) and outcome (agKGBh)
Harmonising cg00389036 (0wN0GK) and outcome (agKGBh)
Error in !remove : invalid argument type
```

however, the package seems to work fine with multiple instruments against single exposure. Can anyone help?

**Comment by explodecomputer** [comment]
would you be able to send us the data so we can try to solve it? e.g.

```
e <- subset(T1D_mQTL_expo_clump, id.exposure == "0wN0GK")
o <- subset(outcome, SNP %in% e$SNP)
save(e, o, file="problem_data.rdata")
```

**Comment by olegkagan** [comment]
Ok, problem is solved now. It looks like in the outcome_data the effect_allele.outcome cannot be NA. 

harmonise_data works if I filter out outcome_data i.e.

`outcome_data1<-subset(outcome_data,mr_keep.outcome=='TRUE')`

cheers

**Comment by jjandshi** [comment]
A problem came out when run harmonise_data, with an error "Error in fix.by(by.x, x) : 'by' must specify a uniquely valid column". Could you please take a look at it. Two files are attached.

Thanks!



[MRBase_Outcome_format_BC.txt](https://github.com/MRCIEU/TwoSampleMR/files/1163723/MRBase_Outcome_format_BC.txt)
[MRBase_exposure_format_SCZ.txt](https://github.com/MRCIEU/TwoSampleMR/files/1163724/MRBase_exposure_format_SCZ.txt)

**Comment by lacarv** [comment]
I also have the same problem as jjandshi. A problem came out when run harmonise_data, with an error "Error in fix.by(by.x, x) : 'by' must specify a uniquely valid column". Could you please take a look at it. Two files are attached.

Although both my files have a unique specified column named SNP to be able to match between them.

Thanks!

**Comment by dana-stack** [comment]
Hi, 

Did anyone figure out why "Error in fix.by(by.x, x) : 'by' must specify a uniquely valid column" comes up with harmonise_data even with a unique specified column of 'SNP'?

**Comment by explodecomputer** [comment]
@dana-stack @jjandshi @lacarv - I think this happens when the required columns are not present - e.g. in the attached example files the id.exposure and id.outcome columns were absent. I've added a check for this in the harmonise_data function, see if it helps, if not let me know and we'll try to figure out the issue
