### ISSUE TITLE
[BUG]: installation error for Windows WSL Ubuntu

### ISSUE THREAD

**Issue by jielab** [MRCIEU/TwoSampleMR#301]
Hi, there:

Please see the screenshot below, I could not install TwoSampleMR into my Ubuntu Linux that comes with Windows.
<img width="518" alt="326538f2244fefff22abc1d9f63fa1e" src="https://user-images.githubusercontent.com/26947455/132499301-618b9e30-054d-40c9-b79d-2e9aff83374a.png">

I use R 4.1.1, for both Windows and Windows WSL. I had no problem to install TwoSampleMR into Windows R version.

BTW, the TwoSampleMR package calls the MendelianRandomization R package, correct?  I was able to successfully install the MendelianRandomization R package for both Windows and WSL.

Best regards,
Jie

**Comment by remlapmot** [comment]
Sorry but this is not a problem with our repo and it's not a bug. It is a problem with either your WSL installation or your own network.

I can't tell from that screenshot why the download failed. If you have hit your GitHub download rate limit I think there's usually information to that effect in the error message. If that is the problem it's worth setting up a GitHub personal access token to be allowed more downloads see instructions [here](https://happygitwithr.com/credential-caching.html) which talks about using the
``` r
usethis::create_github_token()
```
function to set one up.
