### ISSUE TITLE
ERROR: dependency ‘MendelianRandomization’ is not available for package ‘TwoSampleMR

### ISSUE THREAD

**Issue by zillurbmb51** [MRCIEU/TwoSampleMR#314]
Hi, I was trying to install this package but failed. I tried in many ways but no luck. I am using ubuntu20.04. Here is the error message:
Any help?
`> remotes::install_github("MRCIEU/TwoSampleMR")
Downloading GitHub repo MRCIEU/TwoSampleMR@HEAD
Installing 4 packages: arrangements, gmp, iterpc, MendelianRandomization
Installing packages into ‘/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/arrangements_1.1.9.tar.gz'
Content type 'application/x-gzip' length 44334 bytes (43 KB)
==================================================
downloaded 43 KB

trying URL 'https://cloud.r-project.org/src/contrib/gmp_0.6-2.tar.gz'
Content type 'application/x-gzip' length 161933 bytes (158 KB)
==================================================
downloaded 158 KB

trying URL 'https://cloud.r-project.org/src/contrib/iterpc_0.4.2.tar.gz'
Content type 'application/x-gzip' length 10967 bytes (10 KB)
==================================================
downloaded 10 KB

trying URL 'https://cloud.r-project.org/src/contrib/MendelianRandomization_0.5.1.tar.gz'
Content type 'application/x-gzip' length 952843 bytes (930 KB)
==================================================
downloaded 930 KB

* installing *source* package ‘gmp’ ...
** package ‘gmp’ successfully unpacked and MD5 sums checked
** using staged installation
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -std=gnu++11 accepts -g... yes
checking for __gmpz_ui_sub in -lgmp... no
configure: error: GNU MP not found, or not 4.1.4 or up, see http://gmplib.org
ERROR: configuration failed for package ‘gmp’
* removing ‘/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.6/gmp’
ERROR: dependency ‘gmp’ is not available for package ‘arrangements’
* removing ‘/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.6/arrangements’
ERROR: dependencies ‘gmp’, ‘arrangements’ are not available for package ‘iterpc’
* removing ‘/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.6/iterpc’
ERROR: dependency ‘iterpc’ is not available for package ‘MendelianRandomization’
* removing ‘/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.6/MendelianRandomization’

The downloaded source packages are in
	‘/tmp/RtmpdXRElx/downloaded_packages’
✓  checking for file ‘/tmp/RtmpdXRElx/remotes5c62476736b2/MRCIEU-TwoSampleMR-2bb4947/DESCRIPTION’ (783ms)
─  preparing ‘TwoSampleMR’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts (362ms)
─  checking for empty or unneeded directories
─  building ‘TwoSampleMR_0.5.6.tar.gz’
   
Installing package into ‘/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
ERROR: dependency ‘MendelianRandomization’ is not available for package ‘TwoSampleMR’
* removing ‘/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.6/TwoSampleMR’
Warning messages:
1: In i.p(...) : installation of package ‘gmp’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘arrangements’ had non-zero exit status
3: In i.p(...) : installation of package ‘iterpc’ had non-zero exit status
4: In i.p(...) :
  installation of package ‘MendelianRandomization’ had non-zero exit status
5: In i.p(...) :
  installation of package ‘/tmp/RtmpdXRElx/file5c622ae2d379/TwoSampleMR_0.5.6.tar.gz’ had non-zero exit status`

**Comment by llalluan** [comment]
> The issue is resolved. I had to install `gmp` `sudo apt install libgmp-dev`.

Hi, I came across the same issue, and I tried to install the 'gmp', but failed. Can I ask how you installed the 'gmp'? Looking forward to your reply, Thanks!
