### ISSUE TITLE
Json error when using clump_data

### ISSUE THREAD

**Issue by ksiewert** [MRCIEU/TwoSampleMR#33]
Hello,

I am trying to use the clump_data function to clump exposure data I loaded from our own GWAS. However, I get this error when I do so: 

Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML PUBLIC "-//IETF/
                     (right here) ------^

To try to debug, I passed clump_data different subsets of rows, but it's unpredictable what subsets of the data it has this error on. For instance, there's some rows that won't cause an error when they're given to clump_data in a data frame with other SNPs, but if I just give that SNP to clump_data, I get this error.

Thank you,
Katie

**Comment by sc16685** [comment]
I've been getting the same error today when trying to clump exposure data:

> melanoma_exposure_data <- clump_data(melanoma_exposure_data, clump_r2 = 0.1)
Clumping 7qHxyS, 49 SNPs
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML PUBLIC "-//W3C//
                     (right here) ------^

Thanks
Sarah

**Comment by explodecomputer** [comment]
Hi thanks for letting me know @sc16685 @ksiewert . We've been experiencing very heavy traffic which has led to some timeout issues, and we are in the process of migrating to bigger servers. But if there is something else happening I can take a look, are you able to share the SNP list with me and I can try to investigate

**Comment by ksiewert** [comment]
Hi explode computer. That sounds like it it could definitely be causing the issues we're seeing. Congratulations on the success of mrbase though! Sounds like the paper generated a ton of interest.

**Comment by sc16685** [comment]
[Melanoma 5E-8 GWAS_CorrectEAF.txt](https://github.com/MRCIEU/TwoSampleMR/files/2140627/Melanoma.5E-8.GWAS_CorrectEAF.txt)

This in the SNP file I am trying to use - it's be working fine for months. 

Still not having any success 

Thanks
Sarah

**Comment by ksiewert** [comment]
Yeah, I'm still encountering server issues too.

**Comment by explodecomputer** [comment]
Hey @sc16685 apologies for the delay, thanks for sending the file. It looks like there are some empty lines at the end of the file

```
a <- read.table("~/Downloads/Melanoma.5E-8.GWAS_CorrectEAF.txt", he=T, sep="\t")
```

The `read_exposure_data` function was trying to parse that into SNPs, and the clumping was failing because of that. I have made an update to the R package to guard against this but I think just removing empty lines from the file would fix it.

**Comment by valborgg** [comment]
Hey, I am having the same issue:

> instruments_clumped <- clump_data(tmp)
Warning: since v0.4.2 the default r2 value for clumping has changed from 0.01 to 0.001
Clumping 2vlSQM, 22 SNPs
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML PUBLIC "-//W3C//
                     (right here) ------^

I made the instruments dataframe with the "format_data" command so it should not be due to any empty lines.

thanks,
Valborg

**Comment by valborgg** [comment]
Hi, @explodecomputer , I see this issue thread is closed but I'm still experiencing the same problem. Do you have a potential solution for me to try to get this command to work?

**Comment by shuheimiyasaka** [comment]
I'm also having an issue with when trying to use my own GWAS data for the exposure.

`Warning: since v0.4.2 the default r2 value for clumping has changed from 0.01 to 0.001
Clumping LWQr8P, 3 SNPs
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML PUBLIC "-//W3C//
                     (right here) ------^`

Data I'm using is here (no empty lines): 
https://drive.google.com/open?id=1RLpk6hpr8YJ46N-xE8ETlVZePAA4j6jH

**Comment by ruthtopless** [comment]
I am having the same issue as shuheimiyasaka. I just updated the TwoSampleMR package and get "Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML PUBLIC "-//W3C//
           (right here) ------^"  When trying to clump SNPs.

**Comment by explodecomputer** [comment]
hi @ruthtopless @shuheimiyasaka apologies for the delay, I have been away the last few days. I think there was an issue with the API which has now been fixed, apologies for the inconvenience but hopefully it's working as normal now

**Comment by DanaiChas** [comment]
I have the same problem with clump_data().

I get the error: Error: lexical error: invalid char in json text.
<!DOCTYPE HTML PUBLIC "-//W3C//
(right here) ------^" 

My data set is a data frame of this type:
 chr_name      SNP        chrom_start   Allele1    Allele2   pval.exposure    
      12        rs1000824     9064374        G          A         2.908e-05 

Where the p-value is numerical.

When I run the command:  clump_data(data.input, clump_kb = 500, clump_r2=0.2) 
I have no problems.

The error appears when I try to determine the p1 and p2 p-value thresholds:
clump_data(data.input, clump_kb = 500, clump_r2=0.2,
                               clump_p1=0.0001, clump_p2=0.01) 

Any ideas about the issue?
Thanks

**Comment by bethleegy** [comment]
Hello,

I am currently having the same issue. I currently have 21 SNPs to be clumped, but if I increase the number of SNPs by relaxing the p-value criterion, it has no problems. Could you point me to some direction to fix this issue? 

Thank you very much.

**Comment by explodecomputer** [comment]
Hi @bethleegy would you be able to send me the list of SNPs and p-values, so that I can try to reproduce the problem?

**Comment by bethleegy** [comment]
Hi, 

I have emailed you. Would you prefer if I share it here? Thank you very much.

**Comment by explodecomputer** [comment]
Hey @bethleegy thanks for sending me the example data. Unfortunately the issue is that all the SNPs are very low frequency, whereas the reference panel only includes maf > 0.01 in europeans in 1kg. So, that's why it's not working. We're working on releasing a new version that will have more informative error messages

**Comment by kgiperez** [comment]
Same issue here.

[snps.Rdata.zip](https://github.com/MRCIEU/TwoSampleMR/files/3975835/snps.Rdata.zip)

**Comment by Dhihram** [comment]
> outcome_data <- extract_outcome_data(
+   snps = exposure_data$SNP, outcomes = "UKB-a:360")
Extracting data for 62 SNP(s) from 1 GWAS(s)
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML PUBLIC "-//W3C//
                     (right here) ------^ same issue

**Comment by Sii3-HAn** [comment]
I had a similar problem with data analysis.Would you please share the way to sovle this problem?

**Comment by Sii3-HAn** [comment]
I had a similar problem with data analysis.Would you please share the way to sovle this problem?
I have the same problem with clump_data().
