### ISSUE TITLE
[BUG] Harmonise_LD_Dat not exporting properly

### ISSUE THREAD

**Issue by pl92297** [MRCIEU/TwoSampleMR#341]
Hello, 

I am finding that harmonise_ld_dat function is not being exported properly, and I cannot call it properly. This is true for both the master and 0.5.6.

` >TwoSampleMR::harmonise_ld_dat`
`Error: 'harmonise_ld_dat' is not an exported object from 'namespace:TwoSampleMR'`

Some help would be appreciated. Thanks!

**Comment by remlapmot** [comment]
This function is exported properly, you can see it in the `NAMESPACE` file [here](https://github.com/MRCIEU/TwoSampleMR/blob/2bb494719a0d4eef8f66e15eac42ba61bb5d3603/NAMESPACE#L43)

And `getNamespaceExports()` shows it in the list of exported functions.

``` r
remotes::install_github("MRCIEU/TwoSampleMR", force = TRUE, quiet = TRUE)
"harmonise_ld_dat" %in% getNamespaceExports("TwoSampleMR")
#> [1] TRUE
```

<sup>Created on 2022-03-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

So I recommend checking which version of the package you had installed when you saw the error.

**Comment by pl92297** [comment]
Yes, I can see that it is in the NAMESPACE file, and I checked the function definition in other_formats.R. 

Perhaps this is an issue specific to a docker container with TwoSampleMR? The docker container linked here (mrcieu/twosamplemr) loads v 0.5.5, which I confirmed gives me the result below. I've also tried creating my own docker container with the 0.5.6 branch, and it still does not export properly. For what it's worth, I seem to be able to export all other functions, including functions in other_formats. R (e.g. run_mr_presso).

'"harmonise_ld_dat" %in% getNamespaceExports("TwoSampleMR")'
'[1] FALSE'

**Comment by remlapmot** [comment]
Ok, that's an old version of the package and that container needs updating.

You should be able to access the function with R's triple colon syntax (which accesses unexported functions in packages), i.e.

```r
TwoSampleMR:::harmonise_ld_dat()
```
