### ISSUE TITLE
An R package runs incorrectly.

### ISSUE THREAD

**Issue by jf19971028** [MRCIEU/TwoSampleMR#344]
An R package runs incorrectly.

> ao <-available_outcomes(access_token=NULL)
Error in available_outcomes(access_token = NULL) : 
  could not find function "available_outcomes"
> write.csv(ao,'pheno_info.csv',row.names=F）
Error: unexpected input in "write.csv(ao,'pheno_info.csv',row.names=F）"
>

**Comment by remlapmot** [comment]
Remember you need to load the package with `library(TwoSampleMR)` before running that code, i.e.

Install the package with
```r
install.packages("remotes")
remotes::install_github("MRCIEU/TwoSampleMR")
```

Then load it with
```r
library(TwoSampleMR)
```

Then run your code.
