### ISSUE TITLE
available outcomes: spelling mistake for "population" European -> Europrean

### ISSUE THREAD

**Issue by ewtobi** [MRCIEU/TwoSampleMR#38]
Dear maintainers,

ao <- available_outcomes()

In the field "population" over 500 studies with N>10,000  the population European is denoted as Europrean.
Might lead to some people missing studies of interest while prunning the GWAS data to those of European decent. 

Best wishes

p.s. nice job on this package, kudos all around

**Comment by elswob** [comment]
Thanks for pointing that out. Fixed now.

**Comment by ewtobi** [comment]
glad I could help.

I also noticed that not all 'id' fields numerics, some also contain the name of the biobank (UKB-a or UKB-b)

**Comment by elswob** [comment]
Yes, that one is intentional :) The id fields are strings, which can contain integers and characters, for reasons related to the underlying database

**Comment by ewtobi** [comment]
thanks for the info..

A related question; I am using the R package, but also try to use the SNP look-up because I like the search function of the web app above using R string queries (having trouble finding several waist-to-hip and impedance GWAS studies otherwise). Anyhow , I keep getting disconnected of the web app "disconnected from the server" it says after about 30 seconds...are their useage limits set for user accounts?

**Comment by mightyphil2000** [comment]
Btw you can also use the TwoSampleMR R package for snp lookups. You don't have to use the web app.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by ewtobi** [comment]
thanks
