### ISSUE TITLE
Inconsistency with GWAS catalog data and data obtained using extract_intruments()

### ISSUE THREAD

**Issue by RashSar** [MRCIEU/TwoSampleMR#395]
Hi,
I'm using Triglycerides data from multiple studies individually, and obtaining IVs using the extract_intruments() function.
I noticed for a particular study (ebi-a-GCST000758), the data obtained from this function is different from the original paper. If the same study is queried through MRInstruments gwas_catalog, the data is different (this is consistent with the original paper).

Here's an example:
Data from extract_intruments() - 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/c289647/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/c289647/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<div data-col=1 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=2 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=3 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=4 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=5 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=6 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=7 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=8 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=9 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=10 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=11 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=12 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=13 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=14 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=15 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=16 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=17 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=18 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'>

<div data-col=19 style='cursor:ew-resize'></div>

</div>

</div>

</div>

</div>

<div style='font-variant-ligatures: normal;font-variant-caps: normal;
orphans: 2;text-align:start;widows: 2;-webkit-text-stroke-width: 0px;
text-decoration-thickness: initial;text-decoration-style: initial;text-decoration-color: initial'>

<div style='overflow:hidden;margin-right:0px;padding-bottom:0px;padding-top:
0px'>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=0 style='cursor:ew-resize'></div>

</div>

</div>

<body link="#0563C1" vlink="#954F72">

<div style='background-position:initial !important;background-size: initial !important;
background-repeat:initial !important;background-attachment:initial !important;
background-origin: initial !important;background-clip: initial !important;
font-variant-ligatures: normal;font-variant-caps: normal;orphans: 2;text-align:
start;widows: 2;-webkit-text-stroke-width: 0px;text-decoration-thickness: initial;
text-decoration-style: initial;text-decoration-color: initial'>

beta | p | se | position | n | chr | id | rsid | ea | nea
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
-0.0665 | 8.83E-43 | 0.005 | 63025942 | 96598 | 1 | ebi-a-GCST000758 | rs2131925 | T | G

</body>

</html>

Data from gwas_catalog:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/c289647/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/c289647/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<div data-col=1 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=2 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=3 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=4 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=5 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=6 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=7 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=8 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=9 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=10 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=11 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=12 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=13 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=14 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=15 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=16 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=17 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=18 style='cursor:ew-resize'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'>

<div data-col=19 style='cursor:ew-resize'></div>

</div>

</div>

</div>

</div>

<div style='font-variant-ligatures: normal;font-variant-caps: normal;
orphans: 2;text-align:start;widows: 2;-webkit-text-stroke-width: 0px;
text-decoration-thickness: initial;text-decoration-style: initial;text-decoration-color: initial'>

<div style='overflow:hidden;margin-right:0px;padding-bottom:0px;padding-top:
0px'>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=0 style='cursor:ew-resize'></div>

</div>

</div>

<div style='background-position:initial !important;background-size: initial !important;
background-repeat:initial !important;background-attachment:initial !important;
background-origin: initial !important;background-clip: initial !important;
font-variant-ligatures: normal;font-variant-caps: normal;orphans: 2;text-align:
start;widows: 2;-webkit-text-stroke-width: 0px;text-decoration-thickness: initial;
text-decoration-style: initial;text-decoration-color: initial'>

<div style='box-sizing: content-box'>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'>

<div data-col=1 style='cursor:ew-resize'></div>

</div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'>

<div data-col=2 style='cursor:ew-resize'></div>

</div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'>

<div data-col=3 style='cursor:ew-resize'></div>

</div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'>

<div data-col=4 style='cursor:ew-resize'></div>

</div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'>

<div data-col=5 style='cursor:ew-resize'></div>

</div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'>

<div data-col=6 style='cursor:ew-resize'></div>

</div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'>

<div data-col=7 style='cursor:ew-resize'></div>

</div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'>

<div data-col=8 style='cursor:ew-resize'></div>

</div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'>

<div data-col=9 style='cursor:ew-resize'></div>

</div>

</div>

<div style='overflow:hidden;margin-right:0px;padding-bottom:0px;padding-top:
0px'>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=11 style='cursor:ew-resize'></div>

</div>

</div>

<div style='overflow:hidden;margin-right:0px;padding-bottom:0px;padding-top:
0px'>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=12 style='cursor:ew-resize'></div>

</div>

</div>

<div style='overflow:hidden;margin-right:0px;padding-bottom:0px;padding-top:
0px'>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=13 style='cursor:ew-resize'></div>

</div>

</div>

<div style='overflow:hidden;margin-right:0px;padding-bottom:0px;padding-top:
0px'>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=14 style='cursor:ew-resize'></div>

</div>

</div>

<div style='overflow:hidden;margin-right:0px;padding-bottom:0px;padding-top:
0px'>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=15 style='cursor:ew-resize'></div>

</div>

</div>

<div style='overflow:hidden;margin-right:0px;padding-bottom:0px;padding-top:
0px'>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=16 style='cursor:ew-resize'></div>

</div>

</div>

<div style='overflow:hidden;margin-right:0px;padding-bottom:0px;padding-top:
0px'>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=17 style='cursor:ew-resize'></div>

</div>

</div>

<div style='overflow:hidden;margin-right:0px;padding-bottom:0px;padding-top:
0px'>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=18 style='cursor:ew-resize'></div>

</div>

</div>

<div style='overflow:hidden;margin-right:0px;padding-bottom:0px;padding-top:
0px'>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=19 style='cursor:ew-resize'></div>

</div>

</div>

<div title=1 style='max-width:300px'></div>

<div title=-0.0665 style='max-width:300px'></div>

<div title=8.83487e-43 style='text-overflow: ellipsis'></div>

<div title=0.0050 style='max-width:300px'></div>

<div title=63025942 style='max-width:300px'></div>

<div title=96598 style='max-width:300px'></div>

<div title=1 style='max-width:300px'></div>

<div title=ebi-a-GCST000758 style='text-overflow: ellipsis'></div>

<div title=rs2131925 style='max-width:300px'></div>

<div title=T style='max-width:300px'></div>

<div title=G style='max-width:300px'></div>

</div>

<div style='background-position:initial !important;background-size: initial !important;
background-repeat:initial !important;background-attachment:initial !important;
background-origin: initial !important;background-clip: initial !important;
font-variant-ligatures: normal;font-variant-caps: normal;orphans: 2;text-align:
start;widows: 2;-webkit-text-stroke-width: 0px;text-decoration-thickness: initial;
text-decoration-style: initial;text-decoration-color: initial'>

<div style='box-sizing: content-box'>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=12 style='cursor:ew-resize'></div>

</div>

<div style='border-radius: 3px'>

<div style='text-overflow: ellipsis;box-sizing: border-box'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

</div>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'>

<div data-col=25 style='cursor:ew-resize'></div>

</div>

</div>

<div data-col=13 style='cursor:ew-resize'></div>

</div>

<div style='border-radius: 3px;min-width: 35px'>

<div style='margin-right:10px'></div>

<div data-col=14 style='cursor:ew-resize'></div>

</div>

<div style='border-radius: 3px;min-width: 35px'>

<div style='margin-right:10px'></div>

<div data-col=15 style='cursor:ew-resize'></div>

</div>

<div style='border-radius: 3px;min-width: 35px'>

<div style='margin-right:10px'></div>

<div data-col=16 style='cursor:ew-resize'></div>

</div>

<div style='border-radius: 3px;min-width: 35px'>

<div style='margin-right:10px'></div>

<div data-col=17 style='cursor:ew-resize'></div>

</div>

<div style='border-radius: 3px;min-width: 35px'>

<div style='margin-right:10px'></div>

<div data-col=18 style='cursor:ew-resize'></div>

</div>

<div style='border-radius: 3px;min-width: 35px'>

<div style='margin-right:10px'></div>

<div data-col=19 style='cursor:ew-resize'></div>

</div>

<div style='border-radius: 3px;min-width: 35px'>

<div style='margin-right:10px'></div>

<div data-col=20 style='cursor:ew-resize'></div>

</div>

<div style='border-radius: 3px;min-width: 35px'>

<div style='margin-right:10px'></div>

<div data-col=21 style='cursor:ew-resize'></div>

</div>

<div style='border-radius: 3px;min-width: 35px'>

<div style='margin-right:10px'></div>

<div data-col=22 style='cursor:ew-resize'></div>

</div>

<div style='border-radius: 3px;min-width: 35px'>

<div style='margin-right:10px'></div>

<div data-col=23 style='cursor:ew-resize'></div>

</div>

<div style='border-radius: 3px;min-width: 35px'>

<div style='margin-right:10px'></div>

<div data-col=24 style='cursor:ew-resize'></div>

</div>

<div style='border-radius: 3px;min-width: 35px'>

<div style='margin-right:10px'></div>

</div>

</div>

<div style='font-variant-ligatures: normal;font-variant-caps: normal;
orphans: 2;text-align:start;widows: 2;-webkit-text-stroke-width: 0px;
text-decoration-thickness: initial;text-decoration-style: initial;text-decoration-color: initial'>

<div style='overflow:hidden;margin-right:0px;padding-bottom:0px;padding-top:
0px'>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=0 style='cursor:ew-resize'></div>

</div>

</div>

<div style='overflow:hidden;margin-right:0px;padding-bottom:0px;padding-top:
0px'>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=1 style='cursor:ew-resize'></div>

</div>

<div style='border-radius: 3px;min-width: 35px'>

<div style='margin-right:10px'></div>

</div>

</div>

<div style='overflow:hidden;margin-right:0px;padding-bottom:0px;padding-top:
0px'>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=2 style='cursor:ew-resize'></div>

</div>

<div style='border-radius: 3px;min-width: 35px'>

<div style='margin-right:10px'></div>

</div>

</div>

<div style='overflow:hidden;margin-right:0px;padding-bottom:0px;padding-top:
0px'>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=3 style='cursor:ew-resize'></div>

</div>

<div style='border-radius: 3px;min-width: 35px'>

<div style='margin-right:10px'></div>

</div>

</div>

<div style='overflow:hidden;margin-right:0px;padding-bottom:0px;padding-top:
0px'>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=4 style='cursor:ew-resize'></div>

</div>

<div style='border-radius: 3px;min-width: 35px'>

<div style='margin-right:10px'></div>

</div>

</div>

<div style='overflow:hidden;margin-right:0px;padding-bottom:0px;padding-top:
0px'>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=5 style='cursor:ew-resize'></div>

</div>

<div style='border-radius: 3px;min-width: 35px'>

<div style='margin-right:10px'></div>

</div>

</div>

<div style='overflow:hidden;margin-right:0px;padding-bottom:0px;padding-top:
0px'>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=6 style='cursor:ew-resize'></div>

</div>

<div style='border-radius: 3px;min-width: 35px'>

<div style='margin-right:10px'></div>

</div>

</div>

<div style='overflow:hidden;margin-right:0px;padding-bottom:0px;padding-top:
0px'>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=7 style='cursor:ew-resize'></div>

</div>

<div style='border-radius: 3px;min-width: 35px'>

<div style='margin-right:10px'></div>

</div>

</div>

<div style='overflow:hidden;margin-right:0px;padding-bottom:0px;padding-top:
0px'>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=8 style='cursor:ew-resize'></div>

</div>

<div style='border-radius: 3px;min-width: 35px'>

<div style='margin-right:10px'></div>

</div>

</div>

<div style='overflow:hidden;margin-right:0px;padding-bottom:0px;padding-top:
0px'>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=9 style='cursor:ew-resize'></div>

</div>

<div style='border-radius: 3px;min-width: 35px'>

<div style='margin-right:10px'></div>

</div>

</div>

<div style='overflow:hidden;margin-right:0px;padding-bottom:0px;padding-top:
0px'>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=10 style='cursor:ew-resize'></div>

</div>

<div style='border-radius: 3px;min-width: 35px'>

<div style='margin-right:10px'></div>

</div>

</div>

<div style='overflow:hidden;margin-right:0px;padding-bottom:0px;padding-top:
0px'>

<div style='margin-right:10px;position:relative'>

<div style='margin-right:10px'></div>

<div data-col=11 style='cursor:ew-resize'></div>

</div>

<div style='border-radius: 3px;min-width: 35px'>

<div style='margin-right:10px'></div>

</div>

</div>

<body link="#0563C1" vlink="#954F72">

SNP | chr | bp_ens_GRCh38 | Region | gene | Gene_ens | effect_allele | other_allele | beta | se | pval | units
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
rs2131925 | 1 | 62560271 | 1p31.3 | DOCK7 |   | G | T | -4.94 | 0.397959 | 9.00E-43 | mg/dL decreas

</body>

</html>

The effect sizes are very different, for the same study. And not what one might expect from a simple flipping of alt/ref alleles.
Here's the same data from original paper ( which is consistent with gwas_catalog)
![image](https://user-images.githubusercontent.com/122258968/220558941-a71fc8c6-ec32-44f3-930a-9f57792c33d8.png)

I compared gwas_catalog output with extract_instruments() output for a couple of other studies, and they have no issues (other than alt/ref allele switch).

Can anyone identify what might be going wrong here, and how to fix it?

**Comment by mightyphil2000** [comment]
Hi RashSar

Could you also lookup rs2131925 in the dataset here? http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST000001-GCST001000/GCST000758/

ebi-a-GCST000758 in Open GWAS was downloaded from the above ftp site. Can you check if the effect size is also different in that dataset? I suspect that the problem may lie there. If the OpenGWAS dataset is the same as the dataset at the above FTP site, then we need to contact the GWAS catalog to understand what is going on. 

In addition to the very different betas, it also looks like the effect is in opposite directions.

**Comment by RashSar** [comment]
Thanks for you response!

http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST000001-GCST001000/GCST000758/TG_with_Effect.zip

This file has the same effect size as what is fetched from IEU GWAS data using extract_instruments() function. Only the direction is opposite. Allele1 is T, Allele 2 is G. I'm assuming the effect size is for Allele2?

**Comment by mightyphil2000** [comment]
It's unclear whether allele1 or allele2 is the effect allele. Is there any metadata at the ftp link that clarifies this? It could be that the modelled effect alleles are different (e.g. T in IEU GWAS and G in the ftp site), in which case there is no conflict between the ftp site and the IEU GWAS. 

What's more worrying is that the effect size is very different between the IEU GWAS/FTP site on the one hand and the manually curated top hits (i.e. in your table labelled "Data from gwas_catalog" above). 

Could you contact the GWAS catalog about this issue? The ftp site is managed by them and that's ultimately where the discrepancy is coming from. Please could you let us know what they say? Happy to be Cc'd. philip.haycock@bristol.ac.uk

 thanks!

**Comment by RashSar** [comment]
Yes, you're right. The alleles are flipped in the ftp data, which explains the difference in direction.

I will contact GWAS catalog regarding the issue and loop you in.

Thank you!

**Comment by RashSar** [comment]
After clarification from GWAS Catalog and Philip, here's a summary of the issue:

The data available via GWAS Catalog is for top associations that are curated directly from the publication.
Data at the ftp site is obtained directly from the authors.

In this case, the difference in effect sizes between these two datasets is due to difference in units. Data from ftp site has effect size estimates in standard deviation units. While the effect size in the paper (same as GWAS catalog) is in mg/dL.

Direction of effect is also consistent between GWAS catalog and ftp site. (reported with respect to the minor allele G in the paper, hence its a negative effect. Whereas effect allele is T in ftp site, which has positive effect.)

MRC-IEU data also mentions T as effect allele,  but with a negative effect. This flip in direction might to be due an effect allele coding error in the MRC-IEU database.

**Comment by mightyphil2000** [comment]
Thanks RashSar 

I checked the dataset and it indeed looks like the effect allele is wrong in ebi-a-GCST000758 in Open GWAS. We will remove this dataset. I used the package CheckSumStats to confirm. 96% of known GWAS hits for triglycerides had effect sizes in the opposite to expected direction. 

```
library(CheckSumStats)
ao<-ieugwasr::gwasinfo()
id="ebi-a-GCST000758"
trait<-ao$trait[ao$id == id]
gwas_catalog<-gwas_catalog_hits(efo=NULL,efo_id=NULL,trait=trait,map_association_to_study=FALSE)
out<- ieugwasr::associations(id=id, variants=snplist,proxies=0)
out<-format_data(dat=out,trait=trait,rsid="rsid",effect_allele="ea",other_allele="nea",beta="beta",se="se",eaf="eaf",p="p")
gc_dat<-compare_effect_to_gwascatalog2(dat=out,efo_id=efo,trait=trait,map_association_to_study=FALSE,gwas_catalog=gwas_catalog)
gc_dat[gc_dat$rsid=="rs2131925",]
gc_conflicts<-flag_gc_conflicts2(gc_dat=gc_dat) 
gc_conflicts
$effect_size_conflicts
$effect_size_conflicts$`high conflict`
[1] 457

$effect_size_conflicts$`moderate conflict`
[1] 252

$effect_size_conflicts$`no conflict`
[1] 28

$effect_size_conflicts$n_snps
[1] 737
```
