### ISSUE TITLE
Need to download full summary statistics in a genomic region

### ISSUE THREAD

**Issue by mocksu** [MRCIEU/TwoSampleMR#396]
**Please make sure that this is a feature request! If you have questions about how to use TwoSampleMR please use the [Discussions](https://github.com/MRCIEU/TwoSampleMR/discussions) function instead.**

## Describe the feature you would like to see (required)
I need to do colocalization analysis, which requires full summary statistics of a genomic region. If I use "extract_instruments" with clump=FALSE, then the function call is aborted due to time out. It would be nice to be able to extract SNPs from a genomic region and without clumping.

## Describe the importance of this feature to your research (required)
As I said above, colocalization analysis needs all SNPs in the region without clumping.

## Describe the anticipated value of this feature to the wider research community (required)
GWAS data can be very helpful for other purposes than just 2sMR, and TwoSampleMR seems to have all the GWAS readily available.

## Contribute a solution (optional)
Maybe just add chromosome, start position, end position to "extract_instruments(..)"

If you are willing to contribute to the development of this feature, please submit a pull request and/or briefly describe your proposed solution

**Comment by mightyphil2000** [comment]
ieugwasr has this functionality https://github.com/MRCIEU/ieugwasr

**Comment by mocksu** [comment]
> ieugwasr has this functionality https://github.com/MRCIEU/ieugwasr

Wonderful! However, I can't find anywhere (including the link you provided) the user manual. It does not even have a vignette in R.

Thanks so much!

**Comment by mightyphil2000** [comment]
The link to the vignette is at the bottom of the page. 
https://mrcieu.github.io/ieugwasr/

**Comment by mightyphil2000** [comment]
Also https://mrcieu.github.io/ieugwasr/articles/guide.html

**Comment by mocksu** [comment]
Thanks, it worked!
