### ISSUE TITLE
Server code: 502; Server is possibly experiencing traffic, trying again...

### ISSUE THREAD

**Issue by ETHANSHAW** [MRCIEU/TwoSampleMR#422]
again and again...

**Comment by Lin-zikai** [comment]
me too

**Comment by woerheidej** [comment]
I have the same problem!!

**Comment by supertae** [comment]
Does anyone know how to solve it?

**Comment by l0ums** [comment]
Same here  - have been getting this issue occasionally over the last couple weeks, but today I haven't had any successful retries at all - only getting 502 error codes. A bug or lots of bulk requests from big labs? Anything I can do locally to work around? 

> ieugwasr::api_status()
Server code: 502; Server is possibly experiencing traffic, trying again...
Server code: 502; Server is possibly experiencing traffic, trying again...
Server code: 502; Server is possibly experiencing traffic, trying again...
Server code: 502; Server is possibly experiencing traffic, trying again...
Server code: 502; Server is possibly experiencing traffic, trying again...
Server code: 502; Server is possibly experiencing traffic, trying again...
Server error: 502
Failed to retrieve results from server. See error status message in the returned object and contact the developers if the problem persists.
$url
[1] "http://gwas-api.mrcieu.ac.uk/status"

$status_code
[1] 502

$headers
$date
[1] "Mon, 03 Jul 2023 19:25:49 GMT"

$server
[1] "nginx/1.15.8"

$`x-frame-options`
[1] "DENY, DENY"

$`content-type`
[1] "text/html; charset=UTF-8"

$`content-length`
[1] "157"

attr(,"class")
[1] "insensitive" "list"

**Comment by zhoushican** [comment]
me too. How to fix it?

**Comment by jamesjin63** [comment]
me too. either

**Comment by mzon7** [comment]
Anyone make any progress on this? Also causing me some issues. Might try reverting to an older build

**Comment by QY-Dong** [comment]
mine too. ends with
Server error: 502
Failed to retrieve results from server. See error status message in the returned object and contact the developers if the problem persists.
Error in if (nrow(d) == 0) return(NULL) : argument is of length zero

**Comment by neurologyliu** [comment]
QAQ

**Comment by mzon7** [comment]
I sort of fixed the issue. There's a guide online from them about running locally instead of from the server. Take a look at that and follow the instructions and you should be fine. You may need to copy the clumping function of two sample mr package and then replace the clumping function it uses from ieugwasr with the local version. Here's a link with some info 

https://mrcieu.github.io/ieugwasr/articles/local_ld.html

**Comment by explodecomputer** [comment]
Hi all this error arises when the server is under a huge amount of load. We've managed to identify several sources who appeared to be running jobs in parallel to perform queries against the API which was drastically slowing things down. 

If you need to run a lot of queries please do just download the VCF files and query against those. It will run much faster for you, and it allows everyone else to keep using the resource.

In future we will probably need to implement some sort of authentication to avoid this type of behaviour, but we'll consult with users before making final decisions on how to implement that.

**Comment by zhouyyyyanling** [comment]
how to deal?
