### ISSUE TITLE
LOCAL LD CLUMP, LD MATRIX not running - cant open connection to AFR.bed - cant redownload 1kg.v3

### ISSUE THREAD

**Issue by JonnyBaseball** [MRCIEU/TwoSampleMR#427]
**Please make sure that this is a bug! If you have questions about how to use TwoSampleMR please use the [Discussions](https://github.com/MRCIEU/TwoSampleMR/discussions) function instead.**

NOT RUNNING LOCAL LD CLUMPING OR LD MATRIX: HERE IS THE ERROR.  PATH IS CORRECT. ALSO TRIED TO DOWNLOAD AGAIN THE 1kg.v3 (AT RUNNING LOCAL LD OPERATIONS) BUT WOULD NOT DOWNLOAD.  

HERE IS MY CODE:
dat0 <- ieugwasr::ld_clump_local(dat=dat02, # variant, pval, id - won't work with SNP, pval.exposure or id.exposure
  	clump_kb=10000,
  	clump_r2=0.001,
  	clump_p=1, #
  	plink_bin = genetics.binaRies::get_plink_binary(),
  	bfile = "~/Desktop/1kg.v3/AFR"
  	)

HERE IS MY ERROR:

Error: Failed to open ~/Desktop/1kg.v3/EAS.bed.
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
 

## System information MACBOOK PRO - MAC 0S CATALINA version 10.15.7, R version 4.2.0

*Please provide details of your operating system and R version*

## Additional context

*Add any other context about the problem here*

**Comment by fabianacz** [comment]
I have the same issue here 

I am trying to perform clumping using the 1000 genomes as reference dataset.
I been experiencing the following error

To get the same LD reference dataset that is used by the API, you can download it directly from here: http://fileserve.mrcieu.ac.uk/ld/1kg.v3.tgz

To get a path to plink you can do the following:

devtools::install_github("explodecomputer/genetics.binaRies")
plink <- genetics.binaRies::get_plink_binary()

Using plink **
orru_clump <- ld_clump(
dplyr::tibble(rsid = summaryset_orru$rsid, pval = summaryset_orru$p, id = summaryset_orru$id),
plink_bin = "plink",
bfile = "1kg.v3" # This is the same directory as my R project

)

Clumping ebi-a-GCST90001942, 15141982 variants, using EUR population reference PLINK v1.90b7 64-bit (16 Jan 2023) [www.cog-genomics.org/plink/1.9/](http://www.cog-genomics.org/plink/1.9/) (C) 2005-2023 Shaun Purcell, Christopher Chang GNU General Public License v3 Logging to C:\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file3930d7a4440.log. Options in effect: --bfile 1kg.v3 --clump C:\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file3930d7a4440 --clump-kb 10000 --clump-p1 0.99 --clump-r2 0.001 --out C:\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file3930d7a4440 65210 MB RAM detected; reserving 32605 MB for main workspace. Error: Failed to open 1kg.v3.bed. Error in file(file, "rt") : cannot open the connection In addition: Warning message: In file(file, "rt") : cannot open file 'C:\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file3930d7a4440.clumped': No such file or directory

** Using plink2 **

plink2 <- "C:/Users/corsfmdg/Desktop/R/R_ME" # I have put plink.exe in the same directory as my R project

orru_clump <- ld_clump(
dplyr::tibble(rsid=summaryset_orru$rsid, pval=summaryset_orru$p, id=summaryset_orru$id),
plink_bin = "plink2",
bfile = "1kg.v3"
)

Clumping ebi-a-GCST90001942, 15141982 variants, using EUR population reference Error in file(file, "rt") : cannot open the connection In addition: Warning message: In file(file, "rt") : cannot open file 'C:\Users\corsfmdg\AppData\Local\Temp\Rtmp63D8xl\file39303fa538bf.clumped': No such file or directory

any suggestions how to sort that?
