### ISSUE TITLE
localize the functionality of "extract_instruments," "extract_outcome_data," "harmonise_data," and "mr."

### ISSUE THREAD

**Issue by yaya6630170** [MRCIEU/TwoSampleMR#438]
The issue I'm currently facing is that I have a large dataset, and I need to perform calculations on a scale of 40,000 by 40,000. This would result in significant computation time due to the need to make API calls each time. Therefore, I'm considering localizing the TwoSampleMR functionality that I require. The API interfaces I'm using are "extract_instruments," "extract_outcome_data," "harmonise_data," and "mr." Can you provide me with some assistance?
I‘ll give some data, i think the data is right.
![1](https://github.com/MRCIEU/TwoSampleMR/assets/72657813/8a0637f0-4190-4be7-aedb-42ec4bea9751)

**Comment by remlapmot** [comment]
Closing because this seems to be identical to the previous issue you opened.
