### ISSUE TITLE
[BUG]: Server code: 502; Server is possibly experiencing traffic, trying again...

### ISSUE THREAD

**Issue by LivNordestgaard** [MRCIEU/TwoSampleMR#448]
**Please make sure that this is a bug! If you have questions about how to use TwoSampleMR please use the [Discussions](https://github.com/MRCIEU/TwoSampleMR/discussions) function instead.**

## Describe the bug (required)

When I try to extract instruments from the Open GWAS I get an error message (See code block below).
I use the code example from the introduction to Two Sample MR here on GitHub.  

*Provide a clear and concise description of what the bug is*

The problem is that I can't extract instruments from Open GWAS.

## Describe the current behaviour you observe (required)

*Include code blocks with any error messages*

"Server code: 502; Server is possibly experiencing traffic, trying again..."
"Failed to retrieve results from server. See error status message in the returned object and contact the developers if the problem persists.
Error in if (nrow(d) == 0) return(NULL) : argument is of length zero"

## Describe the behaviour you expect (required)

I would expect that I would be able to extract instruments from Open GWAS.

## R code to reproduce the issue (required)

library(TwoSampleMR)
exposure_dat <- extract_instruments("ieu-a-2")

*Please provide a minimal code snippet that will reproduce this issue*

library(TwoSampleMR)
exposure_dat <- extract_instruments("ieu-a-2")

## Contribute a solution (optional)

Please submit a pull request and/or briefly describe your proposed solution

## System information

*Please provide details of your operating system and R version*

I'm using Windows and R version 4.2.2 (2022-10-31 ucrt)

## Additional context

*Add any other context about the problem here*

**Comment by ketzelehs** [comment]
FYI, I've been encountering a similar problem. I'm encountering these issues on bothy my work cluster and my personal laptop with the following:

R version 4.2.3 (2023-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.1 LTS

R version 4.3.1 (2023-06-16)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.0

**Comment by Julie1130** [comment]
I'm encountering 
Error in if (nrow(d) == 0) return(NULL) : argument is of length zero
from this afternoon, anyone knows what happened?

**Comment by xuxutiantian** [comment]
> I'm encountering Error in if (nrow(d) == 0) return(NULL) : argument is of length zero from this afternoon, anyone knows what happened?

the ieu gwas website is broken down

**Comment by xiaoyong2499** [comment]
hhh, I'm encountering the same problem on this afternoon :Error in if (nrow(d) == 0) return(NULL) : argument is of length zero,
I am so stranged for this morning it worked very well.
until I saw [xuxutiantian]'s answer...
so funny

**Comment by xiaoyong2499** [comment]
hhh, I'm encountering the same problem this afternoon :Error in if (nrow(d) == 0) return(NULL) : argument is of length zero,
I am so stranged for this morning it worked very well.
until I saw [xuxutiantian]'s answer...
so funny

**Comment by EEchoes** [comment]
I was looking this issue and now I understand. hh

**Comment by xiaoyong2499** [comment]
Hoping this website get fixed soon...发自我的手机-------- 原始邮件 --------发件人： EEchoes ***@***.***>日期： 2024年3月23日周六 晚上10:47收件人： MRCIEU/TwoSampleMR ***@***.***>抄送： xiaoyong2499 ***@***.***>, Comment ***@***.***>主    题： Re: [MRCIEU/TwoSampleMR] [BUG]: Server code: 502; Server is possibly experiencing traffic, trying again... (Issue #448)
I was looking this issue and now I understand. hh

**Comment by PengXue99** [comment]
Now I am still encountering this probem Error in if (nrow(d) == 0) return(NULL) : argument is of length zero.

**Comment by xiaoyong2499** [comment]
It seems the website fixed, it can be navigated, however, we are still encountering this probem Error in if (nrow(d) == 0) return(NULL) : argument is of length zero.

**Comment by wantaccept** [comment]
> I'm encountering Error in if (nrow(d) == 0) return(NULL) : argument is of length zero from this afternoon, anyone knows what happened?

me too, have you solved this problem now

**Comment by zichunwu21** [comment]
> > I'm encountering Error in if (nrow(d) == 0) return(NULL) : argument is of length zero from this afternoon, anyone knows what happened?
> 
> me too, have you solved this problem now

Hi, I am encountering this error sadly, have you solved this problem?

**Comment by remlapmot** [comment]
Please update your TwoSampleMR and ieugwasr packages - you can use the following command to do this.

```r
install.packages("TwoSampleMR", repos = c("https://mrcieu.r-universe.dev", "https://cran.r-project.org"))
```

Then you need to obtain an OPENGWAS_JWT token - see the ieugwasr documentation https://mrcieu.github.io/ieugwasr/articles/guide.html - and store it in your .Renviron file - then restart R.

**Comment by zichunwu21** [comment]
> Please update your TwoSampleMR and ieugwasr packages - you can use the following command to do this.
> 
> ```r
> install.packages("TwoSampleMR", repos = c("https://mrcieu.r-universe.dev", "https://cran.r-project.org"))
> ```
> 
> Then you need to obtain an OPENGWAS_JWT token - see the ieugwasr documentation https://mrcieu.github.io/ieugwasr/articles/guide.html - and store it in your .Renviron file - then restart R.

Thanks for your help, it worked well and I have a valid api status now.

But I still have some trouble and it goes like this:

I can extract instrumental variables from dataset 'ieu-a-2' using code below:
`exp_dat <- extract_instruments(outcomes = 'ieu-a-2')`
But it is strange that I can not extract IVs from dataset 'ukb-b-7372' using code below:
`exp_dat <- extract_instruments(outcomes = 'ukb-b-7372')`
Error occurs as below:
`Error in if (out == "[]") { : argument is of length zero`

I don't know why this happens.T_T

**Comment by meimei117** [comment]
想請問要如何找到 .Renviron 檔案呢? 已參閱 :https://mrcieu.github.io/ieugwasr/articles/guide.html且獲得token，再R的資料集中只找到 "Rcmd_environ"這個檔案，路徑為"C:\Program Files\R\R-4.4.0\etc"

**Comment by Manojbioinfo** [comment]
Facing same issues :(
