### ISSUE TITLE
[BUG]: Why I can't access the gwas-api.mrcieu.ac.uk? 502 Bad Gateway

### ISSUE THREAD

**Issue by docase** [MRCIEU/TwoSampleMR#452]
**Please make sure that this is a bug! If you have questions about how to use TwoSampleMR please use the [Discussions](https://github.com/MRCIEU/TwoSampleMR/discussions) function instead.**

## Describe the bug (required)

*Provide a clear and concise description of what the bug is*

## Describe the current behaviour you observe (required)

*Include code blocks with any error messages*

## R code to reproduce the issue (required)

*Please provide a minimal code snippet that will reproduce this issue*

## Contribute a solution (optional)

Please submit a pull request and/or briefly describe your proposed solution

## System information

*Please provide details of your operating system and R version*

## Additional context

*Add any other context about the problem here*

**Comment by Real-thinker** [comment]
> library(VariantAnnotation)
> library(gwasglue)
> library(TwoSampleMR)
> 
> exposureFile="exposure.F.csv"         
> outcomeID="ebi-a-GCST90018917"      
> outcomeName="Systemic lupus erythematosus"      
> setwd("D:/Systemic lupus erythematosus")     
> #read exposure data
> exposure_dat=read_exposure_data(filename=exposureFile,
+                                 sep = ",",
+                                 snp_col = "SNP",
+                                 beta_col = "beta.exposure",
+                                 se_col = "se.exposure",
+                                 pval_col = "pval.exposure",
+                                 effect_allele_col="effect_allele.exposure",
+                                 other_allele_col = "other_allele.exposure",
+                                 eaf_col = "eaf.exposure",
+                                 phenotype_col = "exposure",
+                                 id_col = "id.exposure",
+                                 samplesize_col = "samplesize.exposure",
+                                 chr_col="chr.exposure", pos_col = "pos.exposure",
+                                 clump=FALSE)
> 
> #Read the outcome data.
> outcomeData=extract_outcome_data(snps=exposure_dat$SNP, outcomes=outcomeID)
Extracting data for 17939 SNP(s) from 1 GWAS(s)
1 of 1 outcomes
 [>] 1 of 2 chunks
 [>] 2 of 2 chunks
Finding proxies for 17939 SNPs in outcome ebi-a-GCST90018917
Extracting data for 17939 SNP(s) from 1 GWAS(s)
1 of 1 outcomes
 [>] 1 of 36 chunks
 [>] 2 of 36 chunks
 [>] 3 of 36 chunks
 [>] 4 of 36 chunks
 [>] 5 of 36 chunks
 [>] 6 of 36 chunks
 [>] 7 of 36 chunks
 [>] 8 of 36 chunks
 [>] 9 of 36 chunks
 [>] 10 of 36 chunks
 [>] 11 of 36 chunks
 [>] 12 of 36 chunks
 [>] 13 of 36 chunks
 [>] 14 of 36 chunks
 [>] 15 of 36 chunks
 [>] 16 of 36 chunks
 [>] 17 of 36 chunks
 [>] 18 of 36 chunks
 [>] 19 of 36 chunks
 [>] 20 of 36 chunks
 [>] 21 of 36 chunks
 [>] 22 of 36 chunks
 [>] 23 of 36 chunks
 [>] 24 of 36 chunks
 [>] 25 of 36 chunks
 [>] 26 of 36 chunks
 [>] 27 of 36 chunks
 [>] 28 of 36 chunks
 [>] 29 of 36 chunks
 [>] 30 of 36 chunks
 [>] 31 of 36 chunks
 [>] 32 of 36 chunks
 [>] 33 of 36 chunks
 [>] 34 of 36 chunks
 [>] 35 of 36 chunks
 [>] 36 of 36 chunks
> write.csv(outcomeData, file="outcome.csv", row.names=F)
> 
> #Combining exposure and outcome data
> outcomeData$outcome=outcomeName
> dat=harmonise_data(exposure_dat, outcomeData)
error is check_required_columns(outcome_dat, "outcome"): 
  The following required columns are missing from outcome: SNP, id.outcome, beta.outcome, se.outcome, effect_allele.outcome, other_allele.outcome
  
I have installed the TwoSampleMR and gwasglue packages, but the "outcome.csv" file stays empty and I'm confused as to why I can't access the GWAS website.
