### ISSUE TITLE
help for an error

### ISSUE THREAD

**Issue by SaraJavidnia** [MRCIEU/TwoSampleMR#454]
**Please make sure that this is a feature request! If you have questions about how to use TwoSampleMR please use the [Discussions](https://github.com/MRCIEU/TwoSampleMR/discussions) function instead.**

## Describe the feature you would like to see (required)

*Provide a clear and concise description*

## Contribute a solution (optional)

If you are willing to contribute to the development of this feature, please submit a pull request and/or briefly describe your proposed solution

**Comment by SaraJavidnia** [comment]
Hello , I encountered this error while running MR for some of my files including one or two SNPs: 

No phenotype name specified, defaulting to 'outcome'.
Error in `[[<-.data.frame`(`*tmp*`, type, value = "outcome") : 
  replacement has 1 row, data has 0

Can anyone help me to solve this issue?Thanks!

**Comment by SaraJavidnia** [comment]
> God, I have this problem too. Can somebody else help us?

Hello, I couldn't find a proper answer from anyone. Then, I thought maybe the error occurs because there are no similar SNPs in the outcome file. So, I checked the outcome file and searched for one or two SNPs from my exposure. I found out they are not available in the outcome, so maybe the error is due to this!

**Comment by mightyphil2000** [comment]
Yes this error is most likely due to not having any SNPs common to the exposure and outcome datasets
