### ISSUE TITLE
Outcome ID problem:  UKB switched Ids

### ISSUE THREAD

**Issue by jonnyrose** [MRCIEU/TwoSampleMR#46]
In the mrbase.org library (GWAS), 

UKB-b:5779 yesterday was outcome (copying from R studio): 

Alcohol intake frequency. || id:UKB-b:5779

Today it is: Treatment/medication code: gtn 300micrograms sublingual tablet || id:UKB-b:5779  

Was Alcohol Intake overwritten?  Was Alcohol Intake pulled for some reason?  Whom should I contact about the error or deletion?

Thanks.

**Comment by explodecomputer** [comment]
Thanks for alerting us to this @jonnyrose 
The IDs beginning with `UKB-b:` changed for approximately 24 hours and they have now changed back to how they were (i.e. alcohol intake frequency is back to 5779). Sorry for the trouble this may have caused. In the future it is possible that these IDs will change but we'll give adequate warning and a way to map back to old IDs.

**Comment by jonnyrose** [comment]
Thanks for your prompt reply! Best wishes to you all for the holidays!
