### ISSUE TITLE
Provide docker recipe file in the repo

### ISSUE THREAD

**Issue by samwalrus** [MRCIEU/TwoSampleMR#467]
**Please make sure that this is a feature request! If you have questions about how to use TwoSampleMR please use the [Discussions](https://github.com/MRCIEU/TwoSampleMR/discussions) function instead.**

## Describe the feature you would like to see (required)

Please provide or link to the docker recipe file that is used to build the docker image on docker hub.

*Provide a clear and concise description*

## Describe the importance of this feature to your research (required)

This allows people to easily inspect and modify the docker image.

## Describe the anticipated value of this feature to the wider research community (required)

Will ease building new docker images that have the tool as a component. 

## Contribute a solution (optional)

If you are willing to contribute to the development of this feature, please submit a pull request and/or briefly describe your proposed solution

**Comment by remlapmot** [comment]
The repo is accidentally private.

The dockerfile is currently

```dockerfile
FROM rocker/r-ver:latest
WORKDIR /usr/local/src/myscripts
RUN apt-get update && \
    apt-get install -yyy \
        build-essential \
        libcurl4-gnutls-dev \
        libxml2-dev \
        libssl-dev \
        libgmp3-dev \
        cmake \
        libcairo2-dev \
        libxt-dev \
        libharfbuzz-dev \
        libtiff-dev

# Wait until MRCIEU R-Universe has built latest version of the TwoSampleMR binary
# Should be 1 hour or maybe overnight
# Check https://mrcieu.r-universe.dev/TwoSampleMR
# I set the HTTPUserAgent option in order to obtain binary packages from the
# Public Posit Package Manager (otherwise source packages which will have to 
# be built will be obtained).

RUN R -e 'options( \
    repos = c(universe = "https://mrcieu.r-universe.dev/bin/linux/jammy/4.3/", \
        CRAN = "https://packagemanager.posit.co/cran/__linux__/jammy/latest"), \
    HTTPUserAgent = sprintf( \
        "R/%s R (%s)", \
        getRversion(), \
        paste(getRversion(), \
          R.version["platform"], \
          R.version["arch"], \
          R.version["os"]))); \
    install.packages("TwoSampleMR", dependencies = TRUE)'
```

@t0mrg could you make the MRCIEU/docker_twosamplemr repo public, as I don't think that I have enough permissions on that repo.

**Comment by t0mrg** [comment]
@samwalrus @remlapmot - MRCIEU/docker_twosamplemr now public
