### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by zjralkc** [MRCIEU/TwoSampleMR#484]
**Please make sure that this is a bug! If you have questions about how to use TwoSampleMR please use the [Discussions](https://github.com/MRCIEU/TwoSampleMR/discussions) function instead.**

## Describe the bug (required)

*Provide a clear and concise description of what the bug is*

## Describe the current behaviour you observe (required)

*Include code blocks with any error messages*

## R code to reproduce the issue (required)

*Please provide a minimal code snippet that will reproduce this issue*

## Contribute a solution (optional)

Please submit a pull request and/or briefly describe your proposed solution

## System information

*Please provide details of your operating system and R version*

## Additional context

*Add any other context about the problem here*

**Comment by zjralkc** [comment]
when I install the twosampleMR failed in ubuntu. and the system is out of memory .
the error message:
../inst/include/Eigen/src/Core/Matrix.h:225:24:   required from ‘Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>& Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::operator=(const Eigen::DenseBase<OtherDerived>&) [with OtherDerived = Eigen::Product<Eigen::Product<Eigen::Product<Eigen::Matrix<double, -1, -1>, Eigen::Transpose<const Eigen::Matrix<double, -1, -1> >, 0>, Eigen::Transpose<const Eigen::Map<Eigen::Matrix<double, -1, -1>, 0, Eigen::Stride<0, 0> > >, 0>, Eigen::Map<Eigen::Matrix<double, -1, 1>, 0, Eigen::Stride<0, 0> >, 0>; _Scalar = double; int _Rows = -1; int _Cols = 1; int _Options = 0; int _MaxRows = -1; int _MaxCols = 1]’

**Comment by remlapmot** [comment]
Please be more careful. 

A dependency package has failed to install on your system, and hence this is not a bug in the TwoSampleMR package - but rather on your system and how you configure it.

To avoid building packages from source you can obtain binary R packages for Linux using our mrcieu.r-universe and the Posit Public Package Manager as follows.

### Installation code obtaining binary packages on Ubuntu Linux running R through RStudio Desktop or RStudio Server

```r
# Installation code for Ubuntu Jammy Jellyfish users in RStudio Desktop or Server
install.packages(
  'TwoSampleMR',
  repos = c(
    'https://mrcieu.r-universe.dev/bin/linux/jammy/4.3/',
    'https://packagemanager.posit.co/cran/__linux__/jammy/latest',
    'https://cloud.r-project.org'
  )
)
```

### Installation code obtaining binary packages on Ubuntu Linux running R in the Terminal

```r
# Installation code for Ubuntu Jammy Jellyfish users running R in the Terminal
options(HTTPUserAgent = sprintf(
  "R/%s R (%s)",
  getRversion(),
  paste(getRversion(),
        R.version["platform"],
        R.version["arch"],
        R.version["os"])
))

install.packages(
  'TwoSampleMR',
  repos = c(
    'https://mrcieu.r-universe.dev/bin/linux/jammy/4.3/',
    'https://packagemanager.posit.co/cran/__linux__/jammy/latest',
    'https://cloud.r-project.org'
  )
)
```
