### ISSUE TITLE
[BUG]: Using linewidth for a discrete variable is not advised.

### ISSUE THREAD

**Issue by Jinyuze666** [MRCIEU/TwoSampleMR#488]
When conducting two-sample Mendelian randomization analysis, the forest plots and leave-one-out sensitivity analysis generate images with unusually thick lines, as shown in the provided pictures. How can this issue be resolved? Thank you.

Code warning messages:
1: Advised against using linewidth for discrete variables.
![图片1](https://github.com/MRCIEU/TwoSampleMR/assets/162892331/4d5f4096-d829-4bbf-874b-e9fe109aae30)
![图片2](https://github.com/MRCIEU/TwoSampleMR/assets/162892331/f294103c-0129-4883-ad37-61b71cce9187)

**Comment by remlapmot** [comment]
Thanks for this. This was caused by an incomplete fix to a ggplot2 deprecation last week. There were 2 rogue function calls we forgot to update.

So this should be fixed if you update TwoSampleMR

```r
remotes::install_github("MRCIEU/TwoSampleMR")
```
