### ISSUE TITLE
[BUG]: IEU OPEN GWAS PROJECT has been updated and this package didn't work properly.

### ISSUE THREAD

**Issue by docZ9** [MRCIEU/TwoSampleMR#492]
**Please make sure that this is a bug! If you have questions about how to use TwoSampleMR please use the [Discussions](https://github.com/MRCIEU/TwoSampleMR/discussions) function instead.**

## Describe the bug (required)

IEU OPEN GWAS PROJECT has been updated and API changes have caused this package to not work properly.

## Describe the current behaviour you observe (required)

An error occurred while extracting the SNP from the IEU：Error in if (nrow(d) == 0) return(NULL) : 参数长度为零

## Describe the behaviour you expect (required)

Back to normal

## R code to reproduce the issue (required)

a<-extract_instruments(outcomes = "ieu-b-85")

## Contribute a solution (optional)

Please submit a pull request and/or briefly describe your proposed solution

## System information

R version 4.3.3 (2024-02-29 ucrt) -- "Angel Food Cake"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

## Additional context

Clump didn't work either

**Comment by DC-Jer** [comment]
meet same problem too.

**Comment by baiym13** [comment]
I also met this bug. Anyone can solve it?

**Comment by dlwlrmaabaaba** [comment]
met the same bug, did anyone solve it?

**Comment by remlapmot** [comment]
You need to update your TwoSampleMR and ieugwasr packages - you can use the following command to do this.

```r
install.packages("TwoSampleMR", repos = c("https://mrcieu.r-universe.dev", "https://cran.r-project.org"))
```

Then you need to obtain an `OPENGWAS_JWT` token - see the ieugwasr documentation <https://mrcieu.github.io/ieugwasr/articles/guide.html> - and store it in your .Renviron file - then restart R.

**Comment by skyer111** [comment]
> You may also have been banned for excessive use - if after obtaining a token it doesn't work, post on the ieugwasr repo that you probably need to be unbanned.



> You need to update your TwoSampleMR and ieugwasr packages - you can use the following command to do this.
> 
> ```r
> install.packages("TwoSampleMR", repos = c("https://mrcieu.r-universe.dev", "https://cran.r-project.org"))
> ```
> 
> Then you need to obtain an token - see the ieugwasr documentation https://mrcieu.github.io/ieugwasr/articles/guide.html - and store it in your .Renviron file - then restart R.`OPENGWAS_JWT`

非常感谢您的热心回答

**Comment by dlwlrmaabaaba** [comment]
> You need to update your TwoSampleMR and ieugwasr packages - you can use the following command to do this.
> 
> ```r
> install.packages("TwoSampleMR", repos = c("https://mrcieu.r-universe.dev", "https://cran.r-project.org"))
> ```
> 
> Then you need to obtain an `OPENGWAS_JWT` token - see the ieugwasr documentation https://mrcieu.github.io/ieugwasr/articles/guide.html - and store it in your .Renviron file - then restart R.

Useful comment. I have solved this problem, thank you very much ^_^
