### ISSUE TITLE
[BUG]: format_data() Error: j（在 [...] 中的第二个参数）是单一符号，但未找到列名 'i'

### ISSUE THREAD

**Issue by Carnivalera** [MRCIEU/TwoSampleMR#493]
## Describe the bug (required)
When using the function format_data(), an error alert emerged.

## Describe the current behaviour you observe (required)

错误: j（在 [...] 中的第二个参数）是单一符号，但未找到列名 'i'。如果你打算在调用环境中使用变量选择列，请尝试 DT[, ..i]。.. 前缀表示上一级，类似于文件系统路径。

## R code to reproduce the issue (required)

BMI_OUT<-TwoSampleMR::format_data(dat = BMI, type = "outcome", snps = CAD$SNP, header = TRUE, snp_col = "variant_id", beta_col = "beta", se_col = "standard_error", effect_allele_col = "effect_allele", other_allele_col = "other_allele", pval_col = "p_value")

## Contribute a solution (optional)

Please submit a pull request and/or briefly describe your proposed solution

## System information

*Please provide details of your operating system and R version*

## Additional context

*Add any other context about the problem here*

**Comment by Diekunstderfug** [comment]
Surely when I want to user format_dat, I check my data for manys time, but the error repeatly occurs. Finally I read the source codes, It seems that the variant "i" is not state properly. Please fix it if you have time, thanks!

**Comment by filmchen** [comment]
Have you resolved the issue? I have met the same problem, it would be appreciated if there is any suggestion!

**Comment by filmchen** [comment]
Editing the function TwoSampleMR::data.table(), instead "dat <- dat[, i]" with "dat <- dat[, ..i]",which can solve this problem.

**Comment by JPRAH-MORMONT** [comment]
> 编辑函数 TwoSampleMR：:d ata.table（），改为“dat <- dat[， i]”和“dat <- dat[， ..i]“，可以解决这个问题。
I have met the same problem
Thanks for your answer, however I can't understand the meaning.
It would be appreciated if there is more detailed answer or the code

**Comment by nadineparker** [comment]
I also had this issue when updating the TwoSampleMR package. An old script that worked 6 months ago (likely with v5.7) no longer works now (with v5.11). I assume something broke with one of the recent version updates.

**Comment by remlapmot** [comment]
Please see <https://github.com/MRCIEU/ieugwasr/issues/65#issuecomment-2061397631> for the instructions about the token.
