### ISSUE TITLE
[BUG]: mv_extract_exposures_local()

### ISSUE THREAD

**Issue by yaoyao99999999** [MRCIEU/TwoSampleMR#494]
**Please make sure that this is a bug! If you have questions about how to use TwoSampleMR please use the [Discussions](https://github.com/MRCIEU/TwoSampleMR/discussions) function instead.**

## Describe the bug (required)

When using the mv_extract_exposures_local() function, identified variants can be observed based on the output information, but results cannot be directly outputted.

## Describe the current behaviour you observe (required)

>   mv_extract_exposures_local(
+     filenames_exposure = c("class.Bacilli.id.1673_exposure.txt", "sugar_exposure.txt"), 
+     sep = " ",
+     phenotype_col = "Phenotype",
+     id_col = "id",
+     snp_col = 'SNP',
+     beta_col = 'BETA',
+     se_col = 'SE',
+     eaf_col = 'FRQ',
+     effect_allele_col = 'A1',
+     other_allele_col = 'A2',
+     pval_col = 'P',
+     samplesize_col = 'N',
+     min_pval = 1e-200, 
+     log_pval = FALSE, 
+     pval_threshold = 1e-4, 
+     clump_r2 = 0.001,
+     clump_kb = 10000,
+     pop = "EUR",
+     harmonise_strictness = 2
+   )
WARNING: Experimental function
No phenotype name specified, defaulting to 'outcome'.
Please look at vignettes for options on running this locally if you need to run many instances of this command.
Clumping class.Bacilli.id.1673, 634 variants, using EUR population reference
Removing 529 of 634 variants due to LD with other variants or absence from LD reference panel
Identified 105 hits for trait exposure1
No phenotype name specified, defaulting to 'outcome'.
Please look at vignettes for options on running this locally if you need to run many instances of this command.
Clumping Sugar, 1117 variants, using EUR population reference
Removing 1058 of 1117 variants due to LD with other variants or absence from LD reference panel
Identified 59 hits for trait exposure2
Please look at vignettes for options on running this locally if you need to run many instances of this command.
Clumping 1, 164 variants, using EUR population reference
Removing 19 of 164 variants due to LD with other variants or absence from LD reference panel
Identified 145 variants to include
[1] SNP                    exposure               id.exposure            effect_allele.exposure
[5] other_allele.exposure  eaf.exposure           beta.exposure          se.exposure           
[9] pval.exposure         
<0 行> (或0-长度的row.names)
Warning messages:
1: In format_data(as.data.frame(outcome_dat), type = "outcome", snps = snps,  :
  The following columns are not present but are helpful for harmonisation
FRQ

2: In format_data(outcome_dat, beta_col = "beta.outcome", se_col = "se.outcome",  :
  eaf column is not numeric. Coercing...

## Describe the behaviour you expect (required)
I hope to be able to output the results.
## R code to reproduce the issue (required)

*Please provide a minimal code snippet that will reproduce this issue*

## Contribute a solution (optional)

Please submit a pull request and/or briefly describe your proposed solution

## System information

*Please provide details of your operating system and R version*

## Additional context

*Add any other context about the problem here*

**Comment by harterz** [comment]
Hi @yaoyao99999999 ，I met same situation conducting MVMR. How to solve it? Thankx
