### ISSUE TITLE
Is any function to get I2?

### ISSUE THREAD

**Issue by Bochao1** [MRCIEU/TwoSampleMR#5]

**Comment by explodecomputer** [comment]
You can use `mr_heterogeneity(dat)` to obtain Q statistics, and then calculate Isq using

```
x <- mr_heterogeneity(dat)
(x$Q - x$Q_df) / x$Q) * 100
```

**Comment by olegkagan** [comment]
sorry, question following the above discussion, is there anyway to calculate CI from the mr_heterogeneity(dat)?

**Comment by mightyphil2000** [comment]
What would you like to calculate the confidence interval for?

________________________________________

**Comment by explodecomputer** [comment]
There are a few methods to calculate the confidence interval. One that is presented in Higgins & Thompson 2002 (http://onlinelibrary.wiley.com/doi/10.1002/sim.1186/epdf) is:

```
# Example parameters
Q <- 20
k <- 10
alpha <- 0.05

H <- sqrt(Q / (k-1))
isq <- (H^2 - 1) / H^2

Za <- qnorm(1-alpha/2)
se <- ifelse(Q > k, 
	0.5 * (log(Q) - log(k-1)) / (sqrt(2*Q) - sqrt(2*k-3)),
	sqrt((1/(2*k-2)) * (1 - (1 / (3 * (k-2)^2))))
)

conf <- exp(log(H) + c(-1, 1) * Za * se)
(conf^2 - 1) / (conf^2)
```

I've not checked this code very rigorously, but given time I will implement in the R package

**Comment by mightyphil2000** [comment]
Thanks gib


________________________________________

**Comment by olegkagan** [comment]
thanks gib!
