### ISSUE TITLE
[BUG]: Error in extracting outcome instruments, telling to contact the developers.

### ISSUE THREAD

**Issue by Terry-Liu88** [MRCIEU/TwoSampleMR#508]
**Please make sure that this is a bug! If you have questions about how to use TwoSampleMR please use the [Discussions](https://github.com/MRCIEU/TwoSampleMR/discussions) function instead.**

## Describe the bug (required)

Hello, when I was extracting the ending, I jumped to the login interface of my Google account. However, after I logged in with my account, the authorization was not successful and I could not extract the ending.

## Describe the current behaviour you observe (required)

out <- extract_outcome_data(
+         snps=exp$SNP,
+         outcomes=out_dat_id,
+         
+       )
Extracting data for 48 SNP(s) from 1 GWAS(s)
Using access token. For info on how this is used see logging_info()
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
错误: Could not authenticate via any gargle cred function

## R code to reproduce the issue (required)

*Please provide a minimal code snippet that will reproduce this issue*

## Contribute a solution (optional)

Please submit a pull request and/or briefly describe your proposed solution

## System information

*Please provide details of your operating system and R version*

## Additional context

*Add any other context about the problem here*

**Comment by MichaelPudjihartono** [comment]
Any solution?

**Comment by remlapmot** [comment]
Please try updating your version of TwoSampleMR and also setting up an authentication token.

To update TwoSampleMR, restart your R session (i.e., close R, then reopen it), then run

```r
install.packages("TwoSampleMR", repos = c("https://mrcieu.r-universe.dev", "https://cran.r-project.org"))
```

This will update TwoSampleMR and ieugwasr. Then set up a token as described at this link <https://mrcieu.github.io/ieugwasr/articles/guide.html#authentication>. After you have put your token in your _.Renviron_ file again restart your R session.

**Comment by Terry-Liu88** [comment]
> Please try updating your version of TwoSampleMR and also setting up an authentication token.
> 
> To update TwoSampleMR, restart your R session (i.e., close R, then reopen it), then run
> 
> ```r
> install.packages("TwoSampleMR", repos = c("https://mrcieu.r-universe.dev", "https://cran.r-project.org"))
> ```
> 
> This will update TwoSampleMR and ieugwasr. Then set up a token as described at this link https://mrcieu.github.io/ieugwasr/articles/guide.html#authentication. After you have put your token in your _.Renviron_ file again restart your R session.

Thank you so much, this helped me a lot
