### ISSUE TITLE
[BUG]: The query to MR-Base exceeded 300 seconds and timed out. Please simplify the query

### ISSUE THREAD

**Issue by wula-pro** [MRCIEU/TwoSampleMR#513]
> exp_dat <- extract_instruments(outcomes="ukb-b-3822",p1 =5e-08,clump=TRUE,r2=0.001,kb=10000,opengwas_jwt = ieugwasr::get_opengwas_jwt(),force_server = FALSE)
Error in api_query("tophits", query = list(id = id, pval = pval, preclumped = preclumped,  : 
  The query to MR-Base exceeded 300 seconds and timed out. Please simplify the query

**Comment by JasonQiu** [comment]
https://github.com/MRCIEU/ieugwasr/issues/72#issuecomment-2094691008

**Comment by Gaealiu** [comment]
@JasonQiu I have this problem too. I am writing to express my sincerest apologies for submitting too many requests in a short period of time, causing your server to become overloaded recently. Initially, I was concerned that a potential network problem might prevent further connections, prompting me to send multiple queries in quick succession. Here is my ip address: 192.168.0.112. I hope you can help unblock it, thank you!

**Comment by kpCCCP** [comment]
@JasonQiu Dear Sir, I'm very sorry to bother you. I also encountered this problem. But looking back at your previous replies, I found that the previous such errors that appeared were not quite the same as this error in the current discussion. The error I encountered is prompted as: Error in api_query ("tophits", query = list (id = id, pval = pval, preclumped = preclumped, : The query to MR-Base exceeded 300 seconds and timed out. Please simplify the query. Although I don't know how to distinguish the difference between these two errors, this is my IP address: 14.105.173.236. I hope you can help me lift the restriction. I will strictly follow the usage rules, and here I express my sincere thanks.
