### ISSUE TITLE
[BUG]: Server code: 503; Server is possibly experiencing traffic, trying again...

### ISSUE THREAD

**Issue by Uppaln1** [MRCIEU/TwoSampleMR#521]
**Please make sure that this is a bug! If you have questions about how to use TwoSampleMR please use the [Discussions](https://github.com/MRCIEU/TwoSampleMR/discussions) function instead.**

## Describe the bug (required)

I am trying to clump SNPs using the TwoSampleMR command Clump_data and it is producing the result

<img width="830" alt="Screen Shot 2024-05-24 at 2 31 09 PM" src="https://github.com/MRCIEU/TwoSampleMR/assets/93106866/e319a9bf-e29d-4828-9619-69a5cd4e6212">
<img width="912" alt="Screen Shot 2024-05-24 at 2 34 35 PM" src="https://github.com/MRCIEU/TwoSampleMR/assets/93106866/8ee4b5ee-2ebf-479b-8a02-6927675cb695">

## Describe the current behaviour you observe (required)

When I check the status of the servers I obtain this:
<img width="330" alt="Screen Shot 2024-05-24 at 2 33 02 PM" src="https://github.com/MRCIEU/TwoSampleMR/assets/93106866/766b7621-5b08-47d2-a12e-7160da55e823">

## Describe the behaviour you expect (required)
I expected the clumping to run successfully and obtain list of clumped variants. Could this be due to the variants not being present in the reference panel? Or are the servers currently busy?
 
## Contribute a solution (optional)

Please submit a pull request and/or briefly describe your proposed solution

## System information

MacOS 11
Rstudio version 4.0 

## Additional context

Thank you for any help that can be provided it is much appreciated!

**Comment by JasonQiu** [comment]
Check latest versions of ieugwasr and TwoSampleMR
