### ISSUE TITLE
[BUG]:  Experiencing Fail Retrieve

### ISSUE THREAD

**Issue by tj0129edgar** [MRCIEU/TwoSampleMR#531]
First of all, Thanks for all the effort that the developers made for the improvement of this R package.  It is still not working after I first reported the bug, even if I installed the newest version of R package. I also checked the allowance and my request were not limited. My api is still available now.I tried to use my roommate's computer and revealed the same results.  I really do not know where the problems lies. 
 
The code:
Server code: 500; Server is possibly experiencing traffic, trying again...
Server code: 500; Server is possibly experiencing traffic, trying again...
Server code: 500; Server is possibly experiencing traffic, trying again...
Server code: 500; Server is possibly experiencing traffic, trying again...
Server code: 500; Server is possibly experiencing traffic, trying again...
Server code: 500; Server is possibly experiencing traffic, trying again...
Server error: 500
Failed to retrieve results from server. See error status message in the returned object and contact the developers if the problem persists.
if (nrow(d) == 0) return(NULL)

**Comment by dongchaoanderuni** [comment]
Have you find the solution?

**Comment by opuyu** [comment]
Have you found a solution? I need help.

**Comment by tj0129edgar** [comment]
SORRY, I DIDN'T FIND ANY SOLUTION. I DOWNOADED THE DATA FROM THE DATASET. I FOUND THAT THE OTHER FUNCTIONS OF THE PACKAGE ARE AVAILABLE EXPECT THE EXTRACTING PROCEDURE.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MRCIEU/TwoSampleMR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月20日(星期六) 上午10:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MRCIEU/TwoSampleMR] [BUG]:  Experiencing Fail Retrieve (Issue #531)





 
Have you find the solution?

**Comment by tj0129edgar** [comment]
SORRY, I DIDN'T FIND ANY SOLUTION. I DOWNOADED THE DATA FROM THE DATASET. I FOUND THAT THE OTHER FUNCTIONS OF THE PACKAGE ARE AVAILABLE EXPECT THE EXTRACTING PROCEDURE.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MRCIEU/TwoSampleMR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月22日(星期一) 下午4:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MRCIEU/TwoSampleMR] [BUG]:  Experiencing Fail Retrieve (Issue #531)





 
Have you found a solution? I need help.
