### ISSUE TITLE
[BUG]: Failed to retrieve results from server. 

### ISSUE THREAD

**Issue by dongchaoanderuni** [MRCIEU/TwoSampleMR#537]
**Please make sure that this is a bug! If you have questions about how to use TwoSampleMR please use the [Discussions](https://github.com/MRCIEU/TwoSampleMR/discussions) function instead.**

## Describe the bug (required)

*Provide a clear and concise description of what the bug is*

It last several days, and I update TwoSampleMR to 0.6.6, ieugwasr is 1.0.1, I totally have no idea why it could not work.

Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server error: 503
Failed to retrieve results from server. See error status message in the returned object and contact the developers if the problem persists.
Response [http://gwas-api.mrcieu.ac.uk/user]
  Date: 2024-07-19 10:09
  Status: 503
  Content-Type: text/html; charset=iso-8859-1
  Size: 299 B
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
</body></html>
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server error: 503
Failed to retrieve results from server. See error status message in the returned object and contact the developers if the problem persists.

Error in if (nrow(d) == 0) return(NULL) (drugMR05.MR.R#46): argument is of length zero

## Describe the current behaviour you observe (required)

*Include code blocks with any error messages*

## R code to reproduce the issue (required)

*Please provide a minimal code snippet that will reproduce this issue*

## Contribute a solution (optional)

Please submit a pull request and/or briefly describe your proposed solution

## System information

*Please provide details of your operating system and R version*

## Additional context

*Add any other context about the problem here*

**Comment by JasonQiu** [comment]
Do not alter `ieugwasr_api`. Just use the default one.
