### ISSUE TITLE
[BUG]: OpenGWAS allowance exhausted

### ISSUE THREAD

**Issue by zyz-430** [MRCIEU/TwoSampleMR#539]
**Please make sure that this is a bug! If you have questions about how to use TwoSampleMR please use the [Discussions](https://github.com/MRCIEU/TwoSampleMR/discussions) function instead.**

## Describe the bug (required)

I am writing to seek assistance with an issue I have encountered while using the OpenGWAS service. Despite only running a single gene analysis once, I have received a warning that my OpenGWAS allowance has been exhausted. This has caused significant disruption to my work for nearly a week, and I am at a loss as to how to proceed.
Here are the details of the gene analysis I conducted:
exposureID="ukb-a-435"     #暴露数据ID
outcomeID="ukb-d-I9_HYPTENS"        #结局数据ID

geneChr=10                  #基因所在的染色体(https://www.ncbi.nlm.nih.gov/gene)
geneStart=115803625         #染色体起始位置
geneEnd=115806663           #染色体终止位置

exposureName="Vascular/heart problems diagnosed by doctor: None of the above || ADRB1"         #设置图形中展示暴露因素的名称
diseaseName="Hypertension"        #疾病名称
setwd("D:\\projects\\0004_DrugTargetMR\\05.MR")      #设置工作目录

## Describe the current behaviour you observe (required)

Warning in set_reset(r) :
  You have used up your OpenGWAS allowance. Your allowance will reset at 2024-07-22 14:36:53.482827. See https://api.opengwas.io/api/#allowance for more details.
No encoding supplied: defaulting to UTF-8.

Error in mtfrm.default(list(url = "https://api.opengwas.io/api/ld/clump",  (drugMR05.MR.R#40): cannot mtfrm
Show stack trace
## Describe the behaviour you expect (required)
save the error for me
## R code to reproduce the issue (required)

exposureID="ukb-a-435"     #暴露数据ID
outcomeID="ukb-d-I9_HYPTENS"        #结局数据ID

geneChr=10                  #基因所在的染色体(https://www.ncbi.nlm.nih.gov/gene)
geneStart=115803625         #染色体起始位置
geneEnd=115806663           #染色体终止位置

exposureName="Vascular/heart problems diagnosed by doctor: None of the above || ADRB1"         #设置图形中展示暴露因素的名称
diseaseName="Hypertension"        #疾病名称

## Contribute a solution (optional)

Please submit a pull request and/or briefly describe your proposed solution

## System information
 TwoSampleMR is 0.6.6, ieugwasr is 1.0.1
## Additional context

*Add any other context about the problem here*
Account lD of the token:67628d02-7676-35f7-a0e7-4e69ec2b46ba

**Comment by JasonQiu** [comment]
https://github.com/MRCIEU/TwoSampleMR/issues/538#issuecomment-2243656145
