### ISSUE TITLE
[BUG]: Server code: 502; Server is possibly experiencing traffic, trying again - changed API as suggested, no variants left - please help!

### ISSUE THREAD

**Issue by gg-n** [MRCIEU/TwoSampleMR#541]
**Hello,

I seem to be having a similar issue that was reported by someone else today. I would be very grateful for some advice and help. I have a close deadline, and not able to progress with the analysis. Thank you so much!

When I am trying to do clumping in R using the TwoSampleMR package, I get the message below.**
```

 exposure_clump <- clump_data(
+     exposure,
+     clump_kb = 10000,
+     clump_r2 = 0.001,
+     pop = "EUR")
API: public: http://gwas-api.mrcieu.ac.uk/
Please look at vignettes for options on running this locally if you need to run many instances of this command.
Clumping 2q4aRY, 235 variants, using EUR population reference
Server code: 502; Server is possibly experiencing traffic, trying again...
Server code: 502; Server is possibly experiencing traffic, trying again...
Server code: 502; Server is possibly experiencing traffic, trying again...
Server code: 502; Server is possibly experiencing traffic, trying again...
Server code: 502; Server is possibly experiencing traffic, trying again...
Server code: 502; Server is possibly experiencing traffic, trying again...
Server error: 502
Failed to retrieve results from server. See error status message in the returned object and contact the developers if the problem persists.
Removing 235 of 235 variants due to LD with other variants or absence from LD reference panel_

I saw the advice suggested earlier to change  the API from "http://gwas-api.mrcieu.ac.uk/" to "https://api.opengwas.io/api/", which I have managed to do. 

> options("ieugwasr_api")
$ieugwasr_api
[1] "https://api.opengwas.io/api/"

**However, when I proceed with the clumping, I get the below message, essentially all the variants are removed.**

>   exposure_clump <- clump_data(
+     exposure,
+     clump_kb = 10000,
+     clump_r2 = 0.001,
+     pop = "EUR")
Please look at vignettes for options on running this locally if you need to run many instances of this command.
Clumping 2q4aRY, 235 variants, using EUR population reference

Removing 235 of 235 variants due to LD with other variants or absence from LD reference panel.

Could you please help with this? before this error, a couple of days ago, I had 87 variants remaining after this step, and now there are none.
The message also suggests absence from LD reference panel, how can I fix that? 

Thank you very much!!

**Comment by JasonQiu** [comment]
It's not just about changing the URL. You need to set up JWT properly.

https://mrcieu.github.io/ieugwasr/articles/guide.html#authentication

**Comment by jiachenchen322** [comment]
Hi, I am still encountering issues after setting up JWT in .Renviron. Please see the output in R below:

1) 
> library(remotes)
> library(TwoSampleMR)
> ieugwasr::select_api()
API: public: https://api.opengwas.io/api/
> ieugwasr::get_opengwas_jwt()
<token output omitted here>
> ao <- available_outcomes()
Error in `dplyr::bind_rows()`:
! Argument 1 must be a data frame or a named atomic vector.
Run `rlang::last_trace()` to see where the error occurred.

Or if I specify options(ieugwasr_api = 'gwas-api.mrcieu.ac.uk/')
2) ao <- available_outcomes()
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...

Could you please provide some guidance on this? Thanks!

**Comment by JasonQiu** [comment]
> It's not just about changing the URL. You need to set up JWT properly.
> 
> https://mrcieu.github.io/ieugwasr/articles/guide.html#authentication

Make sure you have followed every step here, including step 6.

6. To check that your token is working, run [user()](https://mrcieu.github.io/ieugwasr/reference/user.html). It will make a request to the API for your user information using your token. **_It should return a list with your user information. If it returns an error, then your token is not working._**

Also it's not worth sticking to gwas-api.mrcieu.ac.uk - just forget about it.

**Comment by gg-n** [comment]
Hi JasonQiu,

Thanks very much for your help. I have managed to get it working.

**Comment by jiachenchen322** [comment]
Thank you so much for your help, Jason! It works well now.
