### ISSUE TITLE
[BUG]: Error while using available_outcomes() function: Server code: 503; Server is possibly experiencing traffic 

### ISSUE THREAD

**Issue by AleRaho** [MRCIEU/TwoSampleMR#542]
Basically the title: 
in the last 2 weeks every time I try to use the available_outcomes() function this is what I obtain after 10 minutes of run:

> options(ieugwasr_api = 'gwas-api.mrcieu.ac.uk/')
> ao<- available_outcomes()
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server error: 503
Failed to retrieve results from server. See error status message in the returned object and contact the developers if the problem persists.
Error in `dplyr::bind_rows()`:
! Argument 1 must be a data frame or a named atomic vector.
Run `rlang::last_trace()` to see where the error occurred.

**Comment by JasonQiu** [comment]
https://github.com/MRCIEU/TwoSampleMR/issues/541
