### ISSUE TITLE
[BUG]: Cannot use any function that requires networking

### ISSUE THREAD

**Issue by lihua132** [MRCIEU/TwoSampleMR#543]
**Please make sure that this is a bug! If you have questions about how to use TwoSampleMR please use the [Discussions](https://github.com/MRCIEU/TwoSampleMR/discussions) function instead.**

## Describe the bug (required)

*Provide a clear and concise description of what the bug is*

## Describe the current behaviour you observe (required)

*Include code blocks with any error messages*

## R code to reproduce the issue (required)

*Please provide a minimal code snippet that will reproduce this issue*

## Contribute a solution (optional)

Please submit a pull request and/or briefly describe your proposed solution

## System information

*Please provide details of your operating system and R version*

## Additional context

*Add any other context about the problem here*

I'm trying to figure out why I've been unable to access https://api.opengwas.io/profile for the last week, and I've been unable to either reset my token or use the extraction function in TwoSampleMR. I confirmed that I linked the network and that I am not extracting data from the database in bulk but just individual data. I've tried many networks and it doesn't do anything, it says: Internal Server Error when accessing the web page and always returns a 503 error when using the extract function. I hope to get your reply, thanks!

**Comment by JasonQiu** [comment]
What does https://whatismyipaddress.com/ say for IPv4?

**Comment by lihua132** [comment]
[202.198.161.39]

**Comment by lihua132** [comment]
> What does https://whatismyipaddress.com/ say for IPv4?
I'm glad you got back to me. That web page you gave shows: Your location may be exposed! Could it be a problem with the IP? I've tried to link to the server by changing to a different IP, but all the networks I can use can't link to the server, which doesn't seem to make sense.

**Comment by JasonQiu** [comment]
I only need the information showed in the "IPv4" section.

Is it still 202.198.161.39 now?

**Comment by lihua132** [comment]
> 我只需要“IPv4”部分中显示的信息。
> 
> 现在还是202.198.161.39吗？
Yeah.

**Comment by JasonQiu** [comment]
Your IP address is not blocked on our side at the time of writing.

If you even cannot visit https://api.opengwas.io/profile in your browser (not RStudio) then please check your own network.

**Comment by lihua132** [comment]
> Your IP address is not blocked on our side at the time of writing.
> 
> If you even cannot visit https://api.opengwas.io/profile in your browser (not RStudio) then please check your own network.

Thanks again for your reply.I will try what you said.Hope you have a wonderful weekend.
