### ISSUE TITLE
"Usage  issues  of  the  extract_outcome_data  function"

### ISSUE THREAD

**Issue by M-jk22** [MRCIEU/TwoSampleMR#547]
Dear  Sir/Madam,

I  recently  visited  the  website:  https://gwas.mrcieu.ac.uk/  and  found  that  some  data  were  not  available  for  download  in  the  local  VCF  file  format.  It  seems  that  this  data  may  not  have  been  publicly  released.  However,  when  I  used  the  extract_outcome_data  function  to  input  the  ID  of  the  project,  the  data  became  accessible.  I  am  unsure  whether  the  data  obtained  in  this  manner  is  complete  and  whether  it  can  be  used  for  subsequent  data  analysis.

I  would  appreciate  it  if  you  could  kindly  clarify  the  following:

Is the data obtained through the extract_outcome_data function complete and suitable for further analysis?
If the data is not complete, are there any alternative methods to access the complete dataset?
Thank  you  for  your  attention  to  this  matter,  and  I  look  forward  to  your  prompt  response.

Yours  sincerely

**Comment by JasonQiu** [comment]
All datasets that are present in the query result are ready for use. Around 17% of them do not have a VCF download link on the website. This will be addressed when funds permit.
