### ISSUE TITLE
[BUG]: Can not get the list of outcomes

### ISSUE THREAD

**Issue by PeriwigXu** [MRCIEU/TwoSampleMR#561]
**Please make sure that this is a bug! If you have questions about how to use TwoSampleMR please use the [Discussions](https://github.com/MRCIEU/TwoSampleMR/discussions) function instead.**

## Describe the bug (required)
I was trying to get the list of outcomes in OpenGWAS using available_outcomes(), but somehow it only returned 10 rows.

## Describe the current behaviour you observe (required)
The function in TwoSampleMR, available_outcomes only returned 10 rows. And interestingly, the first two rows show 'TEST-DO NOT USE' in the 'trait' field. I guess someone is testing the API in the production environment.

## Describe the behaviour you expect (required)
There should have been at least thousands of rows in the data frame, at least there was on last month.

## R code to reproduce the issue (required)
```R
pacman::p_load(
  TwoSampleMR,
  MVMR,
  dplyr,
  tibble,
  RMVMR
)
ao <- available_outcomes()
```

## Additional context
ao[1:2, 1:5]
Rows: 2
Columns: 5
$ id         <chr> "ieu-b-5138", "ieu-b-5137"
$ trait      <chr> "TEST - DO NOT USE 3", "TEST - DO NOT USE 2"
$ nsnp       <int> 99999, 99999
$ build      <chr> "HG19/GRCh37", "HG19/GRCh37"
$ group_name <chr> "public", "public"

The version of my TwoSampleMR is 0.6.8

**Comment by JaikumarMuniswamy** [comment]
Same issue  I am also facing , did you debug it?

**Comment by PeriwigXu** [comment]
> Same issue I am also facing , did you debug it?

I didn't but It's been solved somehow. There are 50,033 rows now. I didn't update any of my requirements, so apparently it's an API accident.
