### ISSUE TITLE
[BUG]: Issue with available_outcomes

### ISSUE THREAD

**Issue by ronaldo7-star** [MRCIEU/TwoSampleMR#565]
I am using the TwoSampleMR package and trying to generate the available outcomes. However, for the following code, I do not know where to put the token ID# that I got for the API request.

ao <-available_outcomes(opengwas_jwt = ieugwasr::get_opengwas_jwt())

Let # = token ID number
I have tried the following codes, but none have been successful:
ao <-available_outcomes(opengwas_jwt = #)
ao <-available_outcomes(opengwas_jwt = ieugwasr::getopengwas_jwt(#))

Would you please help me with correcting my code for the available_outcomes code? Thanks so much for your help!

**Comment by remlapmot** [comment]
Please put a line in your .Renviron file - which is just a text file in your home directory. You can follow the instructions at <https://mrcieu.github.io/ieugwasr/articles/guide.html#authentication>

If you struggle to create the .Renviron file yourself you can install the usethis package to help you edit it
```r
install.packages('usethis')
usethis::edit_r_environ()
```
And then enter the required line in .Renviron
```
OPENGWAS_JWT=#############
```
save the file, then restart your R session and call `available_outcomes()`.
