### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by mero2929** [MRCIEU/TwoSampleMR#573]
> options(ieugwasr_api='gwas-api.mrcieu.ac.ur/')
> exposure_gwas <- read.csv(file_path, stringsAsFactors = FALSE)
> exposure_gwas <- exposure_gwas %>%
+   rename(
+     SNP = rsID,                    
+     effect_allele = A0,            
+     other_allele = A1,            
+     beta = BETA,                  
+     se = SE,                       
+     pval = Pvalue,              
+     chr = CHROM,                   
+     pos = GENPOS                  
+   )
> exposure_gwas <- exposure_gwas %>%
+   distinct(SNP, .keep_all = TRUE)
> if (!"eaf" %in% colnames(exposure_gwas)) {
+   exposure_gwas$eaf <- exposure_gwas$A1FREQ  # A1FREQ를 eaf로 설정
+ } else {
+   exposure_gwas$eaf <- ifelse(is.na(exposure_gwas$eaf), exposure_gwas$A1FREQ, exposure_gwas$eaf)
+ }
> exposure_gwas$eaf <- as.numeric(exposure_gwas$eaf)
> exposure_data<-format_data(exposure_gwas)
No phenotype name specified, defaulting to 'exposure'.
> exposure_data<-clump_data(exposure_data, clump_r2 = 0.001, pop="EUR")
Please look at vignettes for options on running this locally if you need to run many instances of this command.
Clumping kYUj5o, 39 variants, using EUR population reference
api_query("ld/clump", query = list(rsid = dat[["rsid"]], pval = dat[["pval"]], 
  The MR-Base server appears to be down, the following error was received:
Error in curl::curl_fetch_memory(url, handle = handle): Could not resolve hostname [gwas-api.mrcieu.ac.ur]: Could not resolve host: gwas-api.mrcieu.ac.ur

I am keep getting the error message despite using the code "> options(ieugwasr_api='gwas-api.mrcieu.ac.ur/')"
Is MR base server down at the moment?
please share your experience, thank you in advance.

**Comment by JasonQiu** [comment]
Avoid altering the API base URL, i.e. don't do `options(ieugwasr_api='gwas-api.mrcieu.ac.ur/')` (the first line of your code). It's unnecessary, let alone the URL was wrong.

Please make sure you are using the latest version of ieugwasr and TwoSampleMR.
