### ISSUE TITLE
[BUG]: You have used up your OpenGWAS allowance

### ISSUE THREAD

**Issue by AleRaho** [MRCIEU/TwoSampleMR#575]
I'm trying to use the extract_outcome_data() function, but in a week or so I keep retrieving the same error:

Extracting data for 328 SNP(s) from 1 GWAS(s)
Finding proxies for 328 SNPs in outcome ebi-a-GCST90027158
Extracting data for 328 SNP(s) from 1 GWAS(s)
Errore in check_reset(override_429) : 
  You have used up your OpenGWAS allowance. Please wait until 2024-11-27 09:44:03.400065to submit another query. See https://api.opengwas.io/api/#allowance for more details. This check is in place to prevent your IP address from being temporarily blocked, but you can override it at your own risk by setting override_429=TRUE.
In aggiunta: Messaggio di avvertimento:
In set_reset(r) :
  You have used up your OpenGWAS allowance. Your allowance will reset at 2024-11-27 09:44:03.400065. See https://api.opengwas.io/api/#allowance for more details.

I read everything in the linked page, but I was not able to solve the problem. Was I suspended? Is there something I can try?

**Comment by jiangxiya-alt** [comment]
请问解决了吗

**Comment by AleRaho** [comment]
Yes, I made it work. Thanks

**Comment by ldbldb** [comment]
How did you solve the problem?

**Comment by mdrj202** [comment]
Hi @AleRaho may you please share how you solved the problem, as I am getting the same issue come up?
