### ISSUE TITLE
Error: Could not authenticate via any gargle cred function

### ISSUE THREAD

**Issue by 731104** [MRCIEU/TwoSampleMR#577]
Hi, I have used TwoSampleMR for many years. Now code I used to be able to run doesn't. 
For example
clump_data3 <- TwoSampleMR::extract_instruments(outcomes="ebi-a-GCST90104345",p1 = 5e-08,
                                                clump = TRUE,
                                                p2 = 5e-08,
                                                r2 = 0.001,
                                                kb = 10000,
                                                access_token = ieugwasr::check_access_token(),
                                                force_server = FALSE)

When I want to run this code today, I get this error 
"Using access token. For info on how this is used see logging_info()
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort"

TwoSampleMR (version 0.5.8) and ieugwasr (version 0.2.2) were installed.

I have Gmail so  I type in, but get another error "Error: Could not authenticate via any gargle cred function".  The reason why I have the old version of R packages is for verifying previous results.  Or please tell me which method should be used in TwoSampleMR version 0.5.8 .

Many thanks!

**Comment by JasonQiu** [comment]
Upgrade to the latest versions of ieugwasr and TwoSampleMR, and try to remove the `access_token` parameter.

That parameter has been renamed to `opengwas_jwt` which is **_required only when_** you have **_not_** configured `.Renviron`.

https://mrcieu.github.io/TwoSampleMR/reference/extract_instruments.html

**Comment by 731104** [comment]
Many thanks！Is there any way that  I can continue to use the old version without this error

**Comment by remlapmot** [comment]
No, there is no way to extract data using the previous versions.

**Comment by 731104** [comment]
Thanks a lot！It was a great help!
