### ISSUE TITLE
SNP clumping not working

### ISSUE THREAD

**Issue by olegkagan** [MRCIEU/TwoSampleMR#6]
Dear developers,

clump_data() was working last week but stopped working now, is there any change in the package that I need to update?

It keeps giving me error message

```
T1D_mQTL_expo_clump<-clump_data(T1D_mQTL_expo)
Clumping 0hW4Tu, 1 SNPs
Error: Forbidden
```

I was used exactly the same code as last week. To test whether the example provided in the package was still working, I followed:

```
library(MRInstruments)
data(gwas_catalog)
bmi_gwas <- subset(gwas_catalog, grepl("Speliotes", Author) & Phenotype == "Body mass index (kg/m2 increase)")
bmi_exp_dat <- format_data(bmi_gwas)
bmi_exp_dat <- clump_data(bmi_exp_dat)
Clumping WhxFbM, 32 SNPs
Error: Forbidden
```
I got the same thing. Sorry for having many troubles...

Thanks

**Comment by explodecomputer** [comment]
network
