### ISSUE TITLE
New error when extracting instruments

### ISSUE THREAD

**Issue by ksiewert** [MRCIEU/TwoSampleMR#7]
Starting today, the function to extract instruments is not working correctly and instead results in an error. For instance, if I run the commands:
library(MRInstruments)
ao <- available_outcomes()
exposure_dat <- extract_instruments(ao$id[c(2)])

I get:
Extracting data from 1 GWAS(s)
and performing LD clumping
 [>] 1 of 1
Token cache file: .httr-oauth
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML PUBLIC "-//W3C//
                     (right here) ------^

I've been using MRbase for weeks and haven't gotten this error before, so I'm wondering if something changed. I tried deleting the .httr-oauth file and making it again, but the error still occurs.

**Comment by explodecomputer** [comment]
Apologies, there was a server issue which is fixed now. We're working on upgrading to new servers which will be much faster and more stable!
