### ISSUE TITLE
extract outcomes error - server problem?

### ISSUE THREAD

**Issue by jonnyrose** [MRCIEU/TwoSampleMR#75]
Just to let you know that trying to extract outcome data: 

Extracting data for 7 SNP(s) from 1 GWAS(s)
Token cache file: mrbase.oauth
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML PUBLIC "-//W3C//
                     (right here) ------^
> 
This happened before and you all told me it was a server problem.

Thanks!

**Comment by elswob** [comment]
We've had an issue with the server, should be ok now?

**Comment by ChristopherZouNMU** [comment]
have you solve the problem? I meet this same problem now! the project just stop right there.
