### ISSUE TITLE
MR-MoE rf data download link broken

### ISSUE THREAD

**Issue by sritchie73** [MRCIEU/TwoSampleMR#77]
On the documentation on the gh-pages branch the link to download the rf data for MR-MoE at www.dropbox.com/s/k0grrhh0ak8er7q/rf.rdata?dl=0 is returning a 404 page not found error code.

**Comment by explodecomputer** [comment]
Sorry for the slow reply, I've been on parental leave for the last few months. This was fixed here https://github.com/MRCIEU/TwoSampleMR/issues/94
