### ISSUE TITLE
clump_data removes all SNPs

### ISSUE THREAD

**Issue by jorient** [MRCIEU/TwoSampleMR#8]
I am trying to run some 2 sample MR analyses but when I use the clump_data command it removes all SNPs that are in the input file. It says they are all in LD with other SNPs but this cannot be the case.
When I ran the exact same script a few weeks ago, with the same data, I didn't have this problem. Did something chance in the R script?
Thank you in advance!

**Comment by explodecomputer** [comment]
Hi Jorient currently trying to fix a server issue, will let you know when it's back up

**Comment by jorient** [comment]
OK, great. Thanks for the reply!

2017-07-26 11:26 GMT+01:00 gibran hemani <notifications@github.com>:
