### ISSUE TITLE
Heterogeneity () Function 

### ISSUE THREAD

**Issue by RoaaNaa** [MRCIEU/TwoSampleMR#86]
Hello,
I have a problem with mr_heterogeneity();
the result that i had is for Q-pval = 0 
 why this happen ? what is the solution ?

could you please help me ?
 regards

**Comment by mightyphil2000** [comment]
Hi

I guess the p value was so small it just returned a zero. Do you have the Q statistic?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by RoaaNaa** [comment]
Hello ,
yes it really small , but anyway i need its value 
I don't have Q-statistic , how i can write it ? and calculated ?

**Comment by mightyphil2000** [comment]
What output did you get from the het function?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by bperry089** [comment]
I'm adding a quick query to this thread because it's related.

The Q output from mr_heterogeneity() - can I ask - is this Cochran's Q or Rucker's Q (or something different?)

TIA

**Comment by mightyphil2000** [comment]
Cochran's Q

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
