### ISSUE TITLE
License and Copyright notice

### ISSUE THREAD

**Issue by mikesivley** [MRCIEU/TwoSampleMR#87]
Thank you very much for this excellent codebase. We would like to ensure that our use of the code is in compliance with your license and copyright. We noticed that other code in the MRC IEU repositories was labelled with ‘Copyright (c) <year> MRC Integrative Epidemiology Unit’, however we could not see any such statements in the TwoSampleMR repository. We assume that the same copyright arrangement would apply to TwoSampleMR, and the omission is just an oversight. However we thought it best to check, and give you the opportunity to update the copyright statements in the TwoSampleMR files.

**Comment by mightyphil2000** [comment]
Hi Mike


Yes your interpretation is correct. Thank you for highlighting this.


bw

Philip

________________________________
