### ISSUE TITLE
Different number of rows Problem in running  mr_singlesnp

### ISSUE THREAD

**Issue by jjandshi** [MRCIEU/TwoSampleMR#9]
Hi my data includes 8 SNPs and the data file works for basic MR analysis. However, when running mr_singlesnp on the R function in my PC, below error information popped up:

Error in data.frame(SNP = c(as.character(x$SNP), nom), b = sapply(l, function(y) y$b),  : 
  arguments imply differing number of rows: 10, 0

Could you please help me out?
Thanks,
Justin

**Comment by jjandshi** [comment]
Here is the dataset.

[Manually_harmonised_datat_8.txt](https://github.com/MRCIEU/TwoSampleMR/files/1198333/Manually_harmonised_datat_8.txt)

**Comment by danconsidine** [comment]
I'm having the exact same issue. 
No idea what is causing it.

**Comment by explodecomputer** [comment]
Thanks @jjandshi and @danconsidine. @jjandshi my apologies for the lengthy delay. The problem was that the singlesnp function was looking for a samplesize.outcome column. I've fixed this now, if you update to the latest version things should work again.

14172721cb6919b20b19e46cafbe483433327c1a
