### ISSUE TITLE
Dropbox link not working

### ISSUE THREAD

**Issue by ParsaAkbari** [MRCIEU/TwoSampleMR#94]
Hi,

The Dropbox link for the `rdata` file to enable MR-MOE is no longer working:
https://mrcieu.github.io/TwoSampleMR/#mr-moe-using-a-mixture-of-experts-machine-learning-approach

Thanks!

**Comment by explodecomputer** [comment]
Apologies, I had updated the documentation within the R package with the new link but not the online documentation. This has been done now

http://www.dropbox.com/s/5la7y38od95swcf/rf.rdata?dl=0
