### ISSUE TITLE
error Error: Cannot read token from alleged .rds file: mrbase.oauthError in readRDS(token_path): error reading from connection

### ISSUE THREAD

**Issue by SunnyWit** [MRCIEU/TwoSampleMR#95]
I used the package"TwoSampleMR",it was all right several weeks ago.
but today I use it, It always show:
Error: Cannot read token from alleged .rds file: mrbase.oauthError in readRDS(token_path): error reading from connection.
So I try to update the package, I use this code:
library(devtools)
install_github("MRCIEU/MRInstruments")
it suggests :Error in install_github("MRCIEU/TwoSampleMR"") : 
  could not find function "install_github"
So what can i do to solve this problem?

**Comment by explodecomputer** [comment]
If you can't find the `install_github` function then the devtools package hasn't been loaded

```
library(devtools)
install_github("MRCIEU/TwoSampleMR")
install_github("MRCIEU/MRInstruments")
```

The error relating to reading mrbase.oauth you can try to get around by

1. Deleting the mrbase.oauth file that is in your working directory in case it is corrupted
2. Making sure that your working directory has write access

**Comment by SunnyWit** [comment]
Thank you

**Comment by Ericwwj** [comment]
Have you solved this problem yet? please. I'm having the same problem.

**Comment by SunnyWit** [comment]
The reason is that network was unstable.Try other time or change the PC



---Original---
From: ***@***.***&gt;
Date: Sat, May 25, 2024 15:06 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MRCIEU/TwoSampleMR] error Error: Cannot read token from alleged.rds file: mrbase.oauthError in readRDS(token_path): error reading fromconnection (#95)




 
Have you solved this problem yet? please. I'm having the same problem.
