### ISSUE TITLE
 adding start value to Forest plot () and scatter plot () function

### ISSUE THREAD

**Issue by RoaaNaa** [MRCIEU/TwoSampleMR#96]
Hello 
I want to add start value to forest plot and scatter plot V0=12345 ,but i don't know if this is possible and how the function in this case look like ??

regards 
Roaa

**Comment by explodecomputer** [comment]
Hi I don't quite understand the question but you can actually modify the scatter plot and forest plot outputs by adding extra ggplot layers like

```
mr_scatterplot(...)[[1]] +
geom_point() +
other_ggplot_layers() 
```

More about ggplot here https://ggplot2.tidyverse.org/
