### ISSUE TITLE
how to calculate se by TwoSampleMR package

### ISSUE THREAD

**Issue by SunnyWit** [MRCIEU/TwoSampleMR#98]
Hi, I want to calculate se,I input following code:
library(TwoSampleMR)
library(digest)
ao <- available_outcomes()
path <-  "G:\\MR"
setwd(path)
 L <- read.csv("Table2.csv")
get_se(L$beta, L$pval)#L$beta is effect size,L$pval is pvals
#then it showed error:
Error in get_se(L$beta, L$pval) : could not find function "get_se"
how can I solve this problem?
Thank you

**Comment by explodecomputer** [comment]
Try

```
TwoSampleMR:::get_se(L$beta, L$pval)
```
